; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4-nofpu -verify-machineinstrs < %s | FileCheck %s

; Two-operand instructions: the second operand is overwritten.

define i32 @add(i32 %a, i32 %b) {
; CHECK-LABEL: add:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    add r5,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %r = add i32 %a, %b
  ret i32 %r
}

define i32 @sub(i32 %a, i32 %b) {
; CHECK-LABEL: sub:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    sub r5,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %r = sub i32 %a, %b
  ret i32 %r
}

define i32 @and(i32 %a, i32 %b) {
; CHECK-LABEL: and:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    and r5,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %r = and i32 %a, %b
  ret i32 %r
}

define i32 @or(i32 %a, i32 %b) {
; CHECK-LABEL: or:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    or r5,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %r = or i32 %a, %b
  ret i32 %r
}

define i32 @xor(i32 %a, i32 %b) {
; CHECK-LABEL: xor:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    xor r5,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %r = xor i32 %a, %b
  ret i32 %r
}

define i32 @neg(i32 %a) {
; CHECK-LABEL: neg:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    neg r4,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %r = sub i32 0, %a
  ret i32 %r
}

define i32 @not(i32 %a) {
; CHECK-LABEL: not:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    not r4,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %r = xor i32 %a, -1
  ret i32 %r
}

; An immediate has eight bits and a sign.
define i32 @add_imm(i32 %a) {
; CHECK-LABEL: add_imm:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    add #100,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %r = add i32 %a, 100
  ret i32 %r
}

define i32 @add_imm_neg(i32 %a) {
; CHECK-LABEL: add_imm_neg:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    add #-128,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %r = add i32 %a, -128
  ret i32 %r
}

; Anything else is a literal.
define i32 @add_big(i32 %a) {
; CHECK-LABEL: add_big:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.l .Ltmp0,r0
; CHECK-NEXT:    add r4,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp0:
; CHECK-NEXT:    .ualong 100000
  %r = add i32 %a, 100000
  ret i32 %r
}

define i32 @zext8(i32 %a) {
; CHECK-LABEL: zext8:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    extu.b r4,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %r = and i32 %a, 255
  ret i32 %r
}

define i32 @zext16(i32 %a) {
; CHECK-LABEL: zext16:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    extu.w r4,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %r = and i32 %a, 65535
  ret i32 %r
}

define i32 @sext8(i8 signext %a) {
; CHECK-LABEL: sext8:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    add #1,r4
; CHECK-NEXT:    exts.b r4,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %b = add i8 %a, 1
  %r = sext i8 %b to i32
  ret i32 %r
}

define i32 @sext16(i16 signext %a) {
; CHECK-LABEL: sext16:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    add #1,r4
; CHECK-NEXT:    exts.w r4,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %b = add i16 %a, 1
  %r = sext i16 %b to i32
  ret i32 %r
}

define i32 @bswap(i32 %a) {
; CHECK-LABEL: bswap:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    swap.b r4,r1
; CHECK-NEXT:    swap.w r1,r1
; CHECK-NEXT:    swap.b r1,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %r = call i32 @llvm.bswap.i32(i32 %a)
  ret i32 %r
}

declare i32 @llvm.bswap.i32(i32)
