; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4-nofpu -verify-machineinstrs < %s | FileCheck %s

; A structure that is passed by value starts in the registers that are left
; and goes on on the stack.

%big = type { [20 x i32] }
%bytes = type { [100 x i8] }

declare void @take(i32, ptr byval(%big) align 4, i32)
declare void @take_bytes(ptr byval(%bytes) align 1)

; r5 to r7 get the first three words.  The rest is copied with a loop: a
; call of memcpy cannot stand between the arguments of another call.
define void @pass(ptr %p) {
; CHECK-LABEL: pass:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    add #-72,r15
; CHECK-NEXT:    .cfi_def_cfa_offset 76
; CHECK-NEXT:    mov r4,r1
; CHECK-NEXT:    add #12,r1
; CHECK-NEXT:    mov #17,r2
; CHECK-NEXT:    mov r15,r3
; CHECK-NEXT:  .LBB0_1: ! =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    mov.l @r1,r0
; CHECK-NEXT:    mov.l r0,@r3
; CHECK-NEXT:    add #4,r1
; CHECK-NEXT:    add #4,r3
; CHECK-NEXT:    add #-1,r2
; CHECK-NEXT:    tst r2,r2
; CHECK-NEXT:    bf .LBB0_1
; CHECK-NEXT:  ! %bb.2:
; CHECK-NEXT:    mov r15,r1
; CHECK-NEXT:    add #68,r1
; CHECK-NEXT:    mov #2,r2
; CHECK-NEXT:    mov.l r2,@r1
; CHECK-NEXT:    mov.l @(8,r4),r7
; CHECK-NEXT:    mov.l @(4,r4),r6
; CHECK-NEXT:    mov.l @r4,r5
; CHECK-NEXT:    mov.l .Ltmp0,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    mov #1,r4
; CHECK-NEXT:    add #72,r15
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.3:
; CHECK-NEXT:  .Ltmp0:
; CHECK-NEXT:    .ualong take
  call void @take(i32 1, ptr byval(%big) align 4 %p, i32 2)
  ret void
}

; Nothing says that the bytes are aligned: r4 to r7 are loaded byte by
; byte, and the loop moves bytes.
define void @pass_bytes(ptr %p) {
; CHECK-LABEL: pass_bytes:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    add #-84,r15
; CHECK-NEXT:    .cfi_def_cfa_offset 88
; CHECK-NEXT:    mov r4,r1
; CHECK-NEXT:    add #16,r1
; CHECK-NEXT:    mov #84,r2
; CHECK-NEXT:    mov r15,r3
; CHECK-NEXT:  .LBB1_1: ! =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    mov.b @r1,r0
; CHECK-NEXT:    mov.b r0,@r3
; CHECK-NEXT:    add #1,r1
; CHECK-NEXT:    add #1,r3
; CHECK-NEXT:    add #-1,r2
; CHECK-NEXT:    tst r2,r2
; CHECK-NEXT:    bf .LBB1_1
; CHECK-NEXT:  ! %bb.2:
; CHECK-NEXT:    mov r4,r1
; CHECK-NEXT:    add #3,r1
; CHECK-NEXT:    mov.b @r1,r1
; CHECK-NEXT:    mov #24,r2
; CHECK-NEXT:    shld r2,r1
; CHECK-NEXT:    mov r4,r3
; CHECK-NEXT:    add #2,r3
; CHECK-NEXT:    mov.b @r3,r3
; CHECK-NEXT:    extu.b r3,r3
; CHECK-NEXT:    shll16 r3
; CHECK-NEXT:    or r1,r3
; CHECK-NEXT:    mov.b @r4,r1
; CHECK-NEXT:    extu.b r1,r1
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    add #1,r0
; CHECK-NEXT:    mov.b @r0,r0
; CHECK-NEXT:    shll8 r0
; CHECK-NEXT:    or r1,r0
; CHECK-NEXT:    extu.w r0,r1
; CHECK-NEXT:    or r3,r1
; CHECK-NEXT:    mov r4,r3
; CHECK-NEXT:    add #7,r3
; CHECK-NEXT:    mov.b @r3,r3
; CHECK-NEXT:    shld r2,r3
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    add #6,r0
; CHECK-NEXT:    mov.b @r0,r0
; CHECK-NEXT:    extu.b r0,r0
; CHECK-NEXT:    shll16 r0
; CHECK-NEXT:    or r3,r0
; CHECK-NEXT:    mov r4,r3
; CHECK-NEXT:    add #4,r3
; CHECK-NEXT:    mov.b @r3,r3
; CHECK-NEXT:    extu.b r3,r3
; CHECK-NEXT:    mov r4,r7
; CHECK-NEXT:    add #5,r7
; CHECK-NEXT:    mov.b @r7,r7
; CHECK-NEXT:    shll8 r7
; CHECK-NEXT:    or r3,r7
; CHECK-NEXT:    extu.w r7,r5
; CHECK-NEXT:    or r0,r5
; CHECK-NEXT:    mov r4,r3
; CHECK-NEXT:    add #11,r3
; CHECK-NEXT:    mov.b @r3,r3
; CHECK-NEXT:    shld r2,r3
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    add #10,r0
; CHECK-NEXT:    mov.b @r0,r0
; CHECK-NEXT:    extu.b r0,r0
; CHECK-NEXT:    shll16 r0
; CHECK-NEXT:    or r3,r0
; CHECK-NEXT:    mov r4,r3
; CHECK-NEXT:    add #8,r3
; CHECK-NEXT:    mov.b @r3,r3
; CHECK-NEXT:    extu.b r3,r3
; CHECK-NEXT:    mov r4,r7
; CHECK-NEXT:    add #9,r7
; CHECK-NEXT:    mov.b @r7,r7
; CHECK-NEXT:    shll8 r7
; CHECK-NEXT:    or r3,r7
; CHECK-NEXT:    extu.w r7,r6
; CHECK-NEXT:    or r0,r6
; CHECK-NEXT:    mov r4,r3
; CHECK-NEXT:    add #15,r3
; CHECK-NEXT:    mov.b @r3,r3
; CHECK-NEXT:    shld r2,r3
; CHECK-NEXT:    mov r4,r2
; CHECK-NEXT:    add #14,r2
; CHECK-NEXT:    mov.b @r2,r2
; CHECK-NEXT:    extu.b r2,r2
; CHECK-NEXT:    shll16 r2
; CHECK-NEXT:    or r3,r2
; CHECK-NEXT:    mov r4,r3
; CHECK-NEXT:    add #12,r3
; CHECK-NEXT:    mov.b @r3,r3
; CHECK-NEXT:    extu.b r3,r3
; CHECK-NEXT:    add #13,r4
; CHECK-NEXT:    mov.b @r4,r0
; CHECK-NEXT:    shll8 r0
; CHECK-NEXT:    or r3,r0
; CHECK-NEXT:    extu.w r0,r7
; CHECK-NEXT:    or r2,r7
; CHECK-NEXT:    mov.l .Ltmp1,r2
; CHECK-NEXT:    jsr @r2
; CHECK-NEXT:    mov r1,r4
; CHECK-NEXT:    add #84,r15
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.3:
; CHECK-NEXT:  .Ltmp1:
; CHECK-NEXT:    .ualong take_bytes
  call void @take_bytes(ptr byval(%bytes) align 1 %p)
  ret void
}

; The callee stores the registers right below the words on the stack.
define i32 @get(i32 %a, ptr byval(%big) align 4 %s, i32 %b) {
; CHECK-LABEL: get:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    add #-12,r15
; CHECK-NEXT:    .cfi_def_cfa_offset 12
; CHECK-NEXT:    mov.l r5,@r15
; CHECK-NEXT:    mov.l r6,@(4,r15)
; CHECK-NEXT:    mov.l r7,@(8,r15)
; CHECK-NEXT:    mov.l @(20,r15),r1
; CHECK-NEXT:    add r5,r1
; CHECK-NEXT:    mov #80,r0
; CHECK-NEXT:    add r15,r0
; CHECK-NEXT:    mov.l @r0,r0
; CHECK-NEXT:    add r1,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    add #12,r15
  %p0 = getelementptr %big, ptr %s, i32 0, i32 0, i32 0
  %p5 = getelementptr %big, ptr %s, i32 0, i32 0, i32 5
  %v0 = load i32, ptr %p0
  %v5 = load i32, ptr %p5
  %s1 = add i32 %v0, %v5
  %s2 = add i32 %s1, %b
  ret i32 %s2
}
