; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4-nofpu -verify-machineinstrs < %s | FileCheck %s

; The convention without a floating point unit: the words of all arguments
; in a row, four in r4 to r7 and the rest on the stack.

declare i32 @callee4(i32, i32, i32, i32)
declare i32 @callee6(i32, i32, i32, i32, i32, i32)
declare i64 @callee64(i32, i64, i64)
declare void @callee_small(i8 signext, i16 zeroext)
declare void @callee_sret(ptr sret({ i32, i32, i32 }))
declare { i32, i32, i32, i32 } @callee_ret4()

define i32 @four(i32 %a) {
; CHECK-LABEL: four:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    mov r4,r7
; CHECK-NEXT:    mov.l .Ltmp0,r1
; CHECK-NEXT:    mov #1,r4
; CHECK-NEXT:    mov #2,r5
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    mov #3,r6
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp0:
; CHECK-NEXT:    .ualong callee4
  %r = call i32 @callee4(i32 1, i32 2, i32 3, i32 %a)
  ret i32 %r
}

; The fifth and the sixth word are on the stack.
define i32 @six(i32 %a, i32 %b) {
; CHECK-LABEL: six:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    add #-8,r15
; CHECK-NEXT:    .cfi_def_cfa_offset 12
; CHECK-NEXT:    mov #6,r1
; CHECK-NEXT:    mov.l r1,@(4,r15)
; CHECK-NEXT:    mov #5,r1
; CHECK-NEXT:    mov.l r1,@r15
; CHECK-NEXT:    mov.l .Ltmp1,r1
; CHECK-NEXT:    mov #3,r6
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    mov #4,r7
; CHECK-NEXT:    add #8,r15
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp1:
; CHECK-NEXT:    .ualong callee6
  %r = call i32 @callee6(i32 %a, i32 %b, i32 3, i32 4, i32 5, i32 6)
  ret i32 %r
}

; A 64-bit value can have one word in r7 and one on the stack.
define i64 @split(i64 %x) {
; CHECK-LABEL: split:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    add #-4,r15
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    mov r5,r6
; CHECK-NEXT:    mov r4,r5
; CHECK-NEXT:    mov.l r6,@r15
; CHECK-NEXT:    mov.l .Ltmp2,r1
; CHECK-NEXT:    mov #1,r4
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    mov r5,r7
; CHECK-NEXT:    add #4,r15
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp2:
; CHECK-NEXT:    .ualong callee64
  %r = call i64 @callee64(i32 1, i64 %x, i64 %x)
  ret i64 %r
}

define i32 @args_on_stack(i32 %a, i32 %b, i32 %c, i32 %d, i32 %e, i32 %f) {
; CHECK-LABEL: args_on_stack:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.l @(4,r15),r1
; CHECK-NEXT:    mov.l @r15,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    add r1,r0
  %s = add i32 %e, %f
  ret i32 %s
}

define void @small(i32 %a) {
; CHECK-LABEL: small:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    exts.b r4,r1
; CHECK-NEXT:    extu.w r4,r5
; CHECK-NEXT:    mov.l .Ltmp3,r2
; CHECK-NEXT:    jsr @r2
; CHECK-NEXT:    mov r1,r4
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp3:
; CHECK-NEXT:    .ualong callee_small
  %b = trunc i32 %a to i8
  %w = trunc i32 %a to i16
  call void @callee_small(i8 signext %b, i16 zeroext %w)
  ret void
}

; The address of a result in memory is passed in r2, and returned in r0.
define void @sret_caller() {
; CHECK-LABEL: sret_caller:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.l r14,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset r14, -4
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    .cfi_offset pr, -8
; CHECK-NEXT:    mov r15,r14
; CHECK-NEXT:    .cfi_def_cfa_register r14
; CHECK-NEXT:    add #-16,r15
; CHECK-NEXT:    mov #-8,r1
; CHECK-NEXT:    and r1,r15
; CHECK-NEXT:    mov.l .Ltmp4,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    mov r15,r2
; CHECK-NEXT:    mov r14,r15
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    mov.l @r15+,r14
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp4:
; CHECK-NEXT:    .ualong callee_sret
  %t = alloca { i32, i32, i32 }
  call void @callee_sret(ptr sret({ i32, i32, i32 }) %t)
  ret void
}

define void @sret_callee(ptr sret({ i32, i32, i32 }) %out, i32 %v) {
; CHECK-LABEL: sret_callee:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r2,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    mov.l r4,@r0
  store i32 %v, ptr %out
  ret void
}

; Up to four words come back in r0 to r3.
define { i32, i32, i32, i32 } @ret4(i32 %a) {
; CHECK-LABEL: ret4:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    mov #2,r1
; CHECK-NEXT:    mov #3,r2
; CHECK-NEXT:    rts
; CHECK-NEXT:    mov #4,r3
  %r0 = insertvalue { i32, i32, i32, i32 } poison, i32 %a, 0
  %r1 = insertvalue { i32, i32, i32, i32 } %r0, i32 2, 1
  %r2 = insertvalue { i32, i32, i32, i32 } %r1, i32 3, 2
  %r3 = insertvalue { i32, i32, i32, i32 } %r2, i32 4, 3
  ret { i32, i32, i32, i32 } %r3
}

define i32 @use_ret4() {
; CHECK-LABEL: use_ret4:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    mov.l .Ltmp5,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    nop
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    mov r3,r0
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp5:
; CHECK-NEXT:    .ualong callee_ret4
  %r = call { i32, i32, i32, i32 } @callee_ret4()
  %v = extractvalue { i32, i32, i32, i32 } %r, 3
  ret i32 %v
}

define i32 @indirect(ptr %f, i32 %a) {
; CHECK-LABEL: indirect:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    mov r4,r2
; CHECK-NEXT:    jsr @r2
; CHECK-NEXT:    mov r5,r4
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %r = call i32 %f(i32 %a)
  ret i32 %r
}
