; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4-nofpu -verify-machineinstrs < %s | FileCheck %s
; RUN: llc -mtriple=sh4eb-unknown-linux-gnu -mcpu=sh4-nofpu -verify-machineinstrs < %s | FileCheck %s --check-prefix=BE

; A sum or a difference of 64 bits: the lower halves with addc or subc and
; no carry coming in (clrt), the upper halves with the carry that this left
; in T.  The number with the other sign is negc twice.

define i64 @add(i64 %a, i64 %b) {
; CHECK-LABEL: add:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r5,r1
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    clrt
; CHECK-NEXT:    addc r6,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    addc r7,r1
;
; BE-LABEL: add:
; BE:         .cfi_startproc
; BE-NEXT:  ! %bb.0:
; BE-NEXT:    mov r5,r1
; BE-NEXT:    mov r4,r0
; BE-NEXT:    clrt
; BE-NEXT:    addc r7,r1
; BE-NEXT:    rts
; BE-NEXT:    addc r6,r0
  %r = add i64 %a, %b
  ret i64 %r
}

define i64 @sub(i64 %a, i64 %b) {
; CHECK-LABEL: sub:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r5,r1
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    clrt
; CHECK-NEXT:    subc r6,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    subc r7,r1
;
; BE-LABEL: sub:
; BE:         .cfi_startproc
; BE-NEXT:  ! %bb.0:
; BE-NEXT:    mov r5,r1
; BE-NEXT:    mov r4,r0
; BE-NEXT:    clrt
; BE-NEXT:    subc r7,r1
; BE-NEXT:    rts
; BE-NEXT:    subc r6,r0
  %r = sub i64 %a, %b
  ret i64 %r
}

define i64 @neg(i64 %a) {
; CHECK-LABEL: neg:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    clrt
; CHECK-NEXT:    negc r4,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    negc r5,r1
;
; BE-LABEL: neg:
; BE:         .cfi_startproc
; BE-NEXT:  ! %bb.0:
; BE-NEXT:    clrt
; BE-NEXT:    negc r5,r1
; BE-NEXT:    rts
; BE-NEXT:    negc r4,r0
  %r = sub i64 0, %a
  ret i64 %r
}

; The upper half of the second operand is its sign, which is computed
; between the two subtractions: nothing there may change T.
define i64 @sub_int(i64 %a, i32 %b) {
; CHECK-LABEL: sub_int:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r5,r1
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    mov #-31,r2
; CHECK-NEXT:    clrt
; CHECK-NEXT:    subc r6,r0
; CHECK-NEXT:    shad r2,r6
; CHECK-NEXT:    rts
; CHECK-NEXT:    subc r6,r1
;
; BE-LABEL: sub_int:
; BE:         .cfi_startproc
; BE-NEXT:  ! %bb.0:
; BE-NEXT:    mov r5,r1
; BE-NEXT:    mov r4,r0
; BE-NEXT:    mov #-31,r2
; BE-NEXT:    clrt
; BE-NEXT:    subc r6,r1
; BE-NEXT:    shad r2,r6
; BE-NEXT:    rts
; BE-NEXT:    subc r6,r0
  %w = sext i32 %b to i64
  %r = sub i64 %a, %w
  ret i64 %r
}

; A comparison of the result needs T again.
define i32 @add_compare(i64 %a, i64 %b, i32 %c) {
; CHECK-LABEL: add_compare:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r5,r0
; CHECK-NEXT:    clrt
; CHECK-NEXT:    addc r6,r4
; CHECK-NEXT:    addc r7,r0
; CHECK-NEXT:    mov.l @r15,r1
; CHECK-NEXT:    cmp/hi r1,r4
; CHECK-NEXT:    bt .LBB4_2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:  .LBB4_2:
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
;
; BE-LABEL: add_compare:
; BE:         .cfi_startproc
; BE-NEXT:  ! %bb.0:
; BE-NEXT:    mov r4,r0
; BE-NEXT:    clrt
; BE-NEXT:    addc r7,r5
; BE-NEXT:    addc r6,r0
; BE-NEXT:    mov.l @r15,r1
; BE-NEXT:    cmp/hi r1,r5
; BE-NEXT:    bt .LBB4_2
; BE-NEXT:  ! %bb.1:
; BE-NEXT:    mov r5,r0
; BE-NEXT:  .LBB4_2:
; BE-NEXT:    rts
; BE-NEXT:    nop
  %s = add i64 %a, %b
  %lo = trunc i64 %s to i32
  %hi64 = lshr i64 %s, 32
  %hi = trunc i64 %hi64 to i32
  %cmp = icmp ugt i32 %lo, %c
  %r = select i1 %cmp, i32 %hi, i32 %lo
  ret i32 %r
}
