; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4-nofpu -verify-machineinstrs < %s | FileCheck %s

; A comparison sets T.  movt copies it, bt and bf branch on it.

define i32 @eq(i32 %a, i32 %b) {
; CHECK-LABEL: eq:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    cmp/eq r5,r4
; CHECK-NEXT:    rts
; CHECK-NEXT:    movt r0
  %c = icmp eq i32 %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}

define i32 @ne(i32 %a, i32 %b) {
; CHECK-LABEL: ne:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    cmp/eq r5,r4
; CHECK-NEXT:    mov #-1,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    negc r0,r0
  %c = icmp ne i32 %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}

define i32 @slt(i32 %a, i32 %b) {
; CHECK-LABEL: slt:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    cmp/gt r4,r5
; CHECK-NEXT:    rts
; CHECK-NEXT:    movt r0
  %c = icmp slt i32 %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}

define i32 @sge(i32 %a, i32 %b) {
; CHECK-LABEL: sge:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    cmp/ge r5,r4
; CHECK-NEXT:    rts
; CHECK-NEXT:    movt r0
  %c = icmp sge i32 %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}

define i32 @sgt(i32 %a, i32 %b) {
; CHECK-LABEL: sgt:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    cmp/gt r5,r4
; CHECK-NEXT:    rts
; CHECK-NEXT:    movt r0
  %c = icmp sgt i32 %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}

define i32 @ult(i32 %a, i32 %b) {
; CHECK-LABEL: ult:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    cmp/hi r4,r5
; CHECK-NEXT:    rts
; CHECK-NEXT:    movt r0
  %c = icmp ult i32 %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}

define i32 @ugt(i32 %a, i32 %b) {
; CHECK-LABEL: ugt:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    cmp/hi r5,r4
; CHECK-NEXT:    rts
; CHECK-NEXT:    movt r0
  %c = icmp ugt i32 %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}

; The forms that compare with zero.

define i32 @eq0(i32 %a) {
; CHECK-LABEL: eq0:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    tst r4,r4
; CHECK-NEXT:    rts
; CHECK-NEXT:    movt r0
  %c = icmp eq i32 %a, 0
  %r = zext i1 %c to i32
  ret i32 %r
}

define i32 @gt0(i32 %a) {
; CHECK-LABEL: gt0:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    cmp/pl r4
; CHECK-NEXT:    rts
; CHECK-NEXT:    movt r0
  %c = icmp sgt i32 %a, 0
  %r = zext i1 %c to i32
  ret i32 %r
}

define i32 @ge0(i32 %a) {
; CHECK-LABEL: ge0:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    not r4,r0
; CHECK-NEXT:    mov #-31,r1
; CHECK-NEXT:    rts
; CHECK-NEXT:    shld r1,r0
  %c = icmp sge i32 %a, 0
  %r = zext i1 %c to i32
  ret i32 %r
}

define i32 @test_bits(i32 %a, i32 %b) {
; CHECK-LABEL: test_bits:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    tst r5,r4
; CHECK-NEXT:    rts
; CHECK-NEXT:    movt r0
  %m = and i32 %a, %b
  %c = icmp eq i32 %m, 0
  %r = zext i1 %c to i32
  ret i32 %r
}

; A selection is a branch around a copy.
define i32 @select(i32 %a, i32 %b, i32 %x, i32 %y) {
; CHECK-LABEL: select:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r6,r0
; CHECK-NEXT:    cmp/gt r4,r5
; CHECK-NEXT:    bt .LBB11_2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:    mov r7,r0
; CHECK-NEXT:  .LBB11_2:
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %c = icmp slt i32 %a, %b
  %r = select i1 %c, i32 %x, i32 %y
  ret i32 %r
}

declare void @f()
declare void @g()

define void @branch(i32 %a, i32 %b) {
; CHECK-LABEL: branch:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    cmp/hs r5,r4
; CHECK-NEXT:    bt .LBB12_3
; CHECK-NEXT:  ! %bb.1: ! %t
; CHECK-NEXT:    mov.l .Ltmp0,r1
; CHECK-NEXT:    bra .LBB12_2
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.4:
; CHECK-NEXT:  .Ltmp0:
; CHECK-NEXT:    .ualong f
; CHECK-NEXT:  .LBB12_3: ! %e
; CHECK-NEXT:    mov.l .Ltmp1,r1
; CHECK-NEXT:  .LBB12_2: ! %t
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    nop
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.5:
; CHECK-NEXT:  .Ltmp1:
; CHECK-NEXT:    .ualong g
  %c = icmp ult i32 %a, %b
  br i1 %c, label %t, label %e
t:
  call void @f()
  ret void
e:
  call void @g()
  ret void
}

define i32 @eq64(i64 %a, i64 %b) {
; CHECK-LABEL: eq64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    xor r7,r5
; CHECK-NEXT:    xor r6,r4
; CHECK-NEXT:    or r5,r4
; CHECK-NEXT:    tst r4,r4
; CHECK-NEXT:    rts
; CHECK-NEXT:    movt r0
  %c = icmp eq i64 %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}

define i32 @slt64(i64 %a, i64 %b) {
; CHECK-LABEL: slt64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    cmp/gt r5,r7
; CHECK-NEXT:    movt r1
; CHECK-NEXT:    cmp/hi r4,r6
; CHECK-NEXT:    movt r0
; CHECK-NEXT:    cmp/eq r7,r5
; CHECK-NEXT:    bt .LBB14_2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:    mov r1,r0
; CHECK-NEXT:  .LBB14_2:
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %c = icmp slt i64 %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}
