; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4-nofpu -verify-machineinstrs < %s | FileCheck %s
; RUN: llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4-nofpu -verify-machineinstrs -sh-fill-delay-slots=0 < %s | FileCheck %s --check-prefix=NOP

; bra, jsr and rts run the instruction behind them before they take effect.
; The instruction in front of the branch is written there where that is the
; same, see delay-slot.mir for the rules.

declare i32 @ext(i32, i32)

; The addition is in the slot of the return.
define i32 @ret(ptr %p) {
; CHECK-LABEL: ret:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.l @r4,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    add #3,r0
;
; NOP-LABEL: ret:
; NOP:         .cfi_startproc
; NOP-NEXT:  ! %bb.0:
; NOP-NEXT:    mov.l @r4,r0
; NOP-NEXT:    add #3,r0
; NOP-NEXT:    rts
; NOP-NEXT:    nop
  %v = load i32, ptr %p
  %r = add i32 %v, 3
  ret i32 %r
}

; The argument is computed in the slot of the call.  The load of pr is not
; in the slot of the return, which has read pr by then.
define i32 @call(i32 %a, i32 %b) {
; CHECK-LABEL: call:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    mov.l .Ltmp0,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    add #1,r4
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp0:
; CHECK-NEXT:    .ualong ext
;
; NOP-LABEL: call:
; NOP:         .cfi_startproc
; NOP-NEXT:  ! %bb.0:
; NOP-NEXT:    sts.l pr,@-r15
; NOP-NEXT:    .cfi_def_cfa_offset 4
; NOP-NEXT:    .cfi_offset pr, -4
; NOP-NEXT:    add #1,r4
; NOP-NEXT:    mov.l .Ltmp0,r1
; NOP-NEXT:    jsr @r1
; NOP-NEXT:    nop
; NOP-NEXT:    lds.l @r15+,pr
; NOP-NEXT:    rts
; NOP-NEXT:    nop
; NOP-NEXT:    .p2align 2
; NOP-NEXT:  ! %bb.1:
; NOP-NEXT:  .Ltmp0:
; NOP-NEXT:    .ualong ext
  %x = add i32 %a, 1
  %r = call i32 @ext(i32 %x, i32 %b)
  ret i32 %r
}

; The slot of the bra that jumps over the other arm.
define i32 @join(i32 %a, i32 %b, ptr %p) {
; CHECK-LABEL: join:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0: ! %entry
; CHECK-NEXT:    mov.l r8,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset r8, -4
; CHECK-NEXT:    mov.l r9,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    .cfi_offset r9, -8
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 12
; CHECK-NEXT:    .cfi_offset pr, -12
; CHECK-NEXT:    mov r4,r8
; CHECK-NEXT:    tst r8,r8
; CHECK-NEXT:    bt .LBB2_1
; CHECK-NEXT:  ! %bb.2: ! %two
; CHECK-NEXT:    mov.l @r6,r1
; CHECK-NEXT:    bra .LBB2_3
; CHECK-NEXT:    xor r1,r5
; CHECK-NEXT:  .LBB2_1: ! %one
; CHECK-NEXT:    mov.l r5,@r6
; CHECK-NEXT:    add #5,r5
; CHECK-NEXT:  .LBB2_3: ! %end
; CHECK-NEXT:    mov.l .Ltmp1,r9
; CHECK-NEXT:    mov r5,r4
; CHECK-NEXT:    jsr @r9
; CHECK-NEXT:    mov r8,r5
; CHECK-NEXT:    mov r0,r4
; CHECK-NEXT:    jsr @r9
; CHECK-NEXT:    mov r8,r5
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    mov.l @r15+,r9
; CHECK-NEXT:    rts
; CHECK-NEXT:    mov.l @r15+,r8
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.4:
; CHECK-NEXT:  .Ltmp1:
; CHECK-NEXT:    .ualong ext
;
; NOP-LABEL: join:
; NOP:         .cfi_startproc
; NOP-NEXT:  ! %bb.0: ! %entry
; NOP-NEXT:    mov.l r8,@-r15
; NOP-NEXT:    .cfi_def_cfa_offset 4
; NOP-NEXT:    .cfi_offset r8, -4
; NOP-NEXT:    mov.l r9,@-r15
; NOP-NEXT:    .cfi_def_cfa_offset 8
; NOP-NEXT:    .cfi_offset r9, -8
; NOP-NEXT:    sts.l pr,@-r15
; NOP-NEXT:    .cfi_def_cfa_offset 12
; NOP-NEXT:    .cfi_offset pr, -12
; NOP-NEXT:    mov r4,r8
; NOP-NEXT:    tst r8,r8
; NOP-NEXT:    bt .LBB2_1
; NOP-NEXT:  ! %bb.2: ! %two
; NOP-NEXT:    mov.l @r6,r1
; NOP-NEXT:    xor r1,r5
; NOP-NEXT:    bra .LBB2_3
; NOP-NEXT:    nop
; NOP-NEXT:  .LBB2_1: ! %one
; NOP-NEXT:    mov.l r5,@r6
; NOP-NEXT:    add #5,r5
; NOP-NEXT:  .LBB2_3: ! %end
; NOP-NEXT:    mov.l .Ltmp1,r9
; NOP-NEXT:    mov r5,r4
; NOP-NEXT:    mov r8,r5
; NOP-NEXT:    jsr @r9
; NOP-NEXT:    nop
; NOP-NEXT:    mov r0,r4
; NOP-NEXT:    mov r8,r5
; NOP-NEXT:    jsr @r9
; NOP-NEXT:    nop
; NOP-NEXT:    lds.l @r15+,pr
; NOP-NEXT:    mov.l @r15+,r9
; NOP-NEXT:    mov.l @r15+,r8
; NOP-NEXT:    rts
; NOP-NEXT:    nop
; NOP-NEXT:    .p2align 2
; NOP-NEXT:  ! %bb.4:
; NOP-NEXT:  .Ltmp1:
; NOP-NEXT:    .ualong ext
entry:
  %c = icmp eq i32 %a, 0
  br i1 %c, label %one, label %two

one:
  store volatile i32 %b, ptr %p
  %x = add i32 %b, 5
  br label %end

two:
  %v = load volatile i32, ptr %p
  %y = xor i32 %v, %b
  br label %end

end:
  %r = phi i32 [ %x, %one ], [ %y, %two ]
  %q = call i32 @ext(i32 %r, i32 %a)
  %s = call i32 @ext(i32 %q, i32 %a)
  ret i32 %s
}

; A function that is not to be optimized keeps its nops.
define void @plain(ptr %p) optnone noinline {
; CHECK-LABEL: plain:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov #1,r1
; CHECK-NEXT:    mov.l r1,@r4
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
;
; NOP-LABEL: plain:
; NOP:         .cfi_startproc
; NOP-NEXT:  ! %bb.0:
; NOP-NEXT:    mov #1,r1
; NOP-NEXT:    mov.l r1,@r4
; NOP-NEXT:    rts
; NOP-NEXT:    nop
  store i32 1, ptr %p
  ret void
}
