; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4-nofpu -verify-machineinstrs < %s | FileCheck --check-prefix=LE %s
; RUN: llc -mtriple=sh4eb-unknown-linux-gnu -mcpu=sh4-nofpu -verify-machineinstrs < %s | FileCheck --check-prefix=BE %s

; The halves of a 64-bit value are in the order of memory: the low one is
; in r0 and r4 on a little-endian processor, the high one on a big-endian.

define i64 @ret64() {
; LE-LABEL: ret64:
; LE:         .cfi_startproc
; LE-NEXT:  ! %bb.0:
; LE-NEXT:    mov #2,r0
; LE-NEXT:    rts
; LE-NEXT:    mov #1,r1
;
; BE-LABEL: ret64:
; BE:         .cfi_startproc
; BE-NEXT:  ! %bb.0:
; BE-NEXT:    mov #1,r0
; BE-NEXT:    rts
; BE-NEXT:    mov #2,r1
  ret i64 4294967298
}

define i32 @high(i64 %a) {
; LE-LABEL: high:
; LE:         .cfi_startproc
; LE-NEXT:  ! %bb.0:
; LE-NEXT:    rts
; LE-NEXT:    mov r5,r0
;
; BE-LABEL: high:
; BE:         .cfi_startproc
; BE-NEXT:  ! %bb.0:
; BE-NEXT:    rts
; BE-NEXT:    mov r4,r0
  %s = lshr i64 %a, 32
  %r = trunc i64 %s to i32
  ret i32 %r
}

define i32 @load_low(ptr %p) {
; LE-LABEL: load_low:
; LE:         .cfi_startproc
; LE-NEXT:  ! %bb.0:
; LE-NEXT:    rts
; LE-NEXT:    mov.l @r4,r0
;
; BE-LABEL: load_low:
; BE:         .cfi_startproc
; BE-NEXT:  ! %bb.0:
; BE-NEXT:    rts
; BE-NEXT:    mov.l @(4,r4),r0
  %v = load i64, ptr %p
  %r = trunc i64 %v to i32
  ret i32 %r
}
