; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4-nofpu -verify-machineinstrs < %s | FileCheck %s
; RUN: llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4-nofpu -relocation-model=pic -verify-machineinstrs < %s | FileCheck %s --check-prefix=PIC

; A call that an exception can leave through a handler.  The unwinder of
; libgcc enters the handler with the exception in r4 and the number of what
; matched in r5.  The table of the function says which calls have a handler
; (the range of a call ends behind its delay slot) and is found through the
; unwind information.  In position independent code the references from
; there are relative and go through a pointer in writable data.

declare void @may_throw(i32)
declare i32 @__gxx_personality_v0(...)
declare ptr @__cxa_begin_catch(ptr)
declare void @__cxa_end_catch()
declare i32 @llvm.eh.typeid.for(ptr)
@_ZTIi = external constant ptr

define i32 @catcher(i32 %x) personality ptr @__gxx_personality_v0 {
; CHECK-LABEL: catcher:
; CHECK:       .Lfunc_begin0:
; CHECK-NEXT:    .cfi_startproc
; CHECK-NEXT:    .cfi_personality 0, __gxx_personality_v0
; CHECK-NEXT:    .cfi_lsda 0, .Lexception0
; CHECK-NEXT:  ! %bb.0: ! %entry
; CHECK-NEXT:    mov.l r8,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset r8, -4
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    .cfi_offset pr, -8
; CHECK-NEXT:  .Ltmp0: ! EH_LABEL
; CHECK-NEXT:    mov.l .Ltmp3,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    nop
; CHECK-NEXT:  .Ltmp1: ! EH_LABEL
; CHECK-NEXT:  ! %bb.1: ! %done
; CHECK-NEXT:    mov #0,r0
; CHECK-NEXT:  .LBB0_2: ! %done
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    mov.l @r15+,r8
; CHECK-NEXT:  .LBB0_3: ! %lpad
; CHECK-NEXT:  .Ltmp2: ! EH_LABEL
; CHECK-NEXT:    mov r5,r0
; CHECK-NEXT:    cmp/eq #1,r0
; CHECK-NEXT:    bf .LBB0_5
; CHECK-NEXT:  ! %bb.4: ! %catch
; CHECK-NEXT:    mov.l .Ltmp4,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    nop
; CHECK-NEXT:    mov.l @r0,r8
; CHECK-NEXT:    mov.l .Ltmp5,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    nop
; CHECK-NEXT:    bra .LBB0_2
; CHECK-NEXT:    mov r8,r0
; CHECK-NEXT:  .LBB0_5: ! %resume
; CHECK-NEXT:    mov.l .Ltmp6,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.6:
; CHECK-NEXT:  .Ltmp3:
; CHECK-NEXT:    .ualong may_throw
; CHECK-NEXT:  .Ltmp4:
; CHECK-NEXT:    .ualong __cxa_begin_catch
; CHECK-NEXT:  .Ltmp5:
; CHECK-NEXT:    .ualong __cxa_end_catch
; CHECK-NEXT:  .Ltmp6:
; CHECK-NEXT:    .ualong _Unwind_Resume
;
; PIC-LABEL: catcher:
; PIC:       .Lfunc_begin0:
; PIC-NEXT:    .cfi_startproc
; PIC-NEXT:    .cfi_personality 155, DW.ref.__gxx_personality_v0
; PIC-NEXT:    .cfi_lsda 27, .Lexception0
; PIC-NEXT:  ! %bb.0: ! %entry
; PIC-NEXT:    mov.l r8,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 4
; PIC-NEXT:    .cfi_offset r8, -4
; PIC-NEXT:    mov.l r12,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 8
; PIC-NEXT:    .cfi_offset r12, -8
; PIC-NEXT:    sts.l pr,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 12
; PIC-NEXT:    .cfi_offset pr, -12
; PIC-NEXT:    mova .Ltmp7,r0
; PIC-NEXT:    mov.l .Ltmp7,r12
; PIC-NEXT:    add r0,r12
; PIC-NEXT:  .Ltmp0: ! EH_LABEL
; PIC-NEXT:    mov.l .Ltmp8,r1
; PIC-NEXT:    bsrf r1
; PIC-NEXT:  .Ltmp1:
; PIC-NEXT:    nop
; PIC-NEXT:  .Ltmp2: ! EH_LABEL
; PIC-NEXT:  ! %bb.1: ! %done
; PIC-NEXT:    mov #0,r0
; PIC-NEXT:  .LBB0_2: ! %done
; PIC-NEXT:    lds.l @r15+,pr
; PIC-NEXT:    mov.l @r15+,r12
; PIC-NEXT:    rts
; PIC-NEXT:    mov.l @r15+,r8
; PIC-NEXT:  .LBB0_3: ! %lpad
; PIC-NEXT:  .Ltmp3: ! EH_LABEL
; PIC-NEXT:    mov r5,r0
; PIC-NEXT:    cmp/eq #1,r0
; PIC-NEXT:    bf .LBB0_5
; PIC-NEXT:  ! %bb.4: ! %catch
; PIC-NEXT:    mov.l .Ltmp9,r1
; PIC-NEXT:    bsrf r1
; PIC-NEXT:  .Ltmp5:
; PIC-NEXT:    nop
; PIC-NEXT:    mov.l @r0,r8
; PIC-NEXT:    mov.l .Ltmp10,r1
; PIC-NEXT:    bsrf r1
; PIC-NEXT:  .Ltmp6:
; PIC-NEXT:    nop
; PIC-NEXT:    bra .LBB0_2
; PIC-NEXT:    mov r8,r0
; PIC-NEXT:  .LBB0_5: ! %resume
; PIC-NEXT:    mov.l .Ltmp11,r1
; PIC-NEXT:    bsrf r1
; PIC-NEXT:  .Ltmp4:
; PIC-NEXT:    nop
; PIC-NEXT:    .p2align 2
; PIC-NEXT:  ! %bb.6:
; PIC-NEXT:  .Ltmp7:
; PIC-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
; PIC-NEXT:  .Ltmp8:
; PIC-NEXT:    .ualong may_throw@PLT-(.Ltmp1+2-.Ltmp8)
; PIC-NEXT:  .Ltmp9:
; PIC-NEXT:    .ualong __cxa_begin_catch@PLT-(.Ltmp5+2-.Ltmp9)
; PIC-NEXT:  .Ltmp10:
; PIC-NEXT:    .ualong __cxa_end_catch@PLT-(.Ltmp6+2-.Ltmp10)
; PIC-NEXT:  .Ltmp11:
; PIC-NEXT:    .ualong _Unwind_Resume@PLT-(.Ltmp4+2-.Ltmp11)
entry:
  invoke void @may_throw(i32 %x)
          to label %done unwind label %lpad

lpad:
  %lp = landingpad { ptr, i32 }
          cleanup
          catch ptr @_ZTIi
  %exn = extractvalue { ptr, i32 } %lp, 0
  %sel = extractvalue { ptr, i32 } %lp, 1
  %id = call i32 @llvm.eh.typeid.for(ptr @_ZTIi)
  %match = icmp eq i32 %sel, %id
  br i1 %match, label %catch, label %resume

catch:
  %obj = call ptr @__cxa_begin_catch(ptr %exn)
  %v = load i32, ptr %obj
  call void @__cxa_end_catch()
  ret i32 %v

resume:
  resume { ptr, i32 } %lp

done:
  ret i32 0
}

; The table of the function, as position independent code has it.
; PIC-LABEL: GCC_except_table0:
; PIC-NEXT:  .Lexception0:
; PIC-NEXT:    .byte 255 ! @LPStart Encoding = omit
; PIC-NEXT:    .byte 155 ! @TType Encoding = indirect pcrel sdata4
; PIC:         .uleb128 .Ltmp0-.Lfunc_begin0 ! >> Call Site 1 <<
; PIC-NEXT:    .uleb128 .Ltmp2-.Ltmp0 ! Call between .Ltmp0 and .Ltmp2
; PIC-NEXT:    .uleb128 .Ltmp3-.Lfunc_begin0 ! jumps to .Ltmp3
; PIC:       .Ltmp{{[0-9]+}}: ! TypeInfo 1
; PIC-NEXT:    .ualong .L_ZTIi.DW.stub-.Ltmp{{[0-9]+}}
; PIC:       DW.ref.__gxx_personality_v0:
; PIC-NEXT:    .ualong __gxx_personality_v0
