; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=sh4-unknown-linux-gnu -verify-machineinstrs < %s | FileCheck %s

; fcmp/eq and fcmp/gt are false if an operand is not a number.  They and
; their opposites are six of the conditions, the others are made from them.

define i32 @oeq(double %a, double %b) {
; CHECK-LABEL: oeq:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    fcmp/eq dr6,dr4
; CHECK-NEXT:    rts
; CHECK-NEXT:    movt r0
  %c = fcmp oeq double %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}

define i32 @une(double %a, double %b) {
; CHECK-LABEL: une:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    fcmp/eq dr6,dr4
; CHECK-NEXT:    mov #-1,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    negc r0,r0
  %c = fcmp une double %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}

define i32 @ogt(double %a, double %b) {
; CHECK-LABEL: ogt:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    fcmp/gt dr6,dr4
; CHECK-NEXT:    rts
; CHECK-NEXT:    movt r0
  %c = fcmp ogt double %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}

define i32 @olt(double %a, double %b) {
; CHECK-LABEL: olt:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    fcmp/gt dr4,dr6
; CHECK-NEXT:    rts
; CHECK-NEXT:    movt r0
  %c = fcmp olt double %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}

define i32 @ule(double %a, double %b) {
; CHECK-LABEL: ule:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    fcmp/gt dr6,dr4
; CHECK-NEXT:    mov #-1,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    negc r0,r0
  %c = fcmp ule double %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}

define i32 @uge(double %a, double %b) {
; CHECK-LABEL: uge:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    fcmp/gt dr4,dr6
; CHECK-NEXT:    mov #-1,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    negc r0,r0
  %c = fcmp uge double %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}

; "Greater or equal" is two comparisons.
define i32 @oge(double %a, double %b) {
; CHECK-LABEL: oge:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    fcmp/gt dr4,dr6
; CHECK-NEXT:    mov #-1,r1
; CHECK-NEXT:    negc r1,r1
; CHECK-NEXT:    fcmp/eq dr6,dr6
; CHECK-NEXT:    movt r2
; CHECK-NEXT:    fcmp/eq dr4,dr4
; CHECK-NEXT:    movt r0
; CHECK-NEXT:    and r2,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    and r1,r0
  %c = fcmp oge double %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}

define i32 @uno(double %a, double %b) {
; CHECK-LABEL: uno:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    fcmp/eq dr6,dr6
; CHECK-NEXT:    mov #-1,r1
; CHECK-NEXT:    negc r1,r1
; CHECK-NEXT:    fcmp/eq dr4,dr4
; CHECK-NEXT:    mov #-1,r0
; CHECK-NEXT:    negc r0,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    or r1,r0
  %c = fcmp uno double %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}

declare void @f()

; The change of the precision stands between the comparison and the branch:
; it leaves T alone.
define void @branch(float %a, float %b) {
; CHECK-LABEL: branch:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    mov #8,r1
; CHECK-NEXT:    shll16 r1
; CHECK-NEXT:    sts fpscr,r2
; CHECK-NEXT:    xor r1,r2
; CHECK-NEXT:    lds r2,fpscr
; CHECK-NEXT:    fcmp/gt fr5,fr4
; CHECK-NEXT:    mov #8,r1
; CHECK-NEXT:    shll16 r1
; CHECK-NEXT:    sts fpscr,r2
; CHECK-NEXT:    xor r1,r2
; CHECK-NEXT:    lds r2,fpscr
; CHECK-NEXT:    bf .LBB8_2
; CHECK-NEXT:  ! %bb.1: ! %t
; CHECK-NEXT:    mov.l .Ltmp0,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    nop
; CHECK-NEXT:  .LBB8_2: ! %e
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.3:
; CHECK-NEXT:  .Ltmp0:
; CHECK-NEXT:    .ualong f
  %c = fcmp olt float %a, %b
  br i1 %c, label %t, label %e
t:
  call void @f()
  ret void
e:
  ret void
}

define double @select(double %a, double %b, double %x, double %y) {
; CHECK-LABEL: select:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    fmov fr8,fr0
; CHECK-NEXT:    fmov fr9,fr1
; CHECK-NEXT:    fcmp/gt dr6,dr4
; CHECK-NEXT:    bt .LBB9_2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:    fmov fr10,fr0
; CHECK-NEXT:    fmov fr11,fr1
; CHECK-NEXT:  .LBB9_2:
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %c = fcmp ogt double %a, %b
  %r = select i1 %c, double %x, double %y
  ret double %r
}
