; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=sh4-unknown-linux-gnu -verify-machineinstrs < %s | FileCheck --check-prefix=LE %s
; RUN: llc -mtriple=sh4eb-unknown-linux-gnu -verify-machineinstrs < %s | FileCheck --check-prefix=BE %s
; RUN: llc -mtriple=sh3e-unknown-linux-gnu -verify-machineinstrs < %s | FileCheck --check-prefix=SH3E %s

; The convention with a floating point unit.  float goes to fr4 to fr11,
; on a little-endian SH-4 with the two registers of a pair exchanged: fr5,
; fr4, fr7.  double goes to dr4 to dr10, and the SH-3E computes it in
; software and passes it in r4 to r7.

@gf = global [4 x float] zeroinitializer
@gd = global [4 x double] zeroinitializer
@gi = global [4 x i32] zeroinitializer

define void @floats(float %a, float %b, float %c) {
; LE-LABEL: floats:
; LE:         .cfi_startproc
; LE-NEXT:  ! %bb.0:
; LE-NEXT:    mov.l .Ltmp0,r1
; LE-NEXT:    fmov.s fr5,@r1
; LE-NEXT:    mov r1,r2
; LE-NEXT:    add #8,r2
; LE-NEXT:    fmov.s fr7,@r2
; LE-NEXT:    add #4,r1
; LE-NEXT:    rts
; LE-NEXT:    fmov.s fr4,@r1
; LE-NEXT:    .p2align 2
; LE-NEXT:  ! %bb.1:
; LE-NEXT:  .Ltmp0:
; LE-NEXT:    .ualong gf
;
; BE-LABEL: floats:
; BE:         .cfi_startproc
; BE-NEXT:  ! %bb.0:
; BE-NEXT:    mov.l .Ltmp0,r1
; BE-NEXT:    fmov.s fr4,@r1
; BE-NEXT:    mov r1,r2
; BE-NEXT:    add #8,r2
; BE-NEXT:    fmov.s fr6,@r2
; BE-NEXT:    add #4,r1
; BE-NEXT:    rts
; BE-NEXT:    fmov.s fr5,@r1
; BE-NEXT:    .p2align 2
; BE-NEXT:  ! %bb.1:
; BE-NEXT:  .Ltmp0:
; BE-NEXT:    .ualong gf
;
; SH3E-LABEL: floats:
; SH3E:         .cfi_startproc
; SH3E-NEXT:  ! %bb.0:
; SH3E-NEXT:    mov.l .Ltmp0,r1
; SH3E-NEXT:    fmov.s fr4,@r1
; SH3E-NEXT:    mov r1,r2
; SH3E-NEXT:    add #8,r2
; SH3E-NEXT:    fmov.s fr6,@r2
; SH3E-NEXT:    add #4,r1
; SH3E-NEXT:    rts
; SH3E-NEXT:    fmov.s fr5,@r1
; SH3E-NEXT:    .p2align 2
; SH3E-NEXT:  ! %bb.1:
; SH3E-NEXT:  .Ltmp0:
; SH3E-NEXT:    .ualong gf
  store float %a, ptr @gf
  store float %b, ptr getelementptr ([4 x float], ptr @gf, i32 0, i32 1)
  store float %c, ptr getelementptr ([4 x float], ptr @gf, i32 0, i32 2)
  ret void
}

; A double starts at an even register, and the one that it skips stays
; empty: c is in fr9 (fr8 on a big-endian processor), not in fr4.
define void @mixed(float %a, double %b, float %c) {
; LE-LABEL: mixed:
; LE:         .cfi_startproc
; LE-NEXT:  ! %bb.0:
; LE-NEXT:    mov.l .Ltmp1,r1
; LE-NEXT:    add #8,r1
; LE-NEXT:    fmov.s fr6,@-r1
; LE-NEXT:    fmov.s fr7,@-r1
; LE-NEXT:    mov.l .Ltmp2,r1
; LE-NEXT:    fmov.s fr5,@r1
; LE-NEXT:    add #4,r1
; LE-NEXT:    rts
; LE-NEXT:    fmov.s fr9,@r1
; LE-NEXT:    .p2align 2
; LE-NEXT:  ! %bb.1:
; LE-NEXT:  .Ltmp1:
; LE-NEXT:    .ualong gd
; LE-NEXT:  .Ltmp2:
; LE-NEXT:    .ualong gf
;
; BE-LABEL: mixed:
; BE:         .cfi_startproc
; BE-NEXT:  ! %bb.0:
; BE-NEXT:    mov.l .Ltmp1,r1
; BE-NEXT:    add #8,r1
; BE-NEXT:    fmov.s fr7,@-r1
; BE-NEXT:    fmov.s fr6,@-r1
; BE-NEXT:    mov.l .Ltmp2,r1
; BE-NEXT:    fmov.s fr4,@r1
; BE-NEXT:    add #4,r1
; BE-NEXT:    rts
; BE-NEXT:    fmov.s fr8,@r1
; BE-NEXT:    .p2align 2
; BE-NEXT:  ! %bb.1:
; BE-NEXT:  .Ltmp1:
; BE-NEXT:    .ualong gd
; BE-NEXT:  .Ltmp2:
; BE-NEXT:    .ualong gf
;
; SH3E-LABEL: mixed:
; SH3E:         .cfi_startproc
; SH3E-NEXT:  ! %bb.0:
; SH3E-NEXT:    mov.l .Ltmp1,r1
; SH3E-NEXT:    mov.l r5,@(4,r1)
; SH3E-NEXT:    mov.l r4,@r1
; SH3E-NEXT:    mov.l .Ltmp2,r1
; SH3E-NEXT:    fmov.s fr4,@r1
; SH3E-NEXT:    add #4,r1
; SH3E-NEXT:    rts
; SH3E-NEXT:    fmov.s fr5,@r1
; SH3E-NEXT:    .p2align 2
; SH3E-NEXT:  ! %bb.1:
; SH3E-NEXT:  .Ltmp1:
; SH3E-NEXT:    .ualong gd
; SH3E-NEXT:  .Ltmp2:
; SH3E-NEXT:    .ualong gf
  store float %a, ptr @gf
  store double %b, ptr @gd
  store float %c, ptr getelementptr ([4 x float], ptr @gf, i32 0, i32 1)
  ret void
}

; Floating point and integer registers are counted apart.
define void @both(i32 %a, float %b, i32 %c, double %d, i32 %e) {
; LE-LABEL: both:
; LE:         .cfi_startproc
; LE-NEXT:  ! %bb.0:
; LE-NEXT:    mov.l .Ltmp3,r1
; LE-NEXT:    fmov.s fr5,@r1
; LE-NEXT:    mov.l .Ltmp4,r1
; LE-NEXT:    mov.l r4,@r1
; LE-NEXT:    mov.l r5,@(4,r1)
; LE-NEXT:    mov.l .Ltmp5,r2
; LE-NEXT:    add #8,r2
; LE-NEXT:    fmov.s fr6,@-r2
; LE-NEXT:    fmov.s fr7,@-r2
; LE-NEXT:    rts
; LE-NEXT:    mov.l r6,@(8,r1)
; LE-NEXT:    .p2align 2
; LE-NEXT:  ! %bb.1:
; LE-NEXT:  .Ltmp3:
; LE-NEXT:    .ualong gf
; LE-NEXT:  .Ltmp4:
; LE-NEXT:    .ualong gi
; LE-NEXT:  .Ltmp5:
; LE-NEXT:    .ualong gd
;
; BE-LABEL: both:
; BE:         .cfi_startproc
; BE-NEXT:  ! %bb.0:
; BE-NEXT:    mov.l .Ltmp3,r1
; BE-NEXT:    fmov.s fr4,@r1
; BE-NEXT:    mov.l .Ltmp4,r1
; BE-NEXT:    mov.l r4,@r1
; BE-NEXT:    mov.l r5,@(4,r1)
; BE-NEXT:    mov.l .Ltmp5,r2
; BE-NEXT:    add #8,r2
; BE-NEXT:    fmov.s fr7,@-r2
; BE-NEXT:    fmov.s fr6,@-r2
; BE-NEXT:    rts
; BE-NEXT:    mov.l r6,@(8,r1)
; BE-NEXT:    .p2align 2
; BE-NEXT:  ! %bb.1:
; BE-NEXT:  .Ltmp3:
; BE-NEXT:    .ualong gf
; BE-NEXT:  .Ltmp4:
; BE-NEXT:    .ualong gi
; BE-NEXT:  .Ltmp5:
; BE-NEXT:    .ualong gd
;
; SH3E-LABEL: both:
; SH3E:         .cfi_startproc
; SH3E-NEXT:  ! %bb.0:
; SH3E-NEXT:    mov.l .Ltmp3,r1
; SH3E-NEXT:    mov.l r7,@(4,r1)
; SH3E-NEXT:    mov.l r6,@r1
; SH3E-NEXT:    mov.l .Ltmp4,r1
; SH3E-NEXT:    fmov.s fr4,@r1
; SH3E-NEXT:    mov.l .Ltmp5,r1
; SH3E-NEXT:    mov.l r4,@r1
; SH3E-NEXT:    mov.l r5,@(4,r1)
; SH3E-NEXT:    mov.l @r15,r2
; SH3E-NEXT:    rts
; SH3E-NEXT:    mov.l r2,@(8,r1)
; SH3E-NEXT:    .p2align 2
; SH3E-NEXT:  ! %bb.1:
; SH3E-NEXT:  .Ltmp3:
; SH3E-NEXT:    .ualong gd
; SH3E-NEXT:  .Ltmp4:
; SH3E-NEXT:    .ualong gf
; SH3E-NEXT:  .Ltmp5:
; SH3E-NEXT:    .ualong gi
  store i32 %a, ptr @gi
  store float %b, ptr @gf
  store i32 %c, ptr getelementptr ([4 x i32], ptr @gi, i32 0, i32 1)
  store double %d, ptr @gd
  store i32 %e, ptr getelementptr ([4 x i32], ptr @gi, i32 0, i32 2)
  ret void
}

; An argument is in registers only if all of it fits: d is on the stack,
; and e still gets r7 on an SH-4.
define void @fits(i32 %a, i32 %b, i32 %c, i64 %d, i32 %e) {
; LE-LABEL: fits:
; LE:         .cfi_startproc
; LE-NEXT:  ! %bb.0:
; LE-NEXT:    mov.l .Ltmp6,r1
; LE-NEXT:    mov.l r7,@(4,r1)
; LE-NEXT:    mov.l @r15,r2
; LE-NEXT:    rts
; LE-NEXT:    mov.l r2,@r1
; LE-NEXT:    .p2align 2
; LE-NEXT:  ! %bb.1:
; LE-NEXT:  .Ltmp6:
; LE-NEXT:    .ualong gi
;
; BE-LABEL: fits:
; BE:         .cfi_startproc
; BE-NEXT:  ! %bb.0:
; BE-NEXT:    mov.l .Ltmp6,r1
; BE-NEXT:    mov.l r7,@(4,r1)
; BE-NEXT:    mov.l @(4,r15),r2
; BE-NEXT:    rts
; BE-NEXT:    mov.l r2,@r1
; BE-NEXT:    .p2align 2
; BE-NEXT:  ! %bb.1:
; BE-NEXT:  .Ltmp6:
; BE-NEXT:    .ualong gi
;
; SH3E-LABEL: fits:
; SH3E:         .cfi_startproc
; SH3E-NEXT:  ! %bb.0:
; SH3E-NEXT:    mov.l .Ltmp6,r1
; SH3E-NEXT:    mov.l @(8,r15),r2
; SH3E-NEXT:    mov.l r2,@(4,r1)
; SH3E-NEXT:    mov.l @r15,r2
; SH3E-NEXT:    rts
; SH3E-NEXT:    mov.l r2,@r1
; SH3E-NEXT:    .p2align 2
; SH3E-NEXT:  ! %bb.1:
; SH3E-NEXT:  .Ltmp6:
; SH3E-NEXT:    .ualong gi
  %lo = trunc i64 %d to i32
  store i32 %lo, ptr @gi
  store i32 %e, ptr getelementptr ([4 x i32], ptr @gi, i32 0, i32 1)
  ret void
}

; A complex float that starts at an even place has its real part in the
; register with the lower number.
define void @complex([2 x float] %z) {
; LE-LABEL: complex:
; LE:         .cfi_startproc
; LE-NEXT:  ! %bb.0:
; LE-NEXT:    mov.l .Ltmp7,r1
; LE-NEXT:    fmov.s fr4,@r1
; LE-NEXT:    add #4,r1
; LE-NEXT:    rts
; LE-NEXT:    fmov.s fr5,@r1
; LE-NEXT:    .p2align 2
; LE-NEXT:  ! %bb.1:
; LE-NEXT:  .Ltmp7:
; LE-NEXT:    .ualong gf
;
; BE-LABEL: complex:
; BE:         .cfi_startproc
; BE-NEXT:  ! %bb.0:
; BE-NEXT:    mov.l .Ltmp7,r1
; BE-NEXT:    fmov.s fr4,@r1
; BE-NEXT:    add #4,r1
; BE-NEXT:    rts
; BE-NEXT:    fmov.s fr5,@r1
; BE-NEXT:    .p2align 2
; BE-NEXT:  ! %bb.1:
; BE-NEXT:  .Ltmp7:
; BE-NEXT:    .ualong gf
;
; SH3E-LABEL: complex:
; SH3E:         .cfi_startproc
; SH3E-NEXT:  ! %bb.0:
; SH3E-NEXT:    mov.l .Ltmp7,r1
; SH3E-NEXT:    fmov.s fr4,@r1
; SH3E-NEXT:    add #4,r1
; SH3E-NEXT:    rts
; SH3E-NEXT:    fmov.s fr5,@r1
; SH3E-NEXT:    .p2align 2
; SH3E-NEXT:  ! %bb.1:
; SH3E-NEXT:  .Ltmp7:
; SH3E-NEXT:    .ualong gf
  %re = extractvalue [2 x float] %z, 0
  %im = extractvalue [2 x float] %z, 1
  store float %re, ptr @gf
  store float %im, ptr getelementptr ([4 x float], ptr @gf, i32 0, i32 1)
  ret void
}

define void @complex_odd(float %x, [2 x float] %z) {
; LE-LABEL: complex_odd:
; LE:         .cfi_startproc
; LE-NEXT:  ! %bb.0:
; LE-NEXT:    mov.l .Ltmp8,r1
; LE-NEXT:    fmov.s fr4,@r1
; LE-NEXT:    add #4,r1
; LE-NEXT:    rts
; LE-NEXT:    fmov.s fr7,@r1
; LE-NEXT:    .p2align 2
; LE-NEXT:  ! %bb.1:
; LE-NEXT:  .Ltmp8:
; LE-NEXT:    .ualong gf
;
; BE-LABEL: complex_odd:
; BE:         .cfi_startproc
; BE-NEXT:  ! %bb.0:
; BE-NEXT:    mov.l .Ltmp8,r1
; BE-NEXT:    fmov.s fr5,@r1
; BE-NEXT:    add #4,r1
; BE-NEXT:    rts
; BE-NEXT:    fmov.s fr6,@r1
; BE-NEXT:    .p2align 2
; BE-NEXT:  ! %bb.1:
; BE-NEXT:  .Ltmp8:
; BE-NEXT:    .ualong gf
;
; SH3E-LABEL: complex_odd:
; SH3E:         .cfi_startproc
; SH3E-NEXT:  ! %bb.0:
; SH3E-NEXT:    mov.l .Ltmp8,r1
; SH3E-NEXT:    fmov.s fr5,@r1
; SH3E-NEXT:    add #4,r1
; SH3E-NEXT:    rts
; SH3E-NEXT:    fmov.s fr6,@r1
; SH3E-NEXT:    .p2align 2
; SH3E-NEXT:  ! %bb.1:
; SH3E-NEXT:  .Ltmp8:
; SH3E-NEXT:    .ualong gf
  %re = extractvalue [2 x float] %z, 0
  %im = extractvalue [2 x float] %z, 1
  store float %re, ptr @gf
  store float %im, ptr getelementptr ([4 x float], ptr @gf, i32 0, i32 1)
  ret void
}

define float @ret_float() {
; LE-LABEL: ret_float:
; LE:         .cfi_startproc
; LE-NEXT:  ! %bb.0:
; LE-NEXT:    mov.l .Ltmp9,r1
; LE-NEXT:    rts
; LE-NEXT:    fmov.s @r1,fr0
; LE-NEXT:    .p2align 2
; LE-NEXT:  ! %bb.1:
; LE-NEXT:  .Ltmp9:
; LE-NEXT:    .ualong gf
;
; BE-LABEL: ret_float:
; BE:         .cfi_startproc
; BE-NEXT:  ! %bb.0:
; BE-NEXT:    mov.l .Ltmp9,r1
; BE-NEXT:    rts
; BE-NEXT:    fmov.s @r1,fr0
; BE-NEXT:    .p2align 2
; BE-NEXT:  ! %bb.1:
; BE-NEXT:  .Ltmp9:
; BE-NEXT:    .ualong gf
;
; SH3E-LABEL: ret_float:
; SH3E:         .cfi_startproc
; SH3E-NEXT:  ! %bb.0:
; SH3E-NEXT:    mov.l .Ltmp9,r1
; SH3E-NEXT:    rts
; SH3E-NEXT:    fmov.s @r1,fr0
; SH3E-NEXT:    .p2align 2
; SH3E-NEXT:  ! %bb.1:
; SH3E-NEXT:  .Ltmp9:
; SH3E-NEXT:    .ualong gf
  %r = load float, ptr @gf
  ret float %r
}

define double @ret_double() {
; LE-LABEL: ret_double:
; LE:         .cfi_startproc
; LE-NEXT:  ! %bb.0:
; LE-NEXT:    mov.l .Ltmp10,r1
; LE-NEXT:    fmov.s @r1+,fr1
; LE-NEXT:    fmov.s @r1,fr0
; LE-NEXT:    rts
; LE-NEXT:    add #-4,r1
; LE-NEXT:    .p2align 2
; LE-NEXT:  ! %bb.1:
; LE-NEXT:  .Ltmp10:
; LE-NEXT:    .ualong gd
;
; BE-LABEL: ret_double:
; BE:         .cfi_startproc
; BE-NEXT:  ! %bb.0:
; BE-NEXT:    mov.l .Ltmp10,r1
; BE-NEXT:    fmov.s @r1+,fr0
; BE-NEXT:    fmov.s @r1,fr1
; BE-NEXT:    rts
; BE-NEXT:    add #-4,r1
; BE-NEXT:    .p2align 2
; BE-NEXT:  ! %bb.1:
; BE-NEXT:  .Ltmp10:
; BE-NEXT:    .ualong gd
;
; SH3E-LABEL: ret_double:
; SH3E:         .cfi_startproc
; SH3E-NEXT:  ! %bb.0:
; SH3E-NEXT:    mov.l .Ltmp10,r1
; SH3E-NEXT:    mov.l @r1,r0
; SH3E-NEXT:    rts
; SH3E-NEXT:    mov.l @(4,r1),r1
; SH3E-NEXT:    .p2align 2
; SH3E-NEXT:  ! %bb.1:
; SH3E-NEXT:  .Ltmp10:
; SH3E-NEXT:    .ualong gd
  %r = load double, ptr @gd
  ret double %r
}

declare void @llvm.va_start(ptr)

; A function with variable arguments stores the registers that hold none of
; its named parameters in a buffer, the floating point ones first, and
; va_list is five pointers into it and to the stack.
define void @variadic(ptr %list, i32 %n, double %d, ...) {
; LE-LABEL: variadic:
; LE:         .cfi_startproc
; LE-NEXT:  ! %bb.0:
; LE-NEXT:    mov.l r14,@-r15
; LE-NEXT:    .cfi_def_cfa_offset 4
; LE-NEXT:    .cfi_offset r14, -4
; LE-NEXT:    mov r15,r14
; LE-NEXT:    .cfi_def_cfa_register r14
; LE-NEXT:    add #-36,r15
; LE-NEXT:    mov #-8,r1
; LE-NEXT:    and r1,r15
; LE-NEXT:    fmov.s fr7,@r15
; LE-NEXT:    mov r15,r1
; LE-NEXT:    add #4,r1
; LE-NEXT:    fmov.s fr6,@r1
; LE-NEXT:    mov r15,r1
; LE-NEXT:    add #8,r1
; LE-NEXT:    fmov.s fr9,@r1
; LE-NEXT:    mov r15,r1
; LE-NEXT:    add #12,r1
; LE-NEXT:    fmov.s fr8,@r1
; LE-NEXT:    mov r15,r1
; LE-NEXT:    add #16,r1
; LE-NEXT:    fmov.s fr11,@r1
; LE-NEXT:    mov r15,r1
; LE-NEXT:    add #20,r1
; LE-NEXT:    fmov.s fr10,@r1
; LE-NEXT:    mov.l r6,@(24,r15)
; LE-NEXT:    mov.l r7,@(28,r15)
; LE-NEXT:    mov r15,r1
; LE-NEXT:    add #24,r1
; LE-NEXT:    mov.l r1,@r4
; LE-NEXT:    mov r15,r2
; LE-NEXT:    add #32,r2
; LE-NEXT:    mov.l r2,@(4,r4)
; LE-NEXT:    mov r15,r2
; LE-NEXT:    mov.l r2,@(8,r4)
; LE-NEXT:    mov.l r1,@(12,r4)
; LE-NEXT:    mov r14,r1
; LE-NEXT:    add #4,r1
; LE-NEXT:    mov.l r1,@(16,r4)
; LE-NEXT:    mov r14,r15
; LE-NEXT:    rts
; LE-NEXT:    mov.l @r15+,r14
;
; BE-LABEL: variadic:
; BE:         .cfi_startproc
; BE-NEXT:  ! %bb.0:
; BE-NEXT:    mov.l r14,@-r15
; BE-NEXT:    .cfi_def_cfa_offset 4
; BE-NEXT:    .cfi_offset r14, -4
; BE-NEXT:    mov r15,r14
; BE-NEXT:    .cfi_def_cfa_register r14
; BE-NEXT:    add #-36,r15
; BE-NEXT:    mov #-8,r1
; BE-NEXT:    and r1,r15
; BE-NEXT:    fmov.s fr6,@r15
; BE-NEXT:    mov r15,r1
; BE-NEXT:    add #4,r1
; BE-NEXT:    fmov.s fr7,@r1
; BE-NEXT:    mov r15,r1
; BE-NEXT:    add #8,r1
; BE-NEXT:    fmov.s fr8,@r1
; BE-NEXT:    mov r15,r1
; BE-NEXT:    add #12,r1
; BE-NEXT:    fmov.s fr9,@r1
; BE-NEXT:    mov r15,r1
; BE-NEXT:    add #16,r1
; BE-NEXT:    fmov.s fr10,@r1
; BE-NEXT:    mov r15,r1
; BE-NEXT:    add #20,r1
; BE-NEXT:    fmov.s fr11,@r1
; BE-NEXT:    mov.l r6,@(24,r15)
; BE-NEXT:    mov.l r7,@(28,r15)
; BE-NEXT:    mov r15,r1
; BE-NEXT:    add #24,r1
; BE-NEXT:    mov.l r1,@r4
; BE-NEXT:    mov r15,r2
; BE-NEXT:    add #32,r2
; BE-NEXT:    mov.l r2,@(4,r4)
; BE-NEXT:    mov r15,r2
; BE-NEXT:    mov.l r2,@(8,r4)
; BE-NEXT:    mov.l r1,@(12,r4)
; BE-NEXT:    mov r14,r1
; BE-NEXT:    add #4,r1
; BE-NEXT:    mov.l r1,@(16,r4)
; BE-NEXT:    mov r14,r15
; BE-NEXT:    rts
; BE-NEXT:    mov.l @r15+,r14
;
; SH3E-LABEL: variadic:
; SH3E:         .cfi_startproc
; SH3E-NEXT:  ! %bb.0:
; SH3E-NEXT:    add #-32,r15
; SH3E-NEXT:    .cfi_def_cfa_offset 32
; SH3E-NEXT:    fmov.s fr4,@r15
; SH3E-NEXT:    mov r15,r1
; SH3E-NEXT:    add #4,r1
; SH3E-NEXT:    fmov.s fr5,@r1
; SH3E-NEXT:    mov r15,r1
; SH3E-NEXT:    add #8,r1
; SH3E-NEXT:    fmov.s fr6,@r1
; SH3E-NEXT:    mov r15,r1
; SH3E-NEXT:    add #12,r1
; SH3E-NEXT:    fmov.s fr7,@r1
; SH3E-NEXT:    mov r15,r1
; SH3E-NEXT:    add #16,r1
; SH3E-NEXT:    fmov.s fr8,@r1
; SH3E-NEXT:    mov r15,r1
; SH3E-NEXT:    add #20,r1
; SH3E-NEXT:    fmov.s fr9,@r1
; SH3E-NEXT:    mov r15,r1
; SH3E-NEXT:    add #24,r1
; SH3E-NEXT:    fmov.s fr10,@r1
; SH3E-NEXT:    mov r15,r1
; SH3E-NEXT:    add #28,r1
; SH3E-NEXT:    fmov.s fr11,@r1
; SH3E-NEXT:    mov r15,r1
; SH3E-NEXT:    add #32,r1
; SH3E-NEXT:    mov.l r1,@r4
; SH3E-NEXT:    mov.l r1,@(4,r4)
; SH3E-NEXT:    mov r15,r2
; SH3E-NEXT:    mov.l r2,@(8,r4)
; SH3E-NEXT:    mov.l r1,@(12,r4)
; SH3E-NEXT:    mov r15,r1
; SH3E-NEXT:    add #32,r1
; SH3E-NEXT:    mov.l r1,@(16,r4)
; SH3E-NEXT:    rts
; SH3E-NEXT:    add #32,r15
  call void @llvm.va_start(ptr %list)
  ret void
}

define void @copy(ptr %to, ptr %from) {
; LE-LABEL: copy:
; LE:         .cfi_startproc
; LE-NEXT:  ! %bb.0:
; LE-NEXT:    mov.l @(16,r5),r1
; LE-NEXT:    mov.l r1,@(16,r4)
; LE-NEXT:    mov.l @(12,r5),r1
; LE-NEXT:    mov.l r1,@(12,r4)
; LE-NEXT:    mov.l @(8,r5),r1
; LE-NEXT:    mov.l r1,@(8,r4)
; LE-NEXT:    mov.l @(4,r5),r1
; LE-NEXT:    mov.l r1,@(4,r4)
; LE-NEXT:    mov.l @r5,r1
; LE-NEXT:    rts
; LE-NEXT:    mov.l r1,@r4
;
; BE-LABEL: copy:
; BE:         .cfi_startproc
; BE-NEXT:  ! %bb.0:
; BE-NEXT:    mov.l @(16,r5),r1
; BE-NEXT:    mov.l r1,@(16,r4)
; BE-NEXT:    mov.l @(12,r5),r1
; BE-NEXT:    mov.l r1,@(12,r4)
; BE-NEXT:    mov.l @(8,r5),r1
; BE-NEXT:    mov.l r1,@(8,r4)
; BE-NEXT:    mov.l @(4,r5),r1
; BE-NEXT:    mov.l r1,@(4,r4)
; BE-NEXT:    mov.l @r5,r1
; BE-NEXT:    rts
; BE-NEXT:    mov.l r1,@r4
;
; SH3E-LABEL: copy:
; SH3E:         .cfi_startproc
; SH3E-NEXT:  ! %bb.0:
; SH3E-NEXT:    mov.l @(16,r5),r1
; SH3E-NEXT:    mov.l r1,@(16,r4)
; SH3E-NEXT:    mov.l @(12,r5),r1
; SH3E-NEXT:    mov.l r1,@(12,r4)
; SH3E-NEXT:    mov.l @(8,r5),r1
; SH3E-NEXT:    mov.l r1,@(8,r4)
; SH3E-NEXT:    mov.l @(4,r5),r1
; SH3E-NEXT:    mov.l r1,@(4,r4)
; SH3E-NEXT:    mov.l @r5,r1
; SH3E-NEXT:    rts
; SH3E-NEXT:    mov.l r1,@r4
  call void @llvm.va_copy(ptr %to, ptr %from)
  ret void
}

declare void @llvm.va_copy(ptr, ptr)
