; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=sh4-unknown-linux-gnu -verify-machineinstrs < %s | FileCheck --check-prefix=SH4 %s
; RUN: llc -mtriple=sh4a-unknown-linux-gnu -verify-machineinstrs < %s | FileCheck --check-prefix=SH4A %s
; RUN: llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4-single -verify-machineinstrs < %s | FileCheck --check-prefix=SINGLE %s

; One instruction computes with float or with double: the PR bit of FPSCR
; says which.  A function is entered with the bit set (double), or clear
; with sh4-single, and leaves it that way.

define double @dadd(double %a, double %b) {
; SH4-LABEL: dadd:
; SH4:         .cfi_startproc
; SH4-NEXT:  ! %bb.0:
; SH4-NEXT:    fmov fr4,fr0
; SH4-NEXT:    fmov fr5,fr1
; SH4-NEXT:    fadd dr6,dr0
; SH4-NEXT:    rts
; SH4-NEXT:    nop
;
; SH4A-LABEL: dadd:
; SH4A:         .cfi_startproc
; SH4A-NEXT:  ! %bb.0:
; SH4A-NEXT:    fmov fr4,fr0
; SH4A-NEXT:    fmov fr5,fr1
; SH4A-NEXT:    fadd dr6,dr0
; SH4A-NEXT:    rts
; SH4A-NEXT:    nop
;
; SINGLE-LABEL: dadd:
; SINGLE:         .cfi_startproc
; SINGLE-NEXT:  ! %bb.0:
; SINGLE-NEXT:    fmov fr4,fr0
; SINGLE-NEXT:    fmov fr5,fr1
; SINGLE-NEXT:    mov #8,r1
; SINGLE-NEXT:    shll16 r1
; SINGLE-NEXT:    sts fpscr,r2
; SINGLE-NEXT:    xor r1,r2
; SINGLE-NEXT:    lds r2,fpscr
; SINGLE-NEXT:    fadd dr6,dr0
; SINGLE-NEXT:    mov #8,r1
; SINGLE-NEXT:    shll16 r1
; SINGLE-NEXT:    sts fpscr,r2
; SINGLE-NEXT:    xor r1,r2
; SINGLE-NEXT:    lds r2,fpscr
; SINGLE-NEXT:    rts
; SINGLE-NEXT:    nop
  %r = fadd double %a, %b
  ret double %r
}

define float @fadd(float %a, float %b) {
; SH4-LABEL: fadd:
; SH4:         .cfi_startproc
; SH4-NEXT:  ! %bb.0:
; SH4-NEXT:    fmov fr5,fr0
; SH4-NEXT:    mov #8,r1
; SH4-NEXT:    shll16 r1
; SH4-NEXT:    sts fpscr,r2
; SH4-NEXT:    xor r1,r2
; SH4-NEXT:    lds r2,fpscr
; SH4-NEXT:    fadd fr4,fr0
; SH4-NEXT:    mov #8,r1
; SH4-NEXT:    shll16 r1
; SH4-NEXT:    sts fpscr,r2
; SH4-NEXT:    xor r1,r2
; SH4-NEXT:    lds r2,fpscr
; SH4-NEXT:    rts
; SH4-NEXT:    nop
;
; SH4A-LABEL: fadd:
; SH4A:         .cfi_startproc
; SH4A-NEXT:  ! %bb.0:
; SH4A-NEXT:    fmov fr5,fr0
; SH4A-NEXT:    fpchg
; SH4A-NEXT:    fadd fr4,fr0
; SH4A-NEXT:    fpchg
; SH4A-NEXT:    rts
; SH4A-NEXT:    nop
;
; SINGLE-LABEL: fadd:
; SINGLE:         .cfi_startproc
; SINGLE-NEXT:  ! %bb.0:
; SINGLE-NEXT:    fmov fr5,fr0
; SINGLE-NEXT:    fadd fr4,fr0
; SINGLE-NEXT:    rts
; SINGLE-NEXT:    nop
  %r = fadd float %a, %b
  ret float %r
}

; Two operations in the other precision share one change of the bit.
define float @fmul_add(float %a, float %b, float %c) {
; SH4-LABEL: fmul_add:
; SH4:         .cfi_startproc
; SH4-NEXT:  ! %bb.0:
; SH4-NEXT:    fmov fr5,fr0
; SH4-NEXT:    mov #8,r1
; SH4-NEXT:    shll16 r1
; SH4-NEXT:    sts fpscr,r2
; SH4-NEXT:    xor r1,r2
; SH4-NEXT:    lds r2,fpscr
; SH4-NEXT:    fmul fr4,fr0
; SH4-NEXT:    fadd fr7,fr0
; SH4-NEXT:    mov #8,r1
; SH4-NEXT:    shll16 r1
; SH4-NEXT:    sts fpscr,r2
; SH4-NEXT:    xor r1,r2
; SH4-NEXT:    lds r2,fpscr
; SH4-NEXT:    rts
; SH4-NEXT:    nop
;
; SH4A-LABEL: fmul_add:
; SH4A:         .cfi_startproc
; SH4A-NEXT:  ! %bb.0:
; SH4A-NEXT:    fmov fr5,fr0
; SH4A-NEXT:    fpchg
; SH4A-NEXT:    fmul fr4,fr0
; SH4A-NEXT:    fadd fr7,fr0
; SH4A-NEXT:    fpchg
; SH4A-NEXT:    rts
; SH4A-NEXT:    nop
;
; SINGLE-LABEL: fmul_add:
; SINGLE:         .cfi_startproc
; SINGLE-NEXT:  ! %bb.0:
; SINGLE-NEXT:    fmov fr5,fr0
; SINGLE-NEXT:    fmul fr4,fr0
; SINGLE-NEXT:    fadd fr7,fr0
; SINGLE-NEXT:    rts
; SINGLE-NEXT:    nop
  %m = fmul float %a, %b
  %r = fadd float %m, %c
  ret float %r
}

define double @dsub(double %a, double %b) {
; SH4-LABEL: dsub:
; SH4:         .cfi_startproc
; SH4-NEXT:  ! %bb.0:
; SH4-NEXT:    fmov fr4,fr0
; SH4-NEXT:    fmov fr5,fr1
; SH4-NEXT:    fsub dr6,dr0
; SH4-NEXT:    rts
; SH4-NEXT:    nop
;
; SH4A-LABEL: dsub:
; SH4A:         .cfi_startproc
; SH4A-NEXT:  ! %bb.0:
; SH4A-NEXT:    fmov fr4,fr0
; SH4A-NEXT:    fmov fr5,fr1
; SH4A-NEXT:    fsub dr6,dr0
; SH4A-NEXT:    rts
; SH4A-NEXT:    nop
;
; SINGLE-LABEL: dsub:
; SINGLE:         .cfi_startproc
; SINGLE-NEXT:  ! %bb.0:
; SINGLE-NEXT:    fmov fr4,fr0
; SINGLE-NEXT:    fmov fr5,fr1
; SINGLE-NEXT:    mov #8,r1
; SINGLE-NEXT:    shll16 r1
; SINGLE-NEXT:    sts fpscr,r2
; SINGLE-NEXT:    xor r1,r2
; SINGLE-NEXT:    lds r2,fpscr
; SINGLE-NEXT:    fsub dr6,dr0
; SINGLE-NEXT:    mov #8,r1
; SINGLE-NEXT:    shll16 r1
; SINGLE-NEXT:    sts fpscr,r2
; SINGLE-NEXT:    xor r1,r2
; SINGLE-NEXT:    lds r2,fpscr
; SINGLE-NEXT:    rts
; SINGLE-NEXT:    nop
  %r = fsub double %a, %b
  ret double %r
}

define double @ddiv(double %a, double %b) {
; SH4-LABEL: ddiv:
; SH4:         .cfi_startproc
; SH4-NEXT:  ! %bb.0:
; SH4-NEXT:    fmov fr4,fr0
; SH4-NEXT:    fmov fr5,fr1
; SH4-NEXT:    fdiv dr6,dr0
; SH4-NEXT:    rts
; SH4-NEXT:    nop
;
; SH4A-LABEL: ddiv:
; SH4A:         .cfi_startproc
; SH4A-NEXT:  ! %bb.0:
; SH4A-NEXT:    fmov fr4,fr0
; SH4A-NEXT:    fmov fr5,fr1
; SH4A-NEXT:    fdiv dr6,dr0
; SH4A-NEXT:    rts
; SH4A-NEXT:    nop
;
; SINGLE-LABEL: ddiv:
; SINGLE:         .cfi_startproc
; SINGLE-NEXT:  ! %bb.0:
; SINGLE-NEXT:    fmov fr4,fr0
; SINGLE-NEXT:    fmov fr5,fr1
; SINGLE-NEXT:    mov #8,r1
; SINGLE-NEXT:    shll16 r1
; SINGLE-NEXT:    sts fpscr,r2
; SINGLE-NEXT:    xor r1,r2
; SINGLE-NEXT:    lds r2,fpscr
; SINGLE-NEXT:    fdiv dr6,dr0
; SINGLE-NEXT:    mov #8,r1
; SINGLE-NEXT:    shll16 r1
; SINGLE-NEXT:    sts fpscr,r2
; SINGLE-NEXT:    xor r1,r2
; SINGLE-NEXT:    lds r2,fpscr
; SINGLE-NEXT:    rts
; SINGLE-NEXT:    nop
  %r = fdiv double %a, %b
  ret double %r
}

; The sign is one bit of the first register in either precision.
define double @dneg(double %a) {
; SH4-LABEL: dneg:
; SH4:         .cfi_startproc
; SH4-NEXT:  ! %bb.0:
; SH4-NEXT:    fmov fr4,fr0
; SH4-NEXT:    fmov fr5,fr1
; SH4-NEXT:    fneg dr0
; SH4-NEXT:    rts
; SH4-NEXT:    nop
;
; SH4A-LABEL: dneg:
; SH4A:         .cfi_startproc
; SH4A-NEXT:  ! %bb.0:
; SH4A-NEXT:    fmov fr4,fr0
; SH4A-NEXT:    fmov fr5,fr1
; SH4A-NEXT:    fneg dr0
; SH4A-NEXT:    rts
; SH4A-NEXT:    nop
;
; SINGLE-LABEL: dneg:
; SINGLE:         .cfi_startproc
; SINGLE-NEXT:  ! %bb.0:
; SINGLE-NEXT:    fmov fr4,fr0
; SINGLE-NEXT:    fmov fr5,fr1
; SINGLE-NEXT:    fneg dr0
; SINGLE-NEXT:    rts
; SINGLE-NEXT:    nop
  %r = fneg double %a
  ret double %r
}

define float @fabs(float %a) {
; SH4-LABEL: fabs:
; SH4:         .cfi_startproc
; SH4-NEXT:  ! %bb.0:
; SH4-NEXT:    fmov fr5,fr0
; SH4-NEXT:    fabs fr0
; SH4-NEXT:    rts
; SH4-NEXT:    nop
;
; SH4A-LABEL: fabs:
; SH4A:         .cfi_startproc
; SH4A-NEXT:  ! %bb.0:
; SH4A-NEXT:    fmov fr5,fr0
; SH4A-NEXT:    fabs fr0
; SH4A-NEXT:    rts
; SH4A-NEXT:    nop
;
; SINGLE-LABEL: fabs:
; SINGLE:         .cfi_startproc
; SINGLE-NEXT:  ! %bb.0:
; SINGLE-NEXT:    fmov fr5,fr0
; SINGLE-NEXT:    fabs fr0
; SINGLE-NEXT:    rts
; SINGLE-NEXT:    nop
  %r = call float @llvm.fabs.f32(float %a)
  ret float %r
}

define double @dsqrt(double %a) {
; SH4-LABEL: dsqrt:
; SH4:         .cfi_startproc
; SH4-NEXT:  ! %bb.0:
; SH4-NEXT:    fmov fr4,fr0
; SH4-NEXT:    fmov fr5,fr1
; SH4-NEXT:    fsqrt dr0
; SH4-NEXT:    rts
; SH4-NEXT:    nop
;
; SH4A-LABEL: dsqrt:
; SH4A:         .cfi_startproc
; SH4A-NEXT:  ! %bb.0:
; SH4A-NEXT:    fmov fr4,fr0
; SH4A-NEXT:    fmov fr5,fr1
; SH4A-NEXT:    fsqrt dr0
; SH4A-NEXT:    rts
; SH4A-NEXT:    nop
;
; SINGLE-LABEL: dsqrt:
; SINGLE:         .cfi_startproc
; SINGLE-NEXT:  ! %bb.0:
; SINGLE-NEXT:    fmov fr4,fr0
; SINGLE-NEXT:    fmov fr5,fr1
; SINGLE-NEXT:    mov #8,r1
; SINGLE-NEXT:    shll16 r1
; SINGLE-NEXT:    sts fpscr,r2
; SINGLE-NEXT:    xor r1,r2
; SINGLE-NEXT:    lds r2,fpscr
; SINGLE-NEXT:    fsqrt dr0
; SINGLE-NEXT:    mov #8,r1
; SINGLE-NEXT:    shll16 r1
; SINGLE-NEXT:    sts fpscr,r2
; SINGLE-NEXT:    xor r1,r2
; SINGLE-NEXT:    lds r2,fpscr
; SINGLE-NEXT:    rts
; SINGLE-NEXT:    nop
  %r = call double @llvm.sqrt.f64(double %a)
  ret double %r
}

; Conversions go through FPUL.
define double @extend(float %a) {
; SH4-LABEL: extend:
; SH4:         .cfi_startproc
; SH4-NEXT:  ! %bb.0:
; SH4-NEXT:    flds fr5,fpul
; SH4-NEXT:    fcnvsd fpul,dr0
; SH4-NEXT:    rts
; SH4-NEXT:    nop
;
; SH4A-LABEL: extend:
; SH4A:         .cfi_startproc
; SH4A-NEXT:  ! %bb.0:
; SH4A-NEXT:    flds fr5,fpul
; SH4A-NEXT:    fcnvsd fpul,dr0
; SH4A-NEXT:    rts
; SH4A-NEXT:    nop
;
; SINGLE-LABEL: extend:
; SINGLE:         .cfi_startproc
; SINGLE-NEXT:  ! %bb.0:
; SINGLE-NEXT:    mov #8,r1
; SINGLE-NEXT:    shll16 r1
; SINGLE-NEXT:    sts fpscr,r2
; SINGLE-NEXT:    xor r1,r2
; SINGLE-NEXT:    lds r2,fpscr
; SINGLE-NEXT:    flds fr5,fpul
; SINGLE-NEXT:    fcnvsd fpul,dr0
; SINGLE-NEXT:    mov #8,r1
; SINGLE-NEXT:    shll16 r1
; SINGLE-NEXT:    sts fpscr,r2
; SINGLE-NEXT:    xor r1,r2
; SINGLE-NEXT:    lds r2,fpscr
; SINGLE-NEXT:    rts
; SINGLE-NEXT:    nop
  %r = fpext float %a to double
  ret double %r
}

define float @round(double %a) {
; SH4-LABEL: round:
; SH4:         .cfi_startproc
; SH4-NEXT:  ! %bb.0:
; SH4-NEXT:    fcnvds dr4,fpul
; SH4-NEXT:    fsts fpul,fr0
; SH4-NEXT:    rts
; SH4-NEXT:    nop
;
; SH4A-LABEL: round:
; SH4A:         .cfi_startproc
; SH4A-NEXT:  ! %bb.0:
; SH4A-NEXT:    fcnvds dr4,fpul
; SH4A-NEXT:    fsts fpul,fr0
; SH4A-NEXT:    rts
; SH4A-NEXT:    nop
;
; SINGLE-LABEL: round:
; SINGLE:         .cfi_startproc
; SINGLE-NEXT:  ! %bb.0:
; SINGLE-NEXT:    mov #8,r1
; SINGLE-NEXT:    shll16 r1
; SINGLE-NEXT:    sts fpscr,r2
; SINGLE-NEXT:    xor r1,r2
; SINGLE-NEXT:    lds r2,fpscr
; SINGLE-NEXT:    fcnvds dr4,fpul
; SINGLE-NEXT:    fsts fpul,fr0
; SINGLE-NEXT:    mov #8,r1
; SINGLE-NEXT:    shll16 r1
; SINGLE-NEXT:    sts fpscr,r2
; SINGLE-NEXT:    xor r1,r2
; SINGLE-NEXT:    lds r2,fpscr
; SINGLE-NEXT:    rts
; SINGLE-NEXT:    nop
  %r = fptrunc double %a to float
  ret float %r
}

define i32 @toint(double %a) {
; SH4-LABEL: toint:
; SH4:         .cfi_startproc
; SH4-NEXT:  ! %bb.0:
; SH4-NEXT:    ftrc dr4,fpul
; SH4-NEXT:    sts fpul,r0
; SH4-NEXT:    rts
; SH4-NEXT:    nop
;
; SH4A-LABEL: toint:
; SH4A:         .cfi_startproc
; SH4A-NEXT:  ! %bb.0:
; SH4A-NEXT:    ftrc dr4,fpul
; SH4A-NEXT:    sts fpul,r0
; SH4A-NEXT:    rts
; SH4A-NEXT:    nop
;
; SINGLE-LABEL: toint:
; SINGLE:         .cfi_startproc
; SINGLE-NEXT:  ! %bb.0:
; SINGLE-NEXT:    mov #8,r1
; SINGLE-NEXT:    shll16 r1
; SINGLE-NEXT:    sts fpscr,r2
; SINGLE-NEXT:    xor r1,r2
; SINGLE-NEXT:    lds r2,fpscr
; SINGLE-NEXT:    ftrc dr4,fpul
; SINGLE-NEXT:    sts fpul,r0
; SINGLE-NEXT:    mov #8,r1
; SINGLE-NEXT:    shll16 r1
; SINGLE-NEXT:    sts fpscr,r2
; SINGLE-NEXT:    xor r1,r2
; SINGLE-NEXT:    lds r2,fpscr
; SINGLE-NEXT:    rts
; SINGLE-NEXT:    nop
  %r = fptosi double %a to i32
  ret i32 %r
}

define i32 @ftoint(float %a) {
; SH4-LABEL: ftoint:
; SH4:         .cfi_startproc
; SH4-NEXT:  ! %bb.0:
; SH4-NEXT:    mov #8,r1
; SH4-NEXT:    shll16 r1
; SH4-NEXT:    sts fpscr,r2
; SH4-NEXT:    xor r1,r2
; SH4-NEXT:    lds r2,fpscr
; SH4-NEXT:    ftrc fr5,fpul
; SH4-NEXT:    sts fpul,r0
; SH4-NEXT:    mov #8,r1
; SH4-NEXT:    shll16 r1
; SH4-NEXT:    sts fpscr,r2
; SH4-NEXT:    xor r1,r2
; SH4-NEXT:    lds r2,fpscr
; SH4-NEXT:    rts
; SH4-NEXT:    nop
;
; SH4A-LABEL: ftoint:
; SH4A:         .cfi_startproc
; SH4A-NEXT:  ! %bb.0:
; SH4A-NEXT:    fpchg
; SH4A-NEXT:    ftrc fr5,fpul
; SH4A-NEXT:    sts fpul,r0
; SH4A-NEXT:    fpchg
; SH4A-NEXT:    rts
; SH4A-NEXT:    nop
;
; SINGLE-LABEL: ftoint:
; SINGLE:         .cfi_startproc
; SINGLE-NEXT:  ! %bb.0:
; SINGLE-NEXT:    ftrc fr5,fpul
; SINGLE-NEXT:    sts fpul,r0
; SINGLE-NEXT:    rts
; SINGLE-NEXT:    nop
  %r = fptosi float %a to i32
  ret i32 %r
}

define double @fromint(i32 %a) {
; SH4-LABEL: fromint:
; SH4:         .cfi_startproc
; SH4-NEXT:  ! %bb.0:
; SH4-NEXT:    lds r4,fpul
; SH4-NEXT:    float fpul,dr0
; SH4-NEXT:    rts
; SH4-NEXT:    nop
;
; SH4A-LABEL: fromint:
; SH4A:         .cfi_startproc
; SH4A-NEXT:  ! %bb.0:
; SH4A-NEXT:    lds r4,fpul
; SH4A-NEXT:    float fpul,dr0
; SH4A-NEXT:    rts
; SH4A-NEXT:    nop
;
; SINGLE-LABEL: fromint:
; SINGLE:         .cfi_startproc
; SINGLE-NEXT:  ! %bb.0:
; SINGLE-NEXT:    mov #8,r1
; SINGLE-NEXT:    shll16 r1
; SINGLE-NEXT:    sts fpscr,r2
; SINGLE-NEXT:    xor r1,r2
; SINGLE-NEXT:    lds r2,fpscr
; SINGLE-NEXT:    lds r4,fpul
; SINGLE-NEXT:    float fpul,dr0
; SINGLE-NEXT:    mov #8,r1
; SINGLE-NEXT:    shll16 r1
; SINGLE-NEXT:    sts fpscr,r2
; SINGLE-NEXT:    xor r1,r2
; SINGLE-NEXT:    lds r2,fpscr
; SINGLE-NEXT:    rts
; SINGLE-NEXT:    nop
  %r = sitofp i32 %a to double
  ret double %r
}

define float @bits(i32 %a) {
; SH4-LABEL: bits:
; SH4:         .cfi_startproc
; SH4-NEXT:  ! %bb.0:
; SH4-NEXT:    lds r4,fpul
; SH4-NEXT:    fsts fpul,fr0
; SH4-NEXT:    rts
; SH4-NEXT:    nop
;
; SH4A-LABEL: bits:
; SH4A:         .cfi_startproc
; SH4A-NEXT:  ! %bb.0:
; SH4A-NEXT:    lds r4,fpul
; SH4A-NEXT:    fsts fpul,fr0
; SH4A-NEXT:    rts
; SH4A-NEXT:    nop
;
; SINGLE-LABEL: bits:
; SINGLE:         .cfi_startproc
; SINGLE-NEXT:  ! %bb.0:
; SINGLE-NEXT:    lds r4,fpul
; SINGLE-NEXT:    fsts fpul,fr0
; SINGLE-NEXT:    rts
; SINGLE-NEXT:    nop
  %r = bitcast i32 %a to float
  ret float %r
}

define i32 @tobits(float %a) {
; SH4-LABEL: tobits:
; SH4:         .cfi_startproc
; SH4-NEXT:  ! %bb.0:
; SH4-NEXT:    flds fr5,fpul
; SH4-NEXT:    sts fpul,r0
; SH4-NEXT:    rts
; SH4-NEXT:    nop
;
; SH4A-LABEL: tobits:
; SH4A:         .cfi_startproc
; SH4A-NEXT:  ! %bb.0:
; SH4A-NEXT:    flds fr5,fpul
; SH4A-NEXT:    sts fpul,r0
; SH4A-NEXT:    rts
; SH4A-NEXT:    nop
;
; SINGLE-LABEL: tobits:
; SINGLE:         .cfi_startproc
; SINGLE-NEXT:  ! %bb.0:
; SINGLE-NEXT:    flds fr5,fpul
; SINGLE-NEXT:    sts fpul,r0
; SINGLE-NEXT:    rts
; SINGLE-NEXT:    nop
  %r = bitcast float %a to i32
  ret i32 %r
}

; A constant comes from the constant pool, whose address is a literal.
define double @constant() {
; SH4-LABEL: constant:
; SH4:         .cfi_startproc
; SH4-NEXT:  ! %bb.0:
; SH4-NEXT:    mov.l .Ltmp0,r1
; SH4-NEXT:    fmov.s @r1+,fr1
; SH4-NEXT:    fmov.s @r1,fr0
; SH4-NEXT:    add #-4,r1
; SH4-NEXT:    rts
; SH4-NEXT:    nop
; SH4-NEXT:    .p2align 2
; SH4-NEXT:  ! %bb.1:
; SH4-NEXT:  .Ltmp0:
; SH4-NEXT:    .ualong .LCPI15_0
;
; SH4A-LABEL: constant:
; SH4A:         .cfi_startproc
; SH4A-NEXT:  ! %bb.0:
; SH4A-NEXT:    mov.l .Ltmp0,r1
; SH4A-NEXT:    fmov.s @r1+,fr1
; SH4A-NEXT:    fmov.s @r1,fr0
; SH4A-NEXT:    add #-4,r1
; SH4A-NEXT:    rts
; SH4A-NEXT:    nop
; SH4A-NEXT:    .p2align 2
; SH4A-NEXT:  ! %bb.1:
; SH4A-NEXT:  .Ltmp0:
; SH4A-NEXT:    .ualong .LCPI15_0
;
; SINGLE-LABEL: constant:
; SINGLE:         .cfi_startproc
; SINGLE-NEXT:  ! %bb.0:
; SINGLE-NEXT:    mov.l .Ltmp0,r1
; SINGLE-NEXT:    fmov.s @r1+,fr1
; SINGLE-NEXT:    fmov.s @r1,fr0
; SINGLE-NEXT:    add #-4,r1
; SINGLE-NEXT:    rts
; SINGLE-NEXT:    nop
; SINGLE-NEXT:    .p2align 2
; SINGLE-NEXT:  ! %bb.1:
; SINGLE-NEXT:  .Ltmp0:
; SINGLE-NEXT:    .ualong .LCPI15_0
  ret double 1.5
}

; A double in memory is two halves, the one with the lower address first.
define double @load(ptr %p) {
; SH4-LABEL: load:
; SH4:         .cfi_startproc
; SH4-NEXT:  ! %bb.0:
; SH4-NEXT:    fmov.s @r4+,fr1
; SH4-NEXT:    fmov.s @r4,fr0
; SH4-NEXT:    add #-4,r4
; SH4-NEXT:    rts
; SH4-NEXT:    nop
;
; SH4A-LABEL: load:
; SH4A:         .cfi_startproc
; SH4A-NEXT:  ! %bb.0:
; SH4A-NEXT:    fmov.s @r4+,fr1
; SH4A-NEXT:    fmov.s @r4,fr0
; SH4A-NEXT:    add #-4,r4
; SH4A-NEXT:    rts
; SH4A-NEXT:    nop
;
; SINGLE-LABEL: load:
; SINGLE:         .cfi_startproc
; SINGLE-NEXT:  ! %bb.0:
; SINGLE-NEXT:    fmov.s @r4+,fr1
; SINGLE-NEXT:    fmov.s @r4,fr0
; SINGLE-NEXT:    add #-4,r4
; SINGLE-NEXT:    rts
; SINGLE-NEXT:    nop
  %r = load double, ptr %p
  ret double %r
}

define void @store(ptr %p, double %v) {
; SH4-LABEL: store:
; SH4:         .cfi_startproc
; SH4-NEXT:  ! %bb.0:
; SH4-NEXT:    add #8,r4
; SH4-NEXT:    fmov.s fr4,@-r4
; SH4-NEXT:    fmov.s fr5,@-r4
; SH4-NEXT:    rts
; SH4-NEXT:    nop
;
; SH4A-LABEL: store:
; SH4A:         .cfi_startproc
; SH4A-NEXT:  ! %bb.0:
; SH4A-NEXT:    add #8,r4
; SH4A-NEXT:    fmov.s fr4,@-r4
; SH4A-NEXT:    fmov.s fr5,@-r4
; SH4A-NEXT:    rts
; SH4A-NEXT:    nop
;
; SINGLE-LABEL: store:
; SINGLE:         .cfi_startproc
; SINGLE-NEXT:  ! %bb.0:
; SINGLE-NEXT:    add #8,r4
; SINGLE-NEXT:    fmov.s fr4,@-r4
; SINGLE-NEXT:    fmov.s fr5,@-r4
; SINGLE-NEXT:    rts
; SINGLE-NEXT:    nop
  store double %v, ptr %p
  ret void
}

define float @fload(ptr %p) {
; SH4-LABEL: fload:
; SH4:         .cfi_startproc
; SH4-NEXT:  ! %bb.0:
; SH4-NEXT:    add #12,r4
; SH4-NEXT:    fmov.s @r4,fr0
; SH4-NEXT:    rts
; SH4-NEXT:    nop
;
; SH4A-LABEL: fload:
; SH4A:         .cfi_startproc
; SH4A-NEXT:  ! %bb.0:
; SH4A-NEXT:    add #12,r4
; SH4A-NEXT:    fmov.s @r4,fr0
; SH4A-NEXT:    rts
; SH4A-NEXT:    nop
;
; SINGLE-LABEL: fload:
; SINGLE:         .cfi_startproc
; SINGLE-NEXT:  ! %bb.0:
; SINGLE-NEXT:    add #12,r4
; SINGLE-NEXT:    fmov.s @r4,fr0
; SINGLE-NEXT:    rts
; SINGLE-NEXT:    nop
  %q = getelementptr float, ptr %p, i32 3
  %r = load float, ptr %q
  ret float %r
}

declare double @ext(double)

; fr12 to fr15 are saved by the callee, and the bit is what the convention
; says at the call.
define float @across_call(float %a) {
; SH4-LABEL: across_call:
; SH4:         .cfi_startproc
; SH4-NEXT:  ! %bb.0:
; SH4-NEXT:    sts.l pr,@-r15
; SH4-NEXT:    .cfi_def_cfa_offset 4
; SH4-NEXT:    .cfi_offset pr, -4
; SH4-NEXT:    fmov.s fr12,@-r15
; SH4-NEXT:    .cfi_def_cfa_offset 8
; SH4-NEXT:    .cfi_offset fr12, -8
; SH4-NEXT:    fmov fr5,fr12
; SH4-NEXT:    flds fr12,fpul
; SH4-NEXT:    fcnvsd fpul,dr4
; SH4-NEXT:    mov.l .Ltmp1,r1
; SH4-NEXT:    jsr @r1
; SH4-NEXT:    nop
; SH4-NEXT:    fcnvds dr0,fpul
; SH4-NEXT:    fsts fpul,fr0
; SH4-NEXT:    mov #8,r1
; SH4-NEXT:    shll16 r1
; SH4-NEXT:    sts fpscr,r2
; SH4-NEXT:    xor r1,r2
; SH4-NEXT:    lds r2,fpscr
; SH4-NEXT:    fmul fr12,fr0
; SH4-NEXT:    mov #8,r1
; SH4-NEXT:    shll16 r1
; SH4-NEXT:    sts fpscr,r2
; SH4-NEXT:    xor r1,r2
; SH4-NEXT:    lds r2,fpscr
; SH4-NEXT:    fmov.s @r15+,fr12
; SH4-NEXT:    lds.l @r15+,pr
; SH4-NEXT:    rts
; SH4-NEXT:    nop
; SH4-NEXT:    .p2align 2
; SH4-NEXT:  ! %bb.1:
; SH4-NEXT:  .Ltmp1:
; SH4-NEXT:    .ualong ext
;
; SH4A-LABEL: across_call:
; SH4A:         .cfi_startproc
; SH4A-NEXT:  ! %bb.0:
; SH4A-NEXT:    sts.l pr,@-r15
; SH4A-NEXT:    .cfi_def_cfa_offset 4
; SH4A-NEXT:    .cfi_offset pr, -4
; SH4A-NEXT:    fmov.s fr12,@-r15
; SH4A-NEXT:    .cfi_def_cfa_offset 8
; SH4A-NEXT:    .cfi_offset fr12, -8
; SH4A-NEXT:    fmov fr5,fr12
; SH4A-NEXT:    flds fr12,fpul
; SH4A-NEXT:    fcnvsd fpul,dr4
; SH4A-NEXT:    mov.l .Ltmp1,r1
; SH4A-NEXT:    jsr @r1
; SH4A-NEXT:    nop
; SH4A-NEXT:    fcnvds dr0,fpul
; SH4A-NEXT:    fsts fpul,fr0
; SH4A-NEXT:    fpchg
; SH4A-NEXT:    fmul fr12,fr0
; SH4A-NEXT:    fpchg
; SH4A-NEXT:    fmov.s @r15+,fr12
; SH4A-NEXT:    lds.l @r15+,pr
; SH4A-NEXT:    rts
; SH4A-NEXT:    nop
; SH4A-NEXT:    .p2align 2
; SH4A-NEXT:  ! %bb.1:
; SH4A-NEXT:  .Ltmp1:
; SH4A-NEXT:    .ualong ext
;
; SINGLE-LABEL: across_call:
; SINGLE:         .cfi_startproc
; SINGLE-NEXT:  ! %bb.0:
; SINGLE-NEXT:    sts.l pr,@-r15
; SINGLE-NEXT:    .cfi_def_cfa_offset 4
; SINGLE-NEXT:    .cfi_offset pr, -4
; SINGLE-NEXT:    fmov.s fr12,@-r15
; SINGLE-NEXT:    .cfi_def_cfa_offset 8
; SINGLE-NEXT:    .cfi_offset fr12, -8
; SINGLE-NEXT:    fmov fr5,fr12
; SINGLE-NEXT:    mov #8,r1
; SINGLE-NEXT:    shll16 r1
; SINGLE-NEXT:    sts fpscr,r2
; SINGLE-NEXT:    xor r1,r2
; SINGLE-NEXT:    lds r2,fpscr
; SINGLE-NEXT:    flds fr12,fpul
; SINGLE-NEXT:    fcnvsd fpul,dr4
; SINGLE-NEXT:    mov.l .Ltmp1,r1
; SINGLE-NEXT:    mov #8,r2
; SINGLE-NEXT:    shll16 r2
; SINGLE-NEXT:    sts fpscr,r3
; SINGLE-NEXT:    xor r2,r3
; SINGLE-NEXT:    lds r3,fpscr
; SINGLE-NEXT:    jsr @r1
; SINGLE-NEXT:    nop
; SINGLE-NEXT:    mov #8,r1
; SINGLE-NEXT:    shll16 r1
; SINGLE-NEXT:    sts fpscr,r2
; SINGLE-NEXT:    xor r1,r2
; SINGLE-NEXT:    lds r2,fpscr
; SINGLE-NEXT:    fcnvds dr0,fpul
; SINGLE-NEXT:    fsts fpul,fr0
; SINGLE-NEXT:    mov #8,r1
; SINGLE-NEXT:    shll16 r1
; SINGLE-NEXT:    sts fpscr,r2
; SINGLE-NEXT:    xor r1,r2
; SINGLE-NEXT:    lds r2,fpscr
; SINGLE-NEXT:    fmul fr12,fr0
; SINGLE-NEXT:    fmov.s @r15+,fr12
; SINGLE-NEXT:    lds.l @r15+,pr
; SINGLE-NEXT:    rts
; SINGLE-NEXT:    nop
; SINGLE-NEXT:    .p2align 2
; SINGLE-NEXT:  ! %bb.1:
; SINGLE-NEXT:  .Ltmp1:
; SINGLE-NEXT:    .ualong ext
  %d = fpext float %a to double
  %c = call double @ext(double %d)
  %f = fptrunc double %c to float
  %r = fmul float %f, %a
  ret float %r
}

declare float @llvm.fabs.f32(float)
declare double @llvm.sqrt.f64(double)
