; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4-nofpu -verify-machineinstrs < %s | FileCheck %s

declare void @use(ptr)
declare i32 @callee6(i32, i32, i32, i32, i32, i32)

; A function that calls another saves pr.
define void @local() {
; CHECK-LABEL: local:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    add #-16,r15
; CHECK-NEXT:    .cfi_def_cfa_offset 20
; CHECK-NEXT:    mov.l .Ltmp0,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    mov r15,r4
; CHECK-NEXT:    add #16,r15
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp0:
; CHECK-NEXT:    .ualong use
  %a = alloca [4 x i32]
  call void @use(ptr %a)
  ret void
}

; r14 is the frame pointer, with the value that the stack pointer has
; behind the prologue.
define void @frame_pointer() "frame-pointer"="all" {
; CHECK-LABEL: frame_pointer:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.l r14,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset r14, -4
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    .cfi_offset pr, -8
; CHECK-NEXT:    add #-16,r15
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    mov r15,r14
; CHECK-NEXT:    .cfi_def_cfa_register r14
; CHECK-NEXT:    mov.l .Ltmp1,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    mov r14,r4
; CHECK-NEXT:    mov r14,r15
; CHECK-NEXT:    add #16,r15
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    mov.l @r15+,r14
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp1:
; CHECK-NEXT:    .ualong use
  %a = alloca [4 x i32]
  call void @use(ptr %a)
  ret void
}

; A frame whose size is no immediate, and slots that no displacement
; reaches.
define i32 @large(i32 %v) {
; CHECK-LABEL: large:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    mov.l .Ltmp2,r1
; CHECK-NEXT:    add r1,r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4004
; CHECK-NEXT:    mov.l .Ltmp3,r1
; CHECK-NEXT:    add r15,r1
; CHECK-NEXT:    mov.l r4,@r1
; CHECK-NEXT:    mov.l .Ltmp4,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    mov r15,r4
; CHECK-NEXT:    mov.l .Ltmp3,r0
; CHECK-NEXT:    add r15,r0
; CHECK-NEXT:    mov.l @r0,r0
; CHECK-NEXT:    mov.l .Ltmp5,r7
; CHECK-NEXT:    add r7,r15
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp2:
; CHECK-NEXT:    .ualong 4294963296
; CHECK-NEXT:  .Ltmp3:
; CHECK-NEXT:    .ualong 3600
; CHECK-NEXT:  .Ltmp4:
; CHECK-NEXT:    .ualong use
; CHECK-NEXT:  .Ltmp5:
; CHECK-NEXT:    .ualong 4000
  %a = alloca [1000 x i32]
  %p = getelementptr [1000 x i32], ptr %a, i32 0, i32 900
  store volatile i32 %v, ptr %p
  call void @use(ptr %a)
  %r = load volatile i32, ptr %p
  ret i32 %r
}

; Memory of variable size: the stack pointer moves, and r14 stays.
define i32 @dynamic(i32 %n) {
; CHECK-LABEL: dynamic:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.l r14,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset r14, -4
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    .cfi_offset pr, -8
; CHECK-NEXT:    mov r15,r14
; CHECK-NEXT:    .cfi_def_cfa_register r14
; CHECK-NEXT:    shll2 r4
; CHECK-NEXT:    mov r15,r2
; CHECK-NEXT:    sub r4,r2
; CHECK-NEXT:    mov r2,r15
; CHECK-NEXT:    mov.l .Ltmp6,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    mov r2,r4
; CHECK-NEXT:    add #-8,r15
; CHECK-NEXT:    mov #6,r1
; CHECK-NEXT:    mov.l r1,@(4,r15)
; CHECK-NEXT:    mov #5,r1
; CHECK-NEXT:    mov.l r1,@r15
; CHECK-NEXT:    mov.l .Ltmp7,r1
; CHECK-NEXT:    mov #1,r4
; CHECK-NEXT:    mov #2,r5
; CHECK-NEXT:    mov #3,r6
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    mov #4,r7
; CHECK-NEXT:    add #8,r15
; CHECK-NEXT:    mov r14,r15
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    mov.l @r15+,r14
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp6:
; CHECK-NEXT:    .ualong use
; CHECK-NEXT:  .Ltmp7:
; CHECK-NEXT:    .ualong callee6
  %a = alloca i32, i32 %n
  call void @use(ptr %a)
  %r = call i32 @callee6(i32 1, i32 2, i32 3, i32 4, i32 5, i32 6)
  ret i32 %r
}

; A variable that is aligned to more than four bytes: the prologue rounds
; the stack pointer down, and r14 is what it was behind the pushes.
define void @realign() {
; CHECK-LABEL: realign:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.l r14,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset r14, -4
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    .cfi_offset pr, -8
; CHECK-NEXT:    mov r15,r14
; CHECK-NEXT:    .cfi_def_cfa_register r14
; CHECK-NEXT:    add #-24,r15
; CHECK-NEXT:    mov #-32,r1
; CHECK-NEXT:    and r1,r15
; CHECK-NEXT:    mov.l .Ltmp8,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    mov r15,r4
; CHECK-NEXT:    mov r14,r15
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    mov.l @r15+,r14
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp8:
; CHECK-NEXT:    .ualong use
  %a = alloca [4 x i32], align 32
  call void @use(ptr %a)
  ret void
}

; Both: r13 is the base of the local variables.
define void @realign_dynamic(i32 %n) {
; CHECK-LABEL: realign_dynamic:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.l r8,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset r8, -4
; CHECK-NEXT:    mov.l r9,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    .cfi_offset r9, -8
; CHECK-NEXT:    mov.l r13,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 12
; CHECK-NEXT:    .cfi_offset r13, -12
; CHECK-NEXT:    mov.l r14,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset r14, -16
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 20
; CHECK-NEXT:    .cfi_offset pr, -20
; CHECK-NEXT:    mov r15,r14
; CHECK-NEXT:    .cfi_def_cfa_register r14
; CHECK-NEXT:    add #-44,r15
; CHECK-NEXT:    mov #-32,r1
; CHECK-NEXT:    and r1,r15
; CHECK-NEXT:    mov r15,r13
; CHECK-NEXT:    shll2 r4
; CHECK-NEXT:    mov r15,r8
; CHECK-NEXT:    sub r4,r8
; CHECK-NEXT:    mov r8,r15
; CHECK-NEXT:    mov.l .Ltmp9,r9
; CHECK-NEXT:    jsr @r9
; CHECK-NEXT:    mov r13,r4
; CHECK-NEXT:    jsr @r9
; CHECK-NEXT:    mov r8,r4
; CHECK-NEXT:    mov r14,r15
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    mov.l @r15+,r14
; CHECK-NEXT:    mov.l @r15+,r13
; CHECK-NEXT:    mov.l @r15+,r9
; CHECK-NEXT:    rts
; CHECK-NEXT:    mov.l @r15+,r8
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp9:
; CHECK-NEXT:    .ualong use
  %a = alloca [4 x i32], align 32
  %b = alloca i32, i32 %n
  call void @use(ptr %a)
  call void @use(ptr %b)
  ret void
}

define ptr @frame_address() {
; CHECK-LABEL: frame_address:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.l r14,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset r14, -4
; CHECK-NEXT:    mov r15,r14
; CHECK-NEXT:    .cfi_def_cfa_register r14
; CHECK-NEXT:    mov r14,r0
; CHECK-NEXT:    mov r14,r15
; CHECK-NEXT:    rts
; CHECK-NEXT:    mov.l @r15+,r14
  %r = call ptr @llvm.frameaddress(i32 0)
  ret ptr %r
}

define ptr @return_address() {
; CHECK-LABEL: return_address:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    rts
; CHECK-NEXT:    sts pr,r0
  %r = call ptr @llvm.returnaddress(i32 0)
  ret ptr %r
}

declare ptr @llvm.frameaddress(i32)
declare ptr @llvm.returnaddress(i32)

; A result of four words is in r0 to r3, so the epilogue of a frame that is
; too large for "add #imm,r15" loads the size into r7.
declare void @fill(ptr)

define { i64, i64 } @large_frame_four_words() {
; CHECK-LABEL: large_frame_four_words:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    mov #-100,r1
; CHECK-NEXT:    shll2 r1
; CHECK-NEXT:    add r1,r15
; CHECK-NEXT:    .cfi_def_cfa_offset 404
; CHECK-NEXT:    mov.l .Ltmp10,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    mov r15,r4
; CHECK-NEXT:    mov.l @r15,r0
; CHECK-NEXT:    mov.l @(4,r15),r1
; CHECK-NEXT:    mov r0,r2
; CHECK-NEXT:    mov #100,r7
; CHECK-NEXT:    shll2 r7
; CHECK-NEXT:    add r7,r15
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    mov r1,r3
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp10:
; CHECK-NEXT:    .ualong fill
  %buf = alloca [400 x i8]
  call void @fill(ptr %buf)
  %a = load i64, ptr %buf
  %b = insertvalue { i64, i64 } undef, i64 %a, 0
  %c = insertvalue { i64, i64 } %b, i64 %a, 1
  ret { i64, i64 } %c
}
