; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4-nofpu -verify-machineinstrs < %s | FileCheck %s

; A number that does not fit the eight bits of an immediate comes from a
; literal, unless one more instruction makes it of a number that fits: an
; extension without sign, or a shift by 1, 2, 8 or 16 bits.

define i32 @u8() {
; CHECK-LABEL: u8:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov #-16,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    extu.b r0,r0
  ret i32 240
}

define i32 @u16() {
; CHECK-LABEL: u16:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov #-1,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    extu.w r0,r0
  ret i32 65535
}

define i32 @twice() {
; CHECK-LABEL: twice:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov #-100,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    add r0,r0
  ret i32 -200
}

define i32 @shifted2() {
; CHECK-LABEL: shifted2:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov #127,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    shll2 r0
  ret i32 508
}

define i32 @shifted8() {
; CHECK-LABEL: shifted8:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov #16,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    shll8 r0
  ret i32 4096
}

define i32 @mask() {
; CHECK-LABEL: mask:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov #-16,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    shll8 r0
  ret i32 -4096
}

define i32 @shifted16() {
; CHECK-LABEL: shifted16:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov #127,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    shll16 r0
  ret i32 8323072
}

; Neither 255 nor 510 nor 1000 is such a number.
define i32 @literal(i32 %a, i32 %b) {
; CHECK-LABEL: literal:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.l .Ltmp0,r1
; CHECK-NEXT:    add r5,r1
; CHECK-NEXT:    mov.l .Ltmp1,r2
; CHECK-NEXT:    mul.l r2,r4
; CHECK-NEXT:    sts macl,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    xor r1,r0
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp0:
; CHECK-NEXT:    .ualong 510
; CHECK-NEXT:  .Ltmp1:
; CHECK-NEXT:    .ualong 1000
  %x = mul i32 %a, 1000
  %y = add i32 %b, 510
  %z = xor i32 %x, %y
  ret i32 %z
}

; The offset of a member that a displacement does not reach.
define i32 @member(ptr %p) {
; CHECK-LABEL: member:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov #-16,r1
; CHECK-NEXT:    extu.b r1,r1
; CHECK-NEXT:    add r4,r1
; CHECK-NEXT:    rts
; CHECK-NEXT:    mov.l @r1,r0
  %q = getelementptr i8, ptr %p, i32 240
  %v = load i32, ptr %q
  ret i32 %v
}
