; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4 -verify-machineinstrs < %s | FileCheck %s

; The register constraints of GCC that name one register or the registers
; of the floating point unit: "z" is r0, "f" a register for a float, "d"
; one for a double, "w" is fr0.

; The value lives on in another register while r0 is the operand: the
; operand is r0 itself, not a value that has to stay there.
define i32 @r0(i32 %a, i32 %b) {
; CHECK-LABEL: r0:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    add r5,r0
; CHECK-NEXT:    !APP
; CHECK-NEXT:    tst #15,r0
; CHECK-EMPTY:
; CHECK-NEXT:    movt r1
; CHECK-EMPTY:
; CHECK-NEXT:    !NO_APP
; CHECK-NEXT:    add r0,r1
; CHECK-NEXT:    rts
; CHECK-NEXT:    mov r1,r0
  %x = add i32 %a, %b
  %t = call i32 asm "tst #15,$1\0A\09movt $0", "=r,z,~{t}"(i32 %x)
  %r = add i32 %t, %x
  ret i32 %r
}

define float @single(float %a, float %b) {
; CHECK-LABEL: single:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    fmov fr5,fr0
; CHECK-NEXT:    !APP
; CHECK-NEXT:    fmov fr4,fr0
; CHECK-EMPTY:
; CHECK-NEXT:    !NO_APP
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %r = call float asm "fmov $2,$0", "=f,0,f"(float %a, float %b)
  ret float %r
}

define double @double(double %a) {
; CHECK-LABEL: double:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    fmov fr4,fr0
; CHECK-NEXT:    fmov fr5,fr1
; CHECK-NEXT:    !APP
; CHECK-NEXT:    fneg dr0
; CHECK-EMPTY:
; CHECK-NEXT:    !NO_APP
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %r = call double asm "fneg $0", "=d,0"(double %a)
  ret double %r
}

define float @first(float %a) {
; CHECK-LABEL: first:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    fmov fr5,fr0
; CHECK-NEXT:    !APP
; CHECK-NEXT:    fmov fr0,fr0
; CHECK-EMPTY:
; CHECK-NEXT:    !NO_APP
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %r = call float asm "fmov $1,$0", "=f,w"(float %a)
  ret float %r
}
