; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4-nofpu -verify-machineinstrs < %s | FileCheck %s
; RUN: not llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4-nofpu -filetype=asm -o /dev/null %S/Inputs/inline-asm-bad.ll 2>&1 | FileCheck --check-prefix=BAD %s

; Inline assembly as GCC prints it: a register by its name, a constant with
; "#" in front of it.

; "z" is r0.
define i32 @reg(i32 %a) {
; CHECK-LABEL: reg:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    !APP
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    add #5,r0
; CHECK-NEXT:    !NO_APP
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %r = call i32 asm "mov $1,$0\0A\09add $2,$0", "=&z,r,i,~{t}"(i32 %a, i32 5)
  ret i32 %r
}

; %O is the constant without the "#".
define void @plain_constant() {
; CHECK-LABEL: plain_constant:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    !APP
; CHECK-NEXT:    1: .short 49918
; CHECK-NEXT:    !NO_APP
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  call void asm "1:\09.short ${0:O}", "n,~{memory}"(i32 49918)
  ret void
}

; The address of "m" is in a register.
define i32 @memory(ptr %p) {
; CHECK-LABEL: memory:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    !APP
; CHECK-NEXT:    mov.l @r4,r0
; CHECK-NEXT:    !NO_APP
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %r = call i32 asm "mov.l $1,$0", "=r,*m"(ptr elementtype(i32) %p)
  ret i32 %r
}

; A stack slot gets its address computed first.
define i32 @memory_stack() {
; CHECK-LABEL: memory_stack:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    add #-4,r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    mov #7,r1
; CHECK-NEXT:    mov.l r1,@r15
; CHECK-NEXT:    mov r15,r1
; CHECK-NEXT:    !APP
; CHECK-NEXT:    mov.l @r1,r0
; CHECK-NEXT:    !NO_APP
; CHECK-NEXT:    add #4,r15
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %slot = alloca i32
  store i32 7, ptr %slot
  %r = call i32 asm "mov.l $1,$0", "=r,*m"(ptr elementtype(i32) %slot)
  ret i32 %r
}

; A 64-bit value is two registers: %R is the one with the low half, %S the
; one with the high half.  %T of a memory operand is its second word.
define i64 @wide(ptr %p) {
; CHECK-LABEL: wide:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    !APP
; CHECK-NEXT:    mov.l @r4,r0
; CHECK-NEXT:    mov.l @(4,r4),r1
; CHECK-NEXT:    !NO_APP
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %r = call i64 asm "mov.l $1,${0:R}\0A\09mov.l ${1:T},${0:S}", "=&r,*m"(ptr elementtype(i64) %p)
  ret i64 %r
}

; What an instruction of the assembly destroys.
define i32 @clobbers(i32 %a, i32 %b) {
; CHECK-LABEL: clobbers:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    !APP
; CHECK-NEXT:    mul.l r0,r5
; CHECK-NEXT:    !NO_APP
; CHECK-NEXT:    add r5,r0
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  call void asm "mul.l $0,$1", "r,r,~{macl},~{mach},~{pr},~{r1}"(i32 %a, i32 %b)
  %s = add i32 %a, %b
  ret i32 %s
}

; "register unsigned long sp asm("r15")"
define i32 @stack_pointer() {
; CHECK-LABEL: stack_pointer:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r15,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %r = call i32 @llvm.read_register.i32(metadata !0)
  ret i32 %r
}

declare i32 @llvm.read_register.i32(metadata)
!0 = !{!"r15"}

; BAD: error: invalid operand in inline asm: 'mov.l @r1,${0:S}'
