; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4-nofpu -verify-machineinstrs < %s | FileCheck %s

; A number that is no eight bit immediate, and every address, is loaded
; from a literal behind the code.

@g = global i32 0
declare void @ext(i32)

define i32 @small() {
; CHECK-LABEL: small:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov #127,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  ret i32 127
}

define i32 @negative() {
; CHECK-LABEL: negative:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov #-128,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  ret i32 -128
}

; An eight bit number that is shifted needs no literal.
define i32 @shifted() {
; CHECK-LABEL: shifted:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.l .Ltmp0,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp0:
; CHECK-NEXT:    .ualong 4096
  ret i32 4096
}

define i32 @big() {
; CHECK-LABEL: big:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.l .Ltmp1,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp1:
; CHECK-NEXT:    .ualong 305419896
  ret i32 305419896
}

; The same literal is there once.
define i32 @twice(i32 %a) {
; CHECK-LABEL: twice:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.l .Ltmp2,r0
; CHECK-NEXT:    add r0,r4
; CHECK-NEXT:    xor r4,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp2:
; CHECK-NEXT:    .ualong 100000
  %x = add i32 %a, 100000
  %y = xor i32 %x, 100000
  ret i32 %y
}

define ptr @address() {
; CHECK-LABEL: address:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.l .Ltmp3,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp3:
; CHECK-NEXT:    .ualong g
  ret ptr @g
}

define ptr @address_offset() {
; CHECK-LABEL: address_offset:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.l .Ltmp4,r0
; CHECK-NEXT:    add #100,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp4:
; CHECK-NEXT:    .ualong g
  ret ptr getelementptr (i32, ptr @g, i32 25)
}

; Behind a branch nothing runs into the literals, so they can go there.
define void @behind_branch(i32 %a) {
; CHECK-LABEL: behind_branch:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.l r8,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset r8, -4
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    .cfi_offset pr, -8
; CHECK-NEXT:    tst r4,r4
; CHECK-NEXT:    mov.l .Ltmp5,r8
; CHECK-NEXT:    bf .LBB7_2
; CHECK-NEXT:  ! %bb.1: ! %t
; CHECK-NEXT:    mov.l .Ltmp6,r4
; CHECK-NEXT:    jsr @r8
; CHECK-NEXT:    nop
; CHECK-NEXT:  .LBB7_2: ! %e
; CHECK-NEXT:    mov.l .Ltmp7,r4
; CHECK-NEXT:    jsr @r8
; CHECK-NEXT:    nop
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    mov.l @r15+,r8
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.3:
; CHECK-NEXT:  .Ltmp5:
; CHECK-NEXT:    .ualong ext
; CHECK-NEXT:  .Ltmp6:
; CHECK-NEXT:    .ualong 100000
; CHECK-NEXT:  .Ltmp7:
; CHECK-NEXT:    .ualong 200000
  %c = icmp eq i32 %a, 0
  br i1 %c, label %t, label %e
t:
  call void @ext(i32 100000)
  br label %e
e:
  call void @ext(i32 200000)
  ret void
}

define i32 @jump_table(i32 %a) {
; CHECK-LABEL: jump_table:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov #4,r1
; CHECK-NEXT:    cmp/hi r1,r4
; CHECK-NEXT:    bt .LBB8_7
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:    shll2 r4
; CHECK-NEXT:    mov.l .Ltmp8,r1
; CHECK-NEXT:    add r4,r1
; CHECK-NEXT:    mov.l @r1,r1
; CHECK-NEXT:    jmp @r1
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.8:
; CHECK-NEXT:  .Ltmp8:
; CHECK-NEXT:    .ualong .LJTI8_0
; CHECK-NEXT:  .LBB8_2: ! %b0
; CHECK-NEXT:    mov #10,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:  .LBB8_6: ! %b4
; CHECK-NEXT:    mov #54,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:  .LBB8_4: ! %b2
; CHECK-NEXT:    mov #32,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:  .LBB8_5: ! %b3
; CHECK-NEXT:    mov #43,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:  .LBB8_3: ! %b1
; CHECK-NEXT:    mov #21,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:  .LBB8_7: ! %d
; CHECK-NEXT:    mov #0,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  switch i32 %a, label %d [
    i32 0, label %b0
    i32 1, label %b1
    i32 2, label %b2
    i32 3, label %b3
    i32 4, label %b4
  ]
b0:
  ret i32 10
b1:
  ret i32 21
b2:
  ret i32 32
b3:
  ret i32 43
b4:
  ret i32 54
d:
  ret i32 0
}

define ptr @block_address() {
; CHECK-LABEL: block_address:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:  .Ltmp10: ! Block address taken
; CHECK-NEXT:  ! %bb.1: ! %next
; CHECK-NEXT:    mov.l .Ltmp9,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.2:
; CHECK-NEXT:  .Ltmp9:
; CHECK-NEXT:    .ualong .Ltmp10
  br label %next
next:
  ret ptr blockaddress(@block_address, %next)
}
