; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4-nofpu -verify-machineinstrs < %s | FileCheck %s

; A product is in MACL, or in MACH and MACL.

define i32 @mul(i32 %a, i32 %b) {
; CHECK-LABEL: mul:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mul.l r5,r4
; CHECK-NEXT:    sts macl,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %r = mul i32 %a, %b
  ret i32 %r
}

define i64 @umul_wide(i32 %a, i32 %b) {
; CHECK-LABEL: umul_wide:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mul.l r5,r4
; CHECK-NEXT:    sts macl,r0
; CHECK-NEXT:    dmulu.l r5,r4
; CHECK-NEXT:    sts mach,r1
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %x = zext i32 %a to i64
  %y = zext i32 %b to i64
  %r = mul i64 %x, %y
  ret i64 %r
}

define i64 @smul_wide(i32 %a, i32 %b) {
; CHECK-LABEL: smul_wide:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mul.l r5,r4
; CHECK-NEXT:    sts macl,r0
; CHECK-NEXT:    dmuls.l r5,r4
; CHECK-NEXT:    sts mach,r1
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %x = sext i32 %a to i64
  %y = sext i32 %b to i64
  %r = mul i64 %x, %y
  ret i64 %r
}

; There is no instruction that divides: libgcc has __sdivsi3 and __udivsi3,
; and nothing for the remainder.

define i32 @sdiv(i32 %a, i32 %b) {
; CHECK-LABEL: sdiv:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    mov.l .Ltmp0,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    nop
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp0:
; CHECK-NEXT:    .ualong __sdivsi3
  %r = sdiv i32 %a, %b
  ret i32 %r
}

define i32 @udiv(i32 %a, i32 %b) {
; CHECK-LABEL: udiv:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    mov.l .Ltmp1,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    nop
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp1:
; CHECK-NEXT:    .ualong __udivsi3
  %r = udiv i32 %a, %b
  ret i32 %r
}

define i32 @srem(i32 %a, i32 %b) {
; CHECK-LABEL: srem:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.l r8,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset r8, -4
; CHECK-NEXT:    mov.l r9,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    .cfi_offset r9, -8
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 12
; CHECK-NEXT:    .cfi_offset pr, -12
; CHECK-NEXT:    mov r5,r8
; CHECK-NEXT:    mov r4,r9
; CHECK-NEXT:    mov.l .Ltmp2,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    nop
; CHECK-NEXT:    mul.l r8,r0
; CHECK-NEXT:    sts macl,r1
; CHECK-NEXT:    sub r1,r9
; CHECK-NEXT:    mov r9,r0
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    mov.l @r15+,r9
; CHECK-NEXT:    mov.l @r15+,r8
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp2:
; CHECK-NEXT:    .ualong __sdivsi3
  %r = srem i32 %a, %b
  ret i32 %r
}

define i32 @urem(i32 %a, i32 %b) {
; CHECK-LABEL: urem:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.l r8,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset r8, -4
; CHECK-NEXT:    mov.l r9,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    .cfi_offset r9, -8
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 12
; CHECK-NEXT:    .cfi_offset pr, -12
; CHECK-NEXT:    mov r5,r8
; CHECK-NEXT:    mov r4,r9
; CHECK-NEXT:    mov.l .Ltmp3,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    nop
; CHECK-NEXT:    mul.l r8,r0
; CHECK-NEXT:    sts macl,r1
; CHECK-NEXT:    sub r1,r9
; CHECK-NEXT:    mov r9,r0
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    mov.l @r15+,r9
; CHECK-NEXT:    mov.l @r15+,r8
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp3:
; CHECK-NEXT:    .ualong __udivsi3
  %r = urem i32 %a, %b
  ret i32 %r
}

define i64 @sdiv64(i64 %a, i64 %b) {
; CHECK-LABEL: sdiv64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    mov.l .Ltmp4,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    nop
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp4:
; CHECK-NEXT:    .ualong __divdi3
  %r = sdiv i64 %a, %b
  ret i64 %r
}
