; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4-nofpu -relocation-model=pic -verify-machineinstrs < %s | FileCheck %s

; Position independent code has the address of the global offset table in a
; register, which is set where the function starts: the address of a literal
; and the distance from that literal to the table.  What the module defines
; for itself is at a fixed distance from the table (sym@GOTOFF), of anything
; else the table has the address (sym@GOT).

@ext = external global i32
@def = global i32 5
@loc = internal global i32 0
@arr = external global [16 x i32]

declare i32 @callee(i32)

define internal i32 @helper(i32 %x) noinline {
; CHECK-LABEL: helper:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mova .Ltmp0,r0
; CHECK-NEXT:    mov.l .Ltmp0,r1
; CHECK-NEXT:    add r0,r1
; CHECK-NEXT:    mov.l .Ltmp1,r2
; CHECK-NEXT:    add r1,r2
; CHECK-NEXT:    mov.l @r2,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    add r4,r0
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp0:
; CHECK-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
; CHECK-NEXT:  .Ltmp1:
; CHECK-NEXT:    .ualong loc@GOTOFF
  %v = load i32, ptr @loc
  %r = add i32 %v, %x
  ret i32 %r
}

; Through the table: the variable can be in another module.
define i32 @load_ext() {
; CHECK-LABEL: load_ext:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mova .Ltmp2,r0
; CHECK-NEXT:    mov.l .Ltmp2,r1
; CHECK-NEXT:    add r0,r1
; CHECK-NEXT:    mov.l .Ltmp3,r2
; CHECK-NEXT:    add r1,r2
; CHECK-NEXT:    mov.l @r2,r1
; CHECK-NEXT:    rts
; CHECK-NEXT:    mov.l @r1,r0
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp2:
; CHECK-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
; CHECK-NEXT:  .Ltmp3:
; CHECK-NEXT:    .ualong ext@GOT
  %v = load i32, ptr @ext
  ret i32 %v
}

; So can one that this module defines: another definition can take its place.
define i32 @load_def() {
; CHECK-LABEL: load_def:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mova .Ltmp4,r0
; CHECK-NEXT:    mov.l .Ltmp4,r1
; CHECK-NEXT:    add r0,r1
; CHECK-NEXT:    mov.l .Ltmp5,r2
; CHECK-NEXT:    add r1,r2
; CHECK-NEXT:    mov.l @r2,r1
; CHECK-NEXT:    rts
; CHECK-NEXT:    mov.l @r1,r0
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp4:
; CHECK-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
; CHECK-NEXT:  .Ltmp5:
; CHECK-NEXT:    .ualong def@GOT
  %v = load i32, ptr @def
  ret i32 %v
}

; Relative to the table.
define i32 @load_loc() {
; CHECK-LABEL: load_loc:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mova .Ltmp6,r0
; CHECK-NEXT:    mov.l .Ltmp6,r1
; CHECK-NEXT:    add r0,r1
; CHECK-NEXT:    mov.l .Ltmp7,r2
; CHECK-NEXT:    add r1,r2
; CHECK-NEXT:    rts
; CHECK-NEXT:    mov.l @r2,r0
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp6:
; CHECK-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
; CHECK-NEXT:  .Ltmp7:
; CHECK-NEXT:    .ualong loc@GOTOFF
  %v = load i32, ptr @loc
  ret i32 %v
}

; An offset is added to the address from the table.
define ptr @element() {
; CHECK-LABEL: element:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mova .Ltmp8,r0
; CHECK-NEXT:    mov.l .Ltmp8,r1
; CHECK-NEXT:    add r0,r1
; CHECK-NEXT:    mov.l .Ltmp9,r2
; CHECK-NEXT:    add r1,r2
; CHECK-NEXT:    mov.l @r2,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    add #12,r0
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp8:
; CHECK-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
; CHECK-NEXT:  .Ltmp9:
; CHECK-NEXT:    .ualong arr@GOT
  ret ptr getelementptr ([16 x i32], ptr @arr, i32 0, i32 3)
}

; A call goes through the address of the function, which is found like the
; address of a variable.
define i32 @call_ext(i32 %x) {
; CHECK-LABEL: call_ext:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    mova .Ltmp10,r0
; CHECK-NEXT:    mov.l .Ltmp10,r1
; CHECK-NEXT:    add r0,r1
; CHECK-NEXT:    mov.l .Ltmp11,r2
; CHECK-NEXT:    add r1,r2
; CHECK-NEXT:    mov.l @r2,r2
; CHECK-NEXT:    jsr @r2
; CHECK-NEXT:    nop
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp10:
; CHECK-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
; CHECK-NEXT:  .Ltmp11:
; CHECK-NEXT:    .ualong callee@GOT
  %r = call i32 @callee(i32 %x)
  ret i32 %r
}

define i32 @call_loc(i32 %x) {
; CHECK-LABEL: call_loc:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    mova .Ltmp12,r0
; CHECK-NEXT:    mov.l .Ltmp12,r1
; CHECK-NEXT:    add r0,r1
; CHECK-NEXT:    mov.l .Ltmp13,r2
; CHECK-NEXT:    add r1,r2
; CHECK-NEXT:    jsr @r2
; CHECK-NEXT:    nop
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp12:
; CHECK-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
; CHECK-NEXT:  .Ltmp13:
; CHECK-NEXT:    .ualong helper@GOTOFF
  %r = call i32 @helper(i32 %x)
  ret i32 %r
}

; The table of a switch has distances from itself.
define i32 @switch(i32 %x) {
; CHECK-LABEL: switch:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0: ! %entry
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    mova .Ltmp14,r0
; CHECK-NEXT:    mov.l .Ltmp14,r1
; CHECK-NEXT:    add r0,r1
; CHECK-NEXT:    mov #4,r2
; CHECK-NEXT:    cmp/hi r2,r4
; CHECK-NEXT:    bt .LBB7_8
; CHECK-NEXT:  ! %bb.1: ! %entry
; CHECK-NEXT:    mov.l .Ltmp15,r2
; CHECK-NEXT:    add r1,r2
; CHECK-NEXT:    shll2 r4
; CHECK-NEXT:    add r2,r4
; CHECK-NEXT:    mov.l @r4,r3
; CHECK-NEXT:    add r2,r3
; CHECK-NEXT:    jmp @r3
; CHECK-NEXT:    nop
; CHECK-NEXT:  .LBB7_2: ! %a
; CHECK-NEXT:    mov.l .Ltmp16,r2
; CHECK-NEXT:    add r2,r1
; CHECK-NEXT:    mov.l @r1,r2
; CHECK-NEXT:    bra .LBB7_3
; CHECK-NEXT:    mov #10,r4
; CHECK-NEXT:  .LBB7_7: ! %e
; CHECK-NEXT:    mov.l .Ltmp16,r2
; CHECK-NEXT:    add r2,r1
; CHECK-NEXT:    mov.l @r1,r2
; CHECK-NEXT:    bra .LBB7_3
; CHECK-NEXT:    mov #54,r4
; CHECK-NEXT:  .LBB7_5: ! %c
; CHECK-NEXT:    mov.l .Ltmp16,r2
; CHECK-NEXT:    add r2,r1
; CHECK-NEXT:    mov.l @r1,r2
; CHECK-NEXT:    bra .LBB7_3
; CHECK-NEXT:    mov #32,r4
; CHECK-NEXT:  .LBB7_6: ! %d
; CHECK-NEXT:    mov.l .Ltmp16,r2
; CHECK-NEXT:    add r2,r1
; CHECK-NEXT:    mov.l @r1,r2
; CHECK-NEXT:    bra .LBB7_3
; CHECK-NEXT:    mov #43,r4
; CHECK-NEXT:  .LBB7_4: ! %b
; CHECK-NEXT:    mov.l .Ltmp16,r2
; CHECK-NEXT:    add r2,r1
; CHECK-NEXT:    mov.l @r1,r2
; CHECK-NEXT:    mov #21,r4
; CHECK-NEXT:  .LBB7_3: ! %a
; CHECK-NEXT:    jsr @r2
; CHECK-NEXT:    nop
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:  .LBB7_8: ! %other
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    mov #0,r0
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.9:
; CHECK-NEXT:  .Ltmp14:
; CHECK-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
; CHECK-NEXT:  .Ltmp15:
; CHECK-NEXT:    .ualong .LJTI7_0@GOTOFF
; CHECK-NEXT:  .Ltmp16:
; CHECK-NEXT:    .ualong callee@GOT
entry:
  switch i32 %x, label %other [
    i32 0, label %a
    i32 1, label %b
    i32 2, label %c
    i32 3, label %d
    i32 4, label %e
  ]

a:
  %ra = call i32 @callee(i32 10)
  ret i32 %ra

b:
  %rb = call i32 @callee(i32 21)
  ret i32 %rb

c:
  %rc = call i32 @callee(i32 32)
  ret i32 %rc

d:
  %rd = call i32 @callee(i32 43)
  ret i32 %rd

e:
  %re = call i32 @callee(i32 54)
  ret i32 %re

other:
  ret i32 0
}

; CHECK-LABEL: .section .rodata
; CHECK: .LJTI7_0:
; CHECK-NEXT: .ualong .LBB7_2-.LJTI7_0
