; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4-nofpu -verify-machineinstrs < %s | FileCheck %s
; RUN: llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4-nofpu -relocation-model=pic -verify-machineinstrs < %s | FileCheck %s --check-prefix=PIC

; -pg: mcount is called in front of the prologue, as GCC calls it.  The
; return address of the function is on top of the stack, pr is the address
; to come back to.  mcount keeps r4 to r7 and nothing else, so the address
; of a result in memory (r2) and a static chain (r3) are put on the stack
; around the call.  The literals in the middle of the sequence are aligned,
; and what follows counts its distances with the size of all this.

%struct.big = type { [8 x i32] }
@g = external global i32

define i32 @leaf(i32 %x) "fentry-call"="true" {
; CHECK-LABEL: leaf:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.l .Ltmp0,r1
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    mova .Ltmp2,r0
; CHECK-NEXT:    jmp @r1
; CHECK-NEXT:    lds r0,pr
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  .Ltmp0:
; CHECK-NEXT:    .ualong mcount
; CHECK-NEXT:  .Ltmp2:
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    add #1,r0
;
; PIC-LABEL: leaf:
; PIC:         .cfi_startproc
; PIC-NEXT:  ! %bb.0:
; PIC-NEXT:    mov.l .Ltmp1,r1
; PIC-NEXT:    mova .Ltmp1,r0
; PIC-NEXT:    add r1,r0
; PIC-NEXT:    mov.l .Ltmp0,r1
; PIC-NEXT:    mov.l @(r0,r1),r1
; PIC-NEXT:    sts.l pr,@-r15
; PIC-NEXT:    mova .Ltmp2,r0
; PIC-NEXT:    jmp @r1
; PIC-NEXT:    lds r0,pr
; PIC-NEXT:    .p2align 2
; PIC-NEXT:  .Ltmp0:
; PIC-NEXT:    .ualong mcount@GOT
; PIC-NEXT:  .Ltmp1:
; PIC-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
; PIC-NEXT:  .Ltmp2:
; PIC-NEXT:    lds.l @r15+,pr
; PIC-NEXT:    mov r4,r0
; PIC-NEXT:    rts
; PIC-NEXT:    add #1,r0
  %r = add i32 %x, 1
  ret i32 %r
}

define void @result_in_memory(ptr sret(%struct.big) %out, i32 %x) "fentry-call"="true" {
; CHECK-LABEL: result_in_memory:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.l r2,@-r15
; CHECK-NEXT:    mov.l .Ltmp3,r1
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    mova .Ltmp5,r0
; CHECK-NEXT:    jmp @r1
; CHECK-NEXT:    lds r0,pr
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  .Ltmp3:
; CHECK-NEXT:    .ualong mcount
; CHECK-NEXT:  .Ltmp5:
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    mov.l @r15+,r2
; CHECK-NEXT:    mov r2,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    mov.l r4,@r0
;
; PIC-LABEL: result_in_memory:
; PIC:         .cfi_startproc
; PIC-NEXT:  ! %bb.0:
; PIC-NEXT:    mov.l r2,@-r15
; PIC-NEXT:    mov.l .Ltmp4,r1
; PIC-NEXT:    mova .Ltmp4,r0
; PIC-NEXT:    add r1,r0
; PIC-NEXT:    mov.l .Ltmp3,r1
; PIC-NEXT:    mov.l @(r0,r1),r1
; PIC-NEXT:    sts.l pr,@-r15
; PIC-NEXT:    mova .Ltmp5,r0
; PIC-NEXT:    jmp @r1
; PIC-NEXT:    lds r0,pr
; PIC-NEXT:    .p2align 2
; PIC-NEXT:  .Ltmp3:
; PIC-NEXT:    .ualong mcount@GOT
; PIC-NEXT:  .Ltmp4:
; PIC-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
; PIC-NEXT:  .Ltmp5:
; PIC-NEXT:    lds.l @r15+,pr
; PIC-NEXT:    mov.l @r15+,r2
; PIC-NEXT:    mov r2,r0
; PIC-NEXT:    rts
; PIC-NEXT:    mov.l r4,@r0
  store i32 %x, ptr %out
  ret void
}

define i32 @static_chain(ptr nest %chain, i32 %x) "fentry-call"="true" {
; CHECK-LABEL: static_chain:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.l r3,@-r15
; CHECK-NEXT:    mov.l .Ltmp6,r1
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    mova .Ltmp8,r0
; CHECK-NEXT:    jmp @r1
; CHECK-NEXT:    lds r0,pr
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  .Ltmp6:
; CHECK-NEXT:    .ualong mcount
; CHECK-NEXT:  .Ltmp8:
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    mov.l @r15+,r3
; CHECK-NEXT:    mov.l @r3,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    add r4,r0
;
; PIC-LABEL: static_chain:
; PIC:         .cfi_startproc
; PIC-NEXT:  ! %bb.0:
; PIC-NEXT:    mov.l r3,@-r15
; PIC-NEXT:    mov.l .Ltmp7,r1
; PIC-NEXT:    mova .Ltmp7,r0
; PIC-NEXT:    add r1,r0
; PIC-NEXT:    mov.l .Ltmp6,r1
; PIC-NEXT:    mov.l @(r0,r1),r1
; PIC-NEXT:    sts.l pr,@-r15
; PIC-NEXT:    mova .Ltmp8,r0
; PIC-NEXT:    jmp @r1
; PIC-NEXT:    lds r0,pr
; PIC-NEXT:    .p2align 2
; PIC-NEXT:  .Ltmp6:
; PIC-NEXT:    .ualong mcount@GOT
; PIC-NEXT:  .Ltmp7:
; PIC-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
; PIC-NEXT:  .Ltmp8:
; PIC-NEXT:    lds.l @r15+,pr
; PIC-NEXT:    mov.l @r15+,r3
; PIC-NEXT:    mov.l @r3,r0
; PIC-NEXT:    rts
; PIC-NEXT:    add r4,r0
  %v = load i32, ptr %chain
  %r = add i32 %v, %x
  ret i32 %r
}

; A literal behind the call of mcount is within reach of its load.
define i32 @with_literal() "fentry-call"="true" {
; CHECK-LABEL: with_literal:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.l .Ltmp11,r1
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    mova .Ltmp13,r0
; CHECK-NEXT:    jmp @r1
; CHECK-NEXT:    lds r0,pr
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  .Ltmp11:
; CHECK-NEXT:    .ualong mcount
; CHECK-NEXT:  .Ltmp13:
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    mov.l .Ltmp9,r1
; CHECK-NEXT:    mov.l @r1,r1
; CHECK-NEXT:    mov.l .Ltmp10,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    add r1,r0
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp9:
; CHECK-NEXT:    .ualong g
; CHECK-NEXT:  .Ltmp10:
; CHECK-NEXT:    .ualong 100000
;
; PIC-LABEL: with_literal:
; PIC:         .cfi_startproc
; PIC-NEXT:  ! %bb.0:
; PIC-NEXT:    mov.l .Ltmp13,r1
; PIC-NEXT:    mova .Ltmp13,r0
; PIC-NEXT:    add r1,r0
; PIC-NEXT:    mov.l .Ltmp12,r1
; PIC-NEXT:    mov.l @(r0,r1),r1
; PIC-NEXT:    sts.l pr,@-r15
; PIC-NEXT:    mova .Ltmp14,r0
; PIC-NEXT:    jmp @r1
; PIC-NEXT:    lds r0,pr
; PIC-NEXT:    .p2align 2
; PIC-NEXT:  .Ltmp12:
; PIC-NEXT:    .ualong mcount@GOT
; PIC-NEXT:  .Ltmp13:
; PIC-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
; PIC-NEXT:  .Ltmp14:
; PIC-NEXT:    lds.l @r15+,pr
; PIC-NEXT:    mova .Ltmp9,r0
; PIC-NEXT:    mov.l .Ltmp9,r1
; PIC-NEXT:    add r0,r1
; PIC-NEXT:    mov.l .Ltmp10,r2
; PIC-NEXT:    add r1,r2
; PIC-NEXT:    mov.l @r2,r1
; PIC-NEXT:    mov.l @r1,r1
; PIC-NEXT:    mov.l .Ltmp11,r0
; PIC-NEXT:    rts
; PIC-NEXT:    add r1,r0
; PIC-NEXT:    .p2align 2
; PIC-NEXT:  ! %bb.1:
; PIC-NEXT:  .Ltmp9:
; PIC-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
; PIC-NEXT:  .Ltmp10:
; PIC-NEXT:    .ualong g@GOT
; PIC-NEXT:  .Ltmp11:
; PIC-NEXT:    .ualong 100000
  %v = load i32, ptr @g
  %r = add i32 %v, 100000
  ret i32 %r
}
