; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4-nofpu -verify-machineinstrs < %s | FileCheck %s

; What only r0 can do: a comparison with an immediate, a test of bits
; against an immediate, and a byte or a word at a displacement from a
; register.  The value is copied to r0, or from it, where it is not there
; anyway.

declare i32 @callee(i32)

define i32 @equal(i32 %x, i32 %a, i32 %b) {
; CHECK-LABEL: equal:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    cmp/eq #5,r0
; CHECK-NEXT:    bt .LBB0_2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:    mov r6,r5
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    rts
; CHECK-NEXT:    mov r5,r0
  %c = icmp eq i32 %x, 5
  %r = select i1 %c, i32 %a, i32 %b
  ret i32 %r
}

define i32 @bits(i32 %x, i32 %a, i32 %b) {
; CHECK-LABEL: bits:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    tst #200,r0
; CHECK-NEXT:    bt .LBB1_2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:    mov r6,r5
; CHECK-NEXT:  .LBB1_2:
; CHECK-NEXT:    rts
; CHECK-NEXT:    mov r5,r0
  %m = and i32 %x, 200
  %c = icmp eq i32 %m, 0
  %r = select i1 %c, i32 %a, i32 %b
  ret i32 %r
}

; The result of a call is in r0.
define i32 @result(i32 %x) {
; CHECK-LABEL: result:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    mov.l .Ltmp0,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    nop
; CHECK-NEXT:    cmp/eq #-7,r0
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    movt r0
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp0:
; CHECK-NEXT:    .ualong callee
  %v = call i32 @callee(i32 %x)
  %c = icmp eq i32 %v, -7
  %r = zext i1 %c to i32
  ret i32 %r
}

; 300 is not an immediate.
define i32 @wide(i32 %x) {
; CHECK-LABEL: wide:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov #75,r1
; CHECK-NEXT:    shll2 r1
; CHECK-NEXT:    cmp/eq r1,r4
; CHECK-NEXT:    rts
; CHECK-NEXT:    movt r0
  %c = icmp eq i32 %x, 300
  %r = zext i1 %c to i32
  ret i32 %r
}

%struct.s = type { i32, i8, i8, i16, i16, [20 x i8], i16 }

define i32 @load_byte(ptr %p) {
; CHECK-LABEL: load_byte:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    rts
; CHECK-NEXT:    mov.b @(4,r4),r0
  %q = getelementptr %struct.s, ptr %p, i32 0, i32 1
  %v = load i8, ptr %q
  %r = sext i8 %v to i32
  ret i32 %r
}

define i32 @load_unsigned_byte(ptr %p) {
; CHECK-LABEL: load_unsigned_byte:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.b @(5,r4),r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    extu.b r0,r0
  %q = getelementptr %struct.s, ptr %p, i32 0, i32 2
  %v = load i8, ptr %q
  %r = zext i8 %v to i32
  ret i32 %r
}

define i32 @load_word(ptr %p) {
; CHECK-LABEL: load_word:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    rts
; CHECK-NEXT:    mov.w @(6,r4),r0
  %q = getelementptr %struct.s, ptr %p, i32 0, i32 3
  %v = load i16, ptr %q
  %r = sext i16 %v to i32
  ret i32 %r
}

define void @store_byte(ptr %p, i32 %v) {
; CHECK-LABEL: store_byte:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r5,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    mov.b r0,@(4,r4)
  %q = getelementptr %struct.s, ptr %p, i32 0, i32 1
  %t = trunc i32 %v to i8
  store i8 %t, ptr %q
  ret void
}

define void @store_word(ptr %p, i32 %v) {
; CHECK-LABEL: store_word:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r5,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    mov.w r0,@(8,r4)
  %q = getelementptr %struct.s, ptr %p, i32 0, i32 4
  %t = trunc i32 %v to i16
  store i16 %t, ptr %q
  ret void
}

; A displacement has four bits: 30 is the last one for a word, 32 is not.
define i32 @last(ptr %p) {
; CHECK-LABEL: last:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    rts
; CHECK-NEXT:    mov.w @(30,r4),r0
  %q = getelementptr i8, ptr %p, i32 30
  %v = load i16, ptr %q
  %r = sext i16 %v to i32
  ret i32 %r
}

define i32 @beyond(ptr %p) {
; CHECK-LABEL: beyond:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    add #32,r4
; CHECK-NEXT:    rts
; CHECK-NEXT:    mov.w @r4,r0
  %q = getelementptr i8, ptr %p, i32 32
  %v = load i16, ptr %q
  %r = sext i16 %v to i32
  ret i32 %r
}

; r0 is taken by the first value while the second is loaded.
define i32 @both(ptr %p) {
; CHECK-LABEL: both:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.w @(6,r4),r0
; CHECK-NEXT:    mov r0,r1
; CHECK-NEXT:    mov.b @(4,r4),r0
; CHECK-NEXT:    mul.l r1,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    sts macl,r0
  %q1 = getelementptr %struct.s, ptr %p, i32 0, i32 1
  %q2 = getelementptr %struct.s, ptr %p, i32 0, i32 3
  %a = load i8, ptr %q1
  %b = load i16, ptr %q2
  %x = sext i8 %a to i32
  %y = sext i16 %b to i32
  %r = mul i32 %x, %y
  ret i32 %r
}
