; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=sh2-unknown-linux-gnu -verify-machineinstrs < %s | FileCheck %s

; The SH-2 has no shad and shld.  A shift by a constant is a row of the
; shifts by sixteen, eight, two and one, and a shift by a variable amount is
; a function of libgcc.

define i32 @shl24(i32 %a) {
; CHECK-LABEL: shl24:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    shll16 r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    shll8 r0
  %r = shl i32 %a, 24
  ret i32 %r
}

define i32 @shl5(i32 %a) {
; CHECK-LABEL: shl5:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    shll2 r0
; CHECK-NEXT:    shll2 r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    add r0,r0
  %r = shl i32 %a, 5
  ret i32 %r
}

define i32 @lshr11(i32 %a) {
; CHECK-LABEL: lshr11:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    shlr8 r0
; CHECK-NEXT:    shlr2 r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    shlr r0
  %r = lshr i32 %a, 11
  ret i32 %r
}

; Only shar shifts to the right with the sign, by one bit.
define i32 @ashr3(i32 %a) {
; CHECK-LABEL: ashr3:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    shar r0
; CHECK-NEXT:    shar r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    shar r0
  %r = ashr i32 %a, 3
  ret i32 %r
}

define i32 @ashr20(i32 %a) {
; CHECK-LABEL: ashr20:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    mov.l .Ltmp0,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    mov #20,r5
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp0:
; CHECK-NEXT:    .ualong __ashrsi3
  %r = ashr i32 %a, 20
  ret i32 %r
}

define i32 @shl_var(i32 %a, i32 %n) {
; CHECK-LABEL: shl_var:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    mov.l .Ltmp1,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    nop
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp1:
; CHECK-NEXT:    .ualong __ashlsi3
  %r = shl i32 %a, %n
  ret i32 %r
}

define i32 @lshr_var(i32 %a, i32 %n) {
; CHECK-LABEL: lshr_var:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    mov.l .Ltmp2,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    nop
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp2:
; CHECK-NEXT:    .ualong __lshrsi3
  %r = lshr i32 %a, %n
  ret i32 %r
}

define i32 @ashr_var(i32 %a, i32 %n) {
; CHECK-LABEL: ashr_var:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    mov.l .Ltmp3,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    nop
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp3:
; CHECK-NEXT:    .ualong __ashrsi3
  %r = ashr i32 %a, %n
  ret i32 %r
}
