; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4-nofpu -verify-machineinstrs < %s | FileCheck %s

; By one, two, eight and sixteen bits there are instructions.

define i32 @shl1(i32 %a) {
; CHECK-LABEL: shl1:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    add r0,r0
  %r = shl i32 %a, 1
  ret i32 %r
}

define i32 @shl2(i32 %a) {
; CHECK-LABEL: shl2:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    shll2 r0
  %r = shl i32 %a, 2
  ret i32 %r
}

define i32 @shl8(i32 %a) {
; CHECK-LABEL: shl8:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    shll8 r0
  %r = shl i32 %a, 8
  ret i32 %r
}

define i32 @shl16(i32 %a) {
; CHECK-LABEL: shl16:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    shll16 r0
  %r = shl i32 %a, 16
  ret i32 %r
}

define i32 @lshr1(i32 %a) {
; CHECK-LABEL: lshr1:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    shlr r0
  %r = lshr i32 %a, 1
  ret i32 %r
}

define i32 @lshr2(i32 %a) {
; CHECK-LABEL: lshr2:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    shlr2 r0
  %r = lshr i32 %a, 2
  ret i32 %r
}

define i32 @ashr1(i32 %a) {
; CHECK-LABEL: ashr1:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    shar r0
  %r = ashr i32 %a, 1
  ret i32 %r
}

; Anything else is shad or shld, which shift to the right by a negative
; amount.

define i32 @shl5(i32 %a) {
; CHECK-LABEL: shl5:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    mov #5,r1
; CHECK-NEXT:    rts
; CHECK-NEXT:    shld r1,r0
  %r = shl i32 %a, 5
  ret i32 %r
}

define i32 @lshr5(i32 %a) {
; CHECK-LABEL: lshr5:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    mov #-5,r1
; CHECK-NEXT:    rts
; CHECK-NEXT:    shld r1,r0
  %r = lshr i32 %a, 5
  ret i32 %r
}

define i32 @ashr5(i32 %a) {
; CHECK-LABEL: ashr5:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    mov #-5,r1
; CHECK-NEXT:    rts
; CHECK-NEXT:    shad r1,r0
  %r = ashr i32 %a, 5
  ret i32 %r
}

define i32 @shl_var(i32 %a, i32 %n) {
; CHECK-LABEL: shl_var:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    rts
; CHECK-NEXT:    shld r5,r0
  %r = shl i32 %a, %n
  ret i32 %r
}

define i32 @lshr_var(i32 %a, i32 %n) {
; CHECK-LABEL: lshr_var:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    neg r5,r1
; CHECK-NEXT:    rts
; CHECK-NEXT:    shld r1,r0
  %r = lshr i32 %a, %n
  ret i32 %r
}

define i32 @ashr_var(i32 %a, i32 %n) {
; CHECK-LABEL: ashr_var:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    neg r5,r1
; CHECK-NEXT:    rts
; CHECK-NEXT:    shad r1,r0
  %r = ashr i32 %a, %n
  ret i32 %r
}

define i32 @rot16(i32 %a) {
; CHECK-LABEL: rot16:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r0
; CHECK-NEXT:    shlr16 r0
; CHECK-NEXT:    shll16 r4
; CHECK-NEXT:    rts
; CHECK-NEXT:    or r4,r0
  %r = call i32 @llvm.fshl.i32(i32 %a, i32 %a, i32 16)
  ret i32 %r
}

define i64 @shl64(i64 %a, i32 %n) {
; CHECK-LABEL: shl64:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    mov.l .Ltmp0,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    nop
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp0:
; CHECK-NEXT:    .ualong __ashldi3
  %s = zext i32 %n to i64
  %r = shl i64 %a, %s
  ret i64 %r
}

declare i32 @llvm.fshl.i32(i32, i32, i32)
