; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4-nofpu -verify-machineinstrs < %s | FileCheck %s
; RUN: llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4-nofpu -relocation-model=pic -verify-machineinstrs < %s | FileCheck %s --check-prefix=PIC

; A call in tail position is a jump behind the epilogue: "jmp @Rn" with the
; address in r0, r1 or r3, which the epilogue leaves alone and which carry
; no argument.  Position independent code jumps over a distance to a
; function of the module ("braf") and takes the address of any other from
; the global offset table: r12, which the procedure linkage table wants, is
; a register that the epilogue restores.

declare i32 @ext(i32)
declare void @ext4(i32, i32, i32, i32)
declare void @ext5(i32, i32, i32, i32, i32)
declare void @sink(ptr)
%struct.big = type { [8 x i32] }
declare void @ret_big(ptr sret(%struct.big))

define internal i32 @local(i32 %x) noinline {
; CHECK-LABEL: local:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov #3,r1
; CHECK-NEXT:    mul.l r1,r4
; CHECK-NEXT:    rts
; CHECK-NEXT:    sts macl,r0
;
; PIC-LABEL: local:
; PIC:         .cfi_startproc
; PIC-NEXT:  ! %bb.0:
; PIC-NEXT:    mov #3,r1
; PIC-NEXT:    mul.l r1,r4
; PIC-NEXT:    rts
; PIC-NEXT:    sts macl,r0
  %r = mul i32 %x, 3
  ret i32 %r
}

define i32 @tail_ext(i32 %x) {
; CHECK-LABEL: tail_ext:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.l .Ltmp0,r1
; CHECK-NEXT:    jmp @r1
; CHECK-NEXT:    add #1,r4
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp0:
; CHECK-NEXT:    .ualong ext
;
; PIC-LABEL: tail_ext:
; PIC:         .cfi_startproc
; PIC-NEXT:  ! %bb.0:
; PIC-NEXT:    mova .Ltmp0,r0
; PIC-NEXT:    mov.l .Ltmp0,r1
; PIC-NEXT:    add r0,r1
; PIC-NEXT:    mov.l .Ltmp1,r2
; PIC-NEXT:    add r1,r2
; PIC-NEXT:    mov.l @r2,r1
; PIC-NEXT:    jmp @r1
; PIC-NEXT:    add #1,r4
; PIC-NEXT:    .p2align 2
; PIC-NEXT:  ! %bb.1:
; PIC-NEXT:  .Ltmp0:
; PIC-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
; PIC-NEXT:  .Ltmp1:
; PIC-NEXT:    .ualong ext@GOT
  %a = add i32 %x, 1
  %r = tail call i32 @ext(i32 %a)
  ret i32 %r
}

define i32 @tail_local(i32 %x) {
; CHECK-LABEL: tail_local:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.l .Ltmp1,r1
; CHECK-NEXT:    jmp @r1
; CHECK-NEXT:    add #1,r4
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp1:
; CHECK-NEXT:    .ualong local
;
; PIC-LABEL: tail_local:
; PIC:         .cfi_startproc
; PIC-NEXT:  ! %bb.0:
; PIC-NEXT:    mov.l .Ltmp3,r1
; PIC-NEXT:    braf r1
; PIC-NEXT:  .Ltmp2:
; PIC-NEXT:    add #1,r4
; PIC-NEXT:    .p2align 2
; PIC-NEXT:  ! %bb.1:
; PIC-NEXT:  .Ltmp3:
; PIC-NEXT:    .ualong local-(.Ltmp2+2)
  %a = add i32 %x, 1
  %r = tail call i32 @local(i32 %a)
  ret i32 %r
}

define i32 @tail_pointer(ptr %f, i32 %x) {
; CHECK-LABEL: tail_pointer:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r1
; CHECK-NEXT:    add #1,r5
; CHECK-NEXT:    jmp @r1
; CHECK-NEXT:    mov r5,r4
;
; PIC-LABEL: tail_pointer:
; PIC:         .cfi_startproc
; PIC-NEXT:  ! %bb.0:
; PIC-NEXT:    mov r4,r1
; PIC-NEXT:    add #1,r5
; PIC-NEXT:    jmp @r1
; PIC-NEXT:    mov r5,r4
  %a = add i32 %x, 1
  %r = tail call i32 %f(i32 %a)
  ret i32 %r
}

; All four argument registers are in use: the address is in none of them.
define void @tail_four(ptr %f, i32 %a, i32 %b, i32 %c) {
; CHECK-LABEL: tail_four:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov r4,r1
; CHECK-NEXT:    mov r5,r4
; CHECK-NEXT:    mov r6,r5
; CHECK-NEXT:    mov r7,r6
; CHECK-NEXT:    jmp @r1
; CHECK-NEXT:    mov #7,r7
;
; PIC-LABEL: tail_four:
; PIC:         .cfi_startproc
; PIC-NEXT:  ! %bb.0:
; PIC-NEXT:    mov r4,r1
; PIC-NEXT:    mov r5,r4
; PIC-NEXT:    mov r6,r5
; PIC-NEXT:    mov r7,r6
; PIC-NEXT:    jmp @r1
; PIC-NEXT:    mov #7,r7
  tail call void %f(i32 %a, i32 %b, i32 %c, i32 7)
  ret void
}

; The epilogue restores registers and pr in front of the jump, and the last
; of that goes into its delay slot.
define i32 @tail_frame(i32 %x) {
; CHECK-LABEL: tail_frame:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.l r8,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset r8, -4
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    .cfi_offset pr, -8
; CHECK-NEXT:    mov.l .Ltmp2,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    mov r4,r8
; CHECK-NEXT:    add r0,r8
; CHECK-NEXT:    mov r8,r4
; CHECK-NEXT:    mov.l .Ltmp2,r1
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    jmp @r1
; CHECK-NEXT:    mov.l @r15+,r8
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp2:
; CHECK-NEXT:    .ualong ext
;
; PIC-LABEL: tail_frame:
; PIC:         .cfi_startproc
; PIC-NEXT:  ! %bb.0:
; PIC-NEXT:    mov.l r8,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 4
; PIC-NEXT:    .cfi_offset r8, -4
; PIC-NEXT:    mov.l r12,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 8
; PIC-NEXT:    .cfi_offset r12, -8
; PIC-NEXT:    sts.l pr,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 12
; PIC-NEXT:    .cfi_offset pr, -12
; PIC-NEXT:    mova .Ltmp5,r0
; PIC-NEXT:    mov.l .Ltmp5,r12
; PIC-NEXT:    add r0,r12
; PIC-NEXT:    mov.l .Ltmp6,r1
; PIC-NEXT:    bsrf r1
; PIC-NEXT:  .Ltmp4:
; PIC-NEXT:    mov r4,r8
; PIC-NEXT:    add r0,r8
; PIC-NEXT:    mov.l .Ltmp7,r1
; PIC-NEXT:    add r12,r1
; PIC-NEXT:    mov.l @r1,r1
; PIC-NEXT:    mov r8,r4
; PIC-NEXT:    lds.l @r15+,pr
; PIC-NEXT:    mov.l @r15+,r12
; PIC-NEXT:    jmp @r1
; PIC-NEXT:    mov.l @r15+,r8
; PIC-NEXT:    .p2align 2
; PIC-NEXT:  ! %bb.1:
; PIC-NEXT:  .Ltmp5:
; PIC-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
; PIC-NEXT:  .Ltmp6:
; PIC-NEXT:    .ualong ext@PLT-(.Ltmp4+2-.Ltmp6)
; PIC-NEXT:  .Ltmp7:
; PIC-NEXT:    .ualong ext@GOT
  %a = call i32 @ext(i32 %x)
  %b = add i32 %a, %x
  %r = tail call i32 @ext(i32 %b)
  ret i32 %r
}

; A frame that is too large for an immediate: the epilogue computes in r2,
; not in r7, which may carry an argument here.
define void @tail_large(i32 %a, i32 %b, i32 %c, i32 %d) {
; CHECK-LABEL: tail_large:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.l r8,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset r8, -4
; CHECK-NEXT:    mov.l r9,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    .cfi_offset r9, -8
; CHECK-NEXT:    mov.l r10,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 12
; CHECK-NEXT:    .cfi_offset r10, -12
; CHECK-NEXT:    mov.l r11,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset r11, -16
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 20
; CHECK-NEXT:    .cfi_offset pr, -20
; CHECK-NEXT:    mov.l .Ltmp3,r1
; CHECK-NEXT:    add r1,r15
; CHECK-NEXT:    .cfi_def_cfa_offset 620
; CHECK-NEXT:    mov r7,r8
; CHECK-NEXT:    mov r6,r9
; CHECK-NEXT:    mov r5,r10
; CHECK-NEXT:    mov r4,r11
; CHECK-NEXT:    mov.l .Ltmp4,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    mov r15,r4
; CHECK-NEXT:    mov.l .Ltmp5,r1
; CHECK-NEXT:    mov r11,r4
; CHECK-NEXT:    mov r10,r5
; CHECK-NEXT:    mov r9,r6
; CHECK-NEXT:    mov r8,r7
; CHECK-NEXT:    mov.l .Ltmp6,r2
; CHECK-NEXT:    add r2,r15
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    mov.l @r15+,r11
; CHECK-NEXT:    mov.l @r15+,r10
; CHECK-NEXT:    mov.l @r15+,r9
; CHECK-NEXT:    jmp @r1
; CHECK-NEXT:    mov.l @r15+,r8
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp3:
; CHECK-NEXT:    .ualong 4294966696
; CHECK-NEXT:  .Ltmp4:
; CHECK-NEXT:    .ualong sink
; CHECK-NEXT:  .Ltmp5:
; CHECK-NEXT:    .ualong ext4
; CHECK-NEXT:  .Ltmp6:
; CHECK-NEXT:    .ualong 600
;
; PIC-LABEL: tail_large:
; PIC:         .cfi_startproc
; PIC-NEXT:  ! %bb.0:
; PIC-NEXT:    mov.l r8,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 4
; PIC-NEXT:    .cfi_offset r8, -4
; PIC-NEXT:    mov.l r9,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 8
; PIC-NEXT:    .cfi_offset r9, -8
; PIC-NEXT:    mov.l r10,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 12
; PIC-NEXT:    .cfi_offset r10, -12
; PIC-NEXT:    mov.l r11,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 16
; PIC-NEXT:    .cfi_offset r11, -16
; PIC-NEXT:    mov.l r12,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 20
; PIC-NEXT:    .cfi_offset r12, -20
; PIC-NEXT:    sts.l pr,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 24
; PIC-NEXT:    .cfi_offset pr, -24
; PIC-NEXT:    mov.l .Ltmp9,r1
; PIC-NEXT:    add r1,r15
; PIC-NEXT:    .cfi_def_cfa_offset 624
; PIC-NEXT:    mova .Ltmp10,r0
; PIC-NEXT:    mov.l .Ltmp10,r12
; PIC-NEXT:    add r0,r12
; PIC-NEXT:    mov r7,r8
; PIC-NEXT:    mov r6,r9
; PIC-NEXT:    mov r5,r10
; PIC-NEXT:    mov r4,r11
; PIC-NEXT:    mov.l .Ltmp11,r1
; PIC-NEXT:    bsrf r1
; PIC-NEXT:  .Ltmp8:
; PIC-NEXT:    mov r15,r4
; PIC-NEXT:    mov.l .Ltmp12,r1
; PIC-NEXT:    add r12,r1
; PIC-NEXT:    mov.l @r1,r1
; PIC-NEXT:    mov r11,r4
; PIC-NEXT:    mov r10,r5
; PIC-NEXT:    mov r9,r6
; PIC-NEXT:    mov r8,r7
; PIC-NEXT:    mov.l .Ltmp13,r2
; PIC-NEXT:    add r2,r15
; PIC-NEXT:    lds.l @r15+,pr
; PIC-NEXT:    mov.l @r15+,r12
; PIC-NEXT:    mov.l @r15+,r11
; PIC-NEXT:    mov.l @r15+,r10
; PIC-NEXT:    mov.l @r15+,r9
; PIC-NEXT:    jmp @r1
; PIC-NEXT:    mov.l @r15+,r8
; PIC-NEXT:    .p2align 2
; PIC-NEXT:  ! %bb.1:
; PIC-NEXT:  .Ltmp9:
; PIC-NEXT:    .ualong 4294966696
; PIC-NEXT:  .Ltmp10:
; PIC-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
; PIC-NEXT:  .Ltmp11:
; PIC-NEXT:    .ualong sink@PLT-(.Ltmp8+2-.Ltmp11)
; PIC-NEXT:  .Ltmp12:
; PIC-NEXT:    .ualong ext4@GOT
; PIC-NEXT:  .Ltmp13:
; PIC-NEXT:    .ualong 600
  %buf = alloca [600 x i8]
  call void @sink(ptr %buf)
  tail call void @ext4(i32 %a, i32 %b, i32 %c, i32 %d)
  ret void
}

; No tail call: an argument on the stack ...
define void @no_stack(i32 %a) {
; CHECK-LABEL: no_stack:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    add #-4,r15
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    mov.l r4,@r15
; CHECK-NEXT:    mov.l .Ltmp7,r1
; CHECK-NEXT:    mov r4,r5
; CHECK-NEXT:    mov r4,r6
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    mov r4,r7
; CHECK-NEXT:    add #4,r15
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp7:
; CHECK-NEXT:    .ualong ext5
;
; PIC-LABEL: no_stack:
; PIC:         .cfi_startproc
; PIC-NEXT:  ! %bb.0:
; PIC-NEXT:    mov.l r12,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 4
; PIC-NEXT:    .cfi_offset r12, -4
; PIC-NEXT:    sts.l pr,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 8
; PIC-NEXT:    .cfi_offset pr, -8
; PIC-NEXT:    add #-4,r15
; PIC-NEXT:    .cfi_def_cfa_offset 12
; PIC-NEXT:    mova .Ltmp15,r0
; PIC-NEXT:    mov.l .Ltmp15,r12
; PIC-NEXT:    add r0,r12
; PIC-NEXT:    mov.l r4,@r15
; PIC-NEXT:    mov.l .Ltmp16,r1
; PIC-NEXT:    mov r4,r5
; PIC-NEXT:    mov r4,r6
; PIC-NEXT:    bsrf r1
; PIC-NEXT:  .Ltmp14:
; PIC-NEXT:    mov r4,r7
; PIC-NEXT:    add #4,r15
; PIC-NEXT:    lds.l @r15+,pr
; PIC-NEXT:    rts
; PIC-NEXT:    mov.l @r15+,r12
; PIC-NEXT:    .p2align 2
; PIC-NEXT:  ! %bb.1:
; PIC-NEXT:  .Ltmp15:
; PIC-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
; PIC-NEXT:  .Ltmp16:
; PIC-NEXT:    .ualong ext5@PLT-(.Ltmp14+2-.Ltmp16)
  tail call void @ext5(i32 %a, i32 %a, i32 %a, i32 %a, i32 %a)
  ret void
}

; ... a result in memory, whose address this function returns in r0 ...
define void @no_sret(ptr sret(%struct.big) %out) {
; CHECK-LABEL: no_sret:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov.l r8,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset r8, -4
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    .cfi_offset pr, -8
; CHECK-NEXT:    mov.l .Ltmp8,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    mov r2,r8
; CHECK-NEXT:    mov r8,r0
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    mov.l @r15+,r8
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp8:
; CHECK-NEXT:    .ualong ret_big
;
; PIC-LABEL: no_sret:
; PIC:         .cfi_startproc
; PIC-NEXT:  ! %bb.0:
; PIC-NEXT:    mov.l r8,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 4
; PIC-NEXT:    .cfi_offset r8, -4
; PIC-NEXT:    mov.l r12,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 8
; PIC-NEXT:    .cfi_offset r12, -8
; PIC-NEXT:    sts.l pr,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 12
; PIC-NEXT:    .cfi_offset pr, -12
; PIC-NEXT:    mova .Ltmp18,r0
; PIC-NEXT:    mov.l .Ltmp18,r12
; PIC-NEXT:    add r0,r12
; PIC-NEXT:    mov.l .Ltmp19,r1
; PIC-NEXT:    bsrf r1
; PIC-NEXT:  .Ltmp17:
; PIC-NEXT:    mov r2,r8
; PIC-NEXT:    mov r8,r0
; PIC-NEXT:    lds.l @r15+,pr
; PIC-NEXT:    mov.l @r15+,r12
; PIC-NEXT:    rts
; PIC-NEXT:    mov.l @r15+,r8
; PIC-NEXT:    .p2align 2
; PIC-NEXT:  ! %bb.1:
; PIC-NEXT:  .Ltmp18:
; PIC-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
; PIC-NEXT:  .Ltmp19:
; PIC-NEXT:    .ualong ret_big@PLT-(.Ltmp17+2-.Ltmp19)
  tail call void @ret_big(ptr sret(%struct.big) %out)
  ret void
}

; ... and a function with variable arguments.
define i32 @no_varargs(i32 %x, ...) {
; CHECK-LABEL: no_varargs:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    add #-12,r15
; CHECK-NEXT:    .cfi_def_cfa_offset 12
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset pr, -16
; CHECK-NEXT:    mov.l r5,@(4,r15)
; CHECK-NEXT:    mov.l r6,@(8,r15)
; CHECK-NEXT:    mov.l r7,@(12,r15)
; CHECK-NEXT:    mov.l .Ltmp9,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    nop
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    add #12,r15
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp9:
; CHECK-NEXT:    .ualong ext
;
; PIC-LABEL: no_varargs:
; PIC:         .cfi_startproc
; PIC-NEXT:  ! %bb.0:
; PIC-NEXT:    add #-12,r15
; PIC-NEXT:    .cfi_def_cfa_offset 12
; PIC-NEXT:    mov.l r12,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 16
; PIC-NEXT:    .cfi_offset r12, -16
; PIC-NEXT:    sts.l pr,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 20
; PIC-NEXT:    .cfi_offset pr, -20
; PIC-NEXT:    mova .Ltmp21,r0
; PIC-NEXT:    mov.l .Ltmp21,r12
; PIC-NEXT:    add r0,r12
; PIC-NEXT:    mov.l r5,@(8,r15)
; PIC-NEXT:    mov.l r6,@(12,r15)
; PIC-NEXT:    mov.l r7,@(16,r15)
; PIC-NEXT:    mov.l .Ltmp22,r1
; PIC-NEXT:    bsrf r1
; PIC-NEXT:  .Ltmp20:
; PIC-NEXT:    nop
; PIC-NEXT:    lds.l @r15+,pr
; PIC-NEXT:    mov.l @r15+,r12
; PIC-NEXT:    rts
; PIC-NEXT:    add #12,r15
; PIC-NEXT:    .p2align 2
; PIC-NEXT:  ! %bb.1:
; PIC-NEXT:  .Ltmp21:
; PIC-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
; PIC-NEXT:  .Ltmp22:
; PIC-NEXT:    .ualong ext@PLT-(.Ltmp20+2-.Ltmp22)
  %r = tail call i32 @ext(i32 %x)
  ret i32 %r
}
