; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4-nofpu -verify-machineinstrs < %s | FileCheck %s --check-prefix=EXEC
; RUN: llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4-nofpu -relocation-model=pic -verify-machineinstrs < %s | FileCheck %s --check-prefix=PIC

; A variable that every thread has its own copy of.  gbr is the thread
; pointer.  In a program the copy is at a distance from it that the linker
; knows (@TPOFF), or that the loader writes into the global offset table if
; the variable belongs to a library (@GOTTPOFF).  Position independent code
; asks __tls_get_addr() for the address (@TLSGD), or for the start of the
; module's variables (@TLSLDM) if the variable is its own.
;
; The sequences with @GOTTPOFF, @TLSGD and @TLSLDM are the ones of GCC to
; the letter, with the table's address in r12 and the literals in the code:
; the linker rewrites them where it can do with less.

@other = external thread_local global i32
@mine = thread_local global i32 3
@hidden = internal thread_local global i32 0
@array = external thread_local global [8 x i32]

define i32 @load_other() {
; EXEC-LABEL: load_other:
; EXEC:         .cfi_startproc
; EXEC-NEXT:  ! %bb.0:
; EXEC-NEXT:    mov.l r12,@-r15
; EXEC-NEXT:    .cfi_def_cfa_offset 4
; EXEC-NEXT:    .cfi_offset r12, -4
; EXEC-NEXT:    mova .Ltmp0,r0
; EXEC-NEXT:    mov.l .Ltmp0,r12
; EXEC-NEXT:    add r0,r12
; EXEC-NEXT:    mov.l .Ltmp1,r0
; EXEC-NEXT:    stc gbr,r1
; EXEC-NEXT:    mov.l @(r0,r12),r0
; EXEC-NEXT:    bra .Ltmp2
; EXEC-NEXT:    add r0,r1
; EXEC-NEXT:    .p2align 2
; EXEC-NEXT:  .Ltmp1:
; EXEC-NEXT:    .ualong other@GOTTPOFF
; EXEC-NEXT:  .Ltmp2:
; EXEC-NEXT:    mov.l @r1,r0
; EXEC-NEXT:    rts
; EXEC-NEXT:    mov.l @r15+,r12
; EXEC-NEXT:    .p2align 2
; EXEC-NEXT:  ! %bb.1:
; EXEC-NEXT:  .Ltmp0:
; EXEC-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
;
; PIC-LABEL: load_other:
; PIC:         .cfi_startproc
; PIC-NEXT:  ! %bb.0:
; PIC-NEXT:    mov.l r12,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 4
; PIC-NEXT:    .cfi_offset r12, -4
; PIC-NEXT:    sts.l pr,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 8
; PIC-NEXT:    .cfi_offset pr, -8
; PIC-NEXT:    mova .Ltmp0,r0
; PIC-NEXT:    mov.l .Ltmp0,r12
; PIC-NEXT:    add r0,r12
; PIC-NEXT:    mov.l .Ltmp1,r4
; PIC-NEXT:    mova .Ltmp2,r0
; PIC-NEXT:    mov.l .Ltmp2,r1
; PIC-NEXT:    add r0,r1
; PIC-NEXT:    jsr @r1
; PIC-NEXT:    add r12,r4
; PIC-NEXT:    bra .Ltmp3
; PIC-NEXT:    nop
; PIC-NEXT:    .p2align 2
; PIC-NEXT:  .Ltmp1:
; PIC-NEXT:    .ualong other@TLSGD
; PIC-NEXT:  .Ltmp2:
; PIC-NEXT:    .ualong __tls_get_addr@PLT
; PIC-NEXT:  .Ltmp3:
; PIC-NEXT:    mov.l @r0,r0
; PIC-NEXT:    lds.l @r15+,pr
; PIC-NEXT:    rts
; PIC-NEXT:    mov.l @r15+,r12
; PIC-NEXT:    .p2align 2
; PIC-NEXT:  ! %bb.1:
; PIC-NEXT:  .Ltmp0:
; PIC-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
  %v = load i32, ptr @other
  ret i32 %v
}

define i32 @load_mine() {
; EXEC-LABEL: load_mine:
; EXEC:         .cfi_startproc
; EXEC-NEXT:  ! %bb.0:
; EXEC-NEXT:    mov.l r12,@-r15
; EXEC-NEXT:    .cfi_def_cfa_offset 4
; EXEC-NEXT:    .cfi_offset r12, -4
; EXEC-NEXT:    mova .Ltmp3,r0
; EXEC-NEXT:    mov.l .Ltmp3,r12
; EXEC-NEXT:    add r0,r12
; EXEC-NEXT:    mov.l .Ltmp4,r0
; EXEC-NEXT:    stc gbr,r1
; EXEC-NEXT:    mov.l @(r0,r12),r0
; EXEC-NEXT:    bra .Ltmp5
; EXEC-NEXT:    add r0,r1
; EXEC-NEXT:    .p2align 2
; EXEC-NEXT:  .Ltmp4:
; EXEC-NEXT:    .ualong mine@GOTTPOFF
; EXEC-NEXT:  .Ltmp5:
; EXEC-NEXT:    mov.l @r1,r0
; EXEC-NEXT:    rts
; EXEC-NEXT:    mov.l @r15+,r12
; EXEC-NEXT:    .p2align 2
; EXEC-NEXT:  ! %bb.1:
; EXEC-NEXT:  .Ltmp3:
; EXEC-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
;
; PIC-LABEL: load_mine:
; PIC:         .cfi_startproc
; PIC-NEXT:  ! %bb.0:
; PIC-NEXT:    mov.l r12,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 4
; PIC-NEXT:    .cfi_offset r12, -4
; PIC-NEXT:    sts.l pr,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 8
; PIC-NEXT:    .cfi_offset pr, -8
; PIC-NEXT:    mova .Ltmp4,r0
; PIC-NEXT:    mov.l .Ltmp4,r12
; PIC-NEXT:    add r0,r12
; PIC-NEXT:    mov.l .Ltmp5,r4
; PIC-NEXT:    mova .Ltmp6,r0
; PIC-NEXT:    mov.l .Ltmp6,r1
; PIC-NEXT:    add r0,r1
; PIC-NEXT:    jsr @r1
; PIC-NEXT:    add r12,r4
; PIC-NEXT:    bra .Ltmp7
; PIC-NEXT:    nop
; PIC-NEXT:    .p2align 2
; PIC-NEXT:  .Ltmp5:
; PIC-NEXT:    .ualong mine@TLSGD
; PIC-NEXT:  .Ltmp6:
; PIC-NEXT:    .ualong __tls_get_addr@PLT
; PIC-NEXT:  .Ltmp7:
; PIC-NEXT:    mov.l @r0,r0
; PIC-NEXT:    lds.l @r15+,pr
; PIC-NEXT:    rts
; PIC-NEXT:    mov.l @r15+,r12
; PIC-NEXT:    .p2align 2
; PIC-NEXT:  ! %bb.1:
; PIC-NEXT:  .Ltmp4:
; PIC-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
  %v = load i32, ptr @mine
  ret i32 %v
}

define void @store_hidden(i32 %v) {
; EXEC-LABEL: store_hidden:
; EXEC:         .cfi_startproc
; EXEC-NEXT:  ! %bb.0:
; EXEC-NEXT:    mov.l .Ltmp6,r1
; EXEC-NEXT:    stc gbr,r2
; EXEC-NEXT:    add r1,r2
; EXEC-NEXT:    rts
; EXEC-NEXT:    mov.l r4,@r2
; EXEC-NEXT:    .p2align 2
; EXEC-NEXT:  ! %bb.1:
; EXEC-NEXT:  .Ltmp6:
; EXEC-NEXT:    .ualong hidden@TPOFF
;
; PIC-LABEL: store_hidden:
; PIC:         .cfi_startproc
; PIC-NEXT:  ! %bb.0:
; PIC-NEXT:    mov.l r8,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 4
; PIC-NEXT:    .cfi_offset r8, -4
; PIC-NEXT:    mov.l r12,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 8
; PIC-NEXT:    .cfi_offset r12, -8
; PIC-NEXT:    sts.l pr,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 12
; PIC-NEXT:    .cfi_offset pr, -12
; PIC-NEXT:    mova .Ltmp8,r0
; PIC-NEXT:    mov.l .Ltmp8,r12
; PIC-NEXT:    add r0,r12
; PIC-NEXT:    mov r4,r8
; PIC-NEXT:    mov.l .Ltmp10,r4
; PIC-NEXT:    mova .Ltmp11,r0
; PIC-NEXT:    mov.l .Ltmp11,r1
; PIC-NEXT:    add r0,r1
; PIC-NEXT:    jsr @r1
; PIC-NEXT:    add r12,r4
; PIC-NEXT:    bra .Ltmp12
; PIC-NEXT:    nop
; PIC-NEXT:    .p2align 2
; PIC-NEXT:  .Ltmp10:
; PIC-NEXT:    .ualong hidden@TLSLDM
; PIC-NEXT:  .Ltmp11:
; PIC-NEXT:    .ualong __tls_get_addr@PLT
; PIC-NEXT:  .Ltmp12:
; PIC-NEXT:    mov.l .Ltmp9,r1
; PIC-NEXT:    add r0,r1
; PIC-NEXT:    mov.l r8,@r1
; PIC-NEXT:    lds.l @r15+,pr
; PIC-NEXT:    mov.l @r15+,r12
; PIC-NEXT:    rts
; PIC-NEXT:    mov.l @r15+,r8
; PIC-NEXT:    .p2align 2
; PIC-NEXT:  ! %bb.1:
; PIC-NEXT:  .Ltmp8:
; PIC-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
; PIC-NEXT:  .Ltmp9:
; PIC-NEXT:    .ualong hidden@DTPOFF
  store i32 %v, ptr @hidden
  ret void
}

; The offset of an element is added to the address of the variable.
define ptr @element() {
; EXEC-LABEL: element:
; EXEC:         .cfi_startproc
; EXEC-NEXT:  ! %bb.0:
; EXEC-NEXT:    mov.l r12,@-r15
; EXEC-NEXT:    .cfi_def_cfa_offset 4
; EXEC-NEXT:    .cfi_offset r12, -4
; EXEC-NEXT:    mova .Ltmp7,r0
; EXEC-NEXT:    mov.l .Ltmp7,r12
; EXEC-NEXT:    add r0,r12
; EXEC-NEXT:    mov.l .Ltmp8,r0
; EXEC-NEXT:    stc gbr,r1
; EXEC-NEXT:    mov.l @(r0,r12),r0
; EXEC-NEXT:    bra .Ltmp9
; EXEC-NEXT:    add r0,r1
; EXEC-NEXT:    .p2align 2
; EXEC-NEXT:  .Ltmp8:
; EXEC-NEXT:    .ualong array@GOTTPOFF
; EXEC-NEXT:  .Ltmp9:
; EXEC-NEXT:    add #20,r1
; EXEC-NEXT:    mov r1,r0
; EXEC-NEXT:    rts
; EXEC-NEXT:    mov.l @r15+,r12
; EXEC-NEXT:    .p2align 2
; EXEC-NEXT:  ! %bb.1:
; EXEC-NEXT:  .Ltmp7:
; EXEC-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
;
; PIC-LABEL: element:
; PIC:         .cfi_startproc
; PIC-NEXT:  ! %bb.0:
; PIC-NEXT:    mov.l r12,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 4
; PIC-NEXT:    .cfi_offset r12, -4
; PIC-NEXT:    sts.l pr,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 8
; PIC-NEXT:    .cfi_offset pr, -8
; PIC-NEXT:    mova .Ltmp13,r0
; PIC-NEXT:    mov.l .Ltmp13,r12
; PIC-NEXT:    add r0,r12
; PIC-NEXT:    mov.l .Ltmp14,r4
; PIC-NEXT:    mova .Ltmp15,r0
; PIC-NEXT:    mov.l .Ltmp15,r1
; PIC-NEXT:    add r0,r1
; PIC-NEXT:    jsr @r1
; PIC-NEXT:    add r12,r4
; PIC-NEXT:    bra .Ltmp16
; PIC-NEXT:    nop
; PIC-NEXT:    .p2align 2
; PIC-NEXT:  .Ltmp14:
; PIC-NEXT:    .ualong array@TLSGD
; PIC-NEXT:  .Ltmp15:
; PIC-NEXT:    .ualong __tls_get_addr@PLT
; PIC-NEXT:  .Ltmp16:
; PIC-NEXT:    add #20,r0
; PIC-NEXT:    lds.l @r15+,pr
; PIC-NEXT:    rts
; PIC-NEXT:    mov.l @r15+,r12
; PIC-NEXT:    .p2align 2
; PIC-NEXT:  ! %bb.1:
; PIC-NEXT:  .Ltmp13:
; PIC-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
  ret ptr getelementptr ([8 x i32], ptr @array, i32 0, i32 5)
}

; The model that the variable asks for.
@early = external thread_local(initialexec) global i32

define i32 @load_early() {
; EXEC-LABEL: load_early:
; EXEC:         .cfi_startproc
; EXEC-NEXT:  ! %bb.0:
; EXEC-NEXT:    mov.l r12,@-r15
; EXEC-NEXT:    .cfi_def_cfa_offset 4
; EXEC-NEXT:    .cfi_offset r12, -4
; EXEC-NEXT:    mova .Ltmp10,r0
; EXEC-NEXT:    mov.l .Ltmp10,r12
; EXEC-NEXT:    add r0,r12
; EXEC-NEXT:    mov.l .Ltmp11,r0
; EXEC-NEXT:    stc gbr,r1
; EXEC-NEXT:    mov.l @(r0,r12),r0
; EXEC-NEXT:    bra .Ltmp12
; EXEC-NEXT:    add r0,r1
; EXEC-NEXT:    .p2align 2
; EXEC-NEXT:  .Ltmp11:
; EXEC-NEXT:    .ualong early@GOTTPOFF
; EXEC-NEXT:  .Ltmp12:
; EXEC-NEXT:    mov.l @r1,r0
; EXEC-NEXT:    rts
; EXEC-NEXT:    mov.l @r15+,r12
; EXEC-NEXT:    .p2align 2
; EXEC-NEXT:  ! %bb.1:
; EXEC-NEXT:  .Ltmp10:
; EXEC-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
;
; PIC-LABEL: load_early:
; PIC:         .cfi_startproc
; PIC-NEXT:  ! %bb.0:
; PIC-NEXT:    mov.l r12,@-r15
; PIC-NEXT:    .cfi_def_cfa_offset 4
; PIC-NEXT:    .cfi_offset r12, -4
; PIC-NEXT:    mova .Ltmp17,r0
; PIC-NEXT:    mov.l .Ltmp17,r12
; PIC-NEXT:    add r0,r12
; PIC-NEXT:    mov.l .Ltmp18,r0
; PIC-NEXT:    stc gbr,r1
; PIC-NEXT:    mov.l @(r0,r12),r0
; PIC-NEXT:    bra .Ltmp19
; PIC-NEXT:    add r0,r1
; PIC-NEXT:    .p2align 2
; PIC-NEXT:  .Ltmp18:
; PIC-NEXT:    .ualong early@GOTTPOFF
; PIC-NEXT:  .Ltmp19:
; PIC-NEXT:    mov.l @r1,r0
; PIC-NEXT:    rts
; PIC-NEXT:    mov.l @r15+,r12
; PIC-NEXT:    .p2align 2
; PIC-NEXT:  ! %bb.1:
; PIC-NEXT:  .Ltmp17:
; PIC-NEXT:    .ualong _GLOBAL_OFFSET_TABLE_
  %v = load i32, ptr @early
  ret i32 %v
}
