; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4-nofpu -verify-machineinstrs < %s | FileCheck %s
; RUN: llc -mtriple=sh4-unknown-linux-gnu -filetype=obj -o %t.o < %s
; RUN: llvm-objdump -d %t.o | FileCheck %s --check-prefix=OBJ
; RUN: llc -mtriple=sh4eb-unknown-linux-gnu -filetype=obj -o %t.eb.o < %s
; RUN: llvm-objdump -d %t.eb.o | FileCheck %s --check-prefix=OBJ-EB

; __builtin_trap() is the instruction code that every SuperH leaves
; undefined, not a call of abort(), which a kernel does not have.  GNU as
; has no name for it.  It is not put behind a branch: there it would raise
; the exception for an illegal instruction in a delay slot.

declare void @llvm.trap()
declare void @llvm.debugtrap()
declare void @llvm.ubsantrap(i8)
declare void @callee(i32)

; OBJ:    fd ff         .word 0xfffd
; OBJ-EB: ff fd         .word 0xfffd

define void @trap() {
; CHECK-LABEL: trap:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    .word 0xfffd
  call void @llvm.trap()
  unreachable
}

define void @conditional(i32 %x) {
; CHECK-LABEL: conditional:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    tst r4,r4
; CHECK-NEXT:    bf .LBB1_1
; CHECK-NEXT:  ! %bb.2: ! %ok
; CHECK-NEXT:    mov.l .Ltmp0,r1
; CHECK-NEXT:    jmp @r1
; CHECK-NEXT:    mov #0,r4
; CHECK-NEXT:  .LBB1_1: ! %bad
; CHECK-NEXT:    .word 0xfffd
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.3:
; CHECK-NEXT:  .Ltmp0:
; CHECK-NEXT:    .ualong callee
  %c = icmp eq i32 %x, 0
  br i1 %c, label %ok, label %bad

ok:
  tail call void @callee(i32 0)
  ret void

bad:
  call void @llvm.trap()
  unreachable
}

define i32 @after_call(i32 %x) {
; CHECK-LABEL: after_call:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    mov.l .Ltmp1,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    mov #1,r4
; CHECK-NEXT:    .word 0xfffd
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp1:
; CHECK-NEXT:    .ualong callee
  call void @callee(i32 1)
  call void @llvm.trap()
  unreachable
}

define void @debugtrap() {
; CHECK-LABEL: debugtrap:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    .word 0xfffd
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  call void @llvm.debugtrap()
  ret void
}

define void @ubsantrap(i32 %x) {
; CHECK-LABEL: ubsantrap:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    mov #9,r1
; CHECK-NEXT:    cmp/hi r1,r4
; CHECK-NEXT:    bt .LBB4_2
; CHECK-NEXT:  ! %bb.1: ! %ok
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:  .LBB4_2: ! %bad
; CHECK-NEXT:    .word 0xfffd
  %c = icmp ult i32 %x, 10
  br i1 %c, label %ok, label %bad

ok:
  ret void

bad:
  call void @llvm.ubsantrap(i8 18)
  unreachable
}
