; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=sh4-unknown-linux-gnu -mcpu=sh4-nofpu -verify-machineinstrs < %s | FileCheck %s

; A function with variable arguments stores the registers that hold none of
; its named parameters right below the arguments on the stack, so that
; va_arg walks one row of words.

declare void @llvm.va_start(ptr)
declare void @llvm.va_end(ptr)
declare i32 @printf(ptr, ...)

define i32 @first(i32 %n, ...) {
; CHECK-LABEL: first:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    add #-12,r15
; CHECK-NEXT:    .cfi_def_cfa_offset 12
; CHECK-NEXT:    add #-4,r15
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    mov r5,r0
; CHECK-NEXT:    mov.l r6,@(8,r15)
; CHECK-NEXT:    mov.l r7,@(12,r15)
; CHECK-NEXT:    mov r15,r1
; CHECK-NEXT:    add #4,r1
; CHECK-NEXT:    mov.l r1,@r15
; CHECK-NEXT:    mov.l r0,@(4,r15)
; CHECK-NEXT:    add #4,r15
; CHECK-NEXT:    add #12,r15
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %ap = alloca ptr
  call void @llvm.va_start(ptr %ap)
  %p = load ptr, ptr %ap
  %v = load i32, ptr %p
  call void @llvm.va_end(ptr %ap)
  ret i32 %v
}

; All four registers hold named parameters: the list starts on the stack.
define i32 @fifth(i32 %a, i32 %b, i32 %c, i32 %d, ...) {
; CHECK-LABEL: fifth:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    add #-4,r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    mov r15,r1
; CHECK-NEXT:    add #4,r1
; CHECK-NEXT:    mov.l r1,@r15
; CHECK-NEXT:    mov.l @(4,r15),r0
; CHECK-NEXT:    add #4,r15
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
  %ap = alloca ptr
  call void @llvm.va_start(ptr %ap)
  %p = load ptr, ptr %ap
  %v = load i32, ptr %p
  call void @llvm.va_end(ptr %ap)
  ret i32 %v
}

@fmt = private constant [7 x i8] c"%d %d\0A\00"

define void @caller(i32 %a, i64 %b) {
; CHECK-LABEL: caller:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ! %bb.0:
; CHECK-NEXT:    sts.l pr,@-r15
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    .cfi_offset pr, -4
; CHECK-NEXT:    add #-4,r15
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    mov r6,r7
; CHECK-NEXT:    mov r5,r6
; CHECK-NEXT:    mov r4,r5
; CHECK-NEXT:    mov #7,r1
; CHECK-NEXT:    mov.l r1,@r15
; CHECK-NEXT:    mov.l .Ltmp0,r4
; CHECK-NEXT:    mov.l .Ltmp1,r1
; CHECK-NEXT:    jsr @r1
; CHECK-NEXT:    nop
; CHECK-NEXT:    add #4,r15
; CHECK-NEXT:    lds.l @r15+,pr
; CHECK-NEXT:    rts
; CHECK-NEXT:    nop
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  ! %bb.1:
; CHECK-NEXT:  .Ltmp0:
; CHECK-NEXT:    .ualong .Lfmt
; CHECK-NEXT:  .Ltmp1:
; CHECK-NEXT:    .ualong printf
  %r = call i32 (ptr, ...) @printf(ptr @fmt, i32 %a, i64 %b, i32 7)
  ret void
}
